/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_MQTT_TYPES_H__
#define __TSDEV_API_MQTT_TYPES_H__
#include "tsdev_api_base_types.h"

/*******************************************************************************
 * For mqtt API version 0.0
 ******************************************************************************/
struct tsdev_mqtt_client_config_t
{
    uint8_t sw_version; // 0:v0 1:v1
    uint8_t rev[7];
    union tsdev_mqtt_client_config_pars_t
    {
        uint8_t rev[1024];
        struct tsdev_mqtt_client_config_pars_v0_t
        {
            uint16_t sn_len;
            char sn[900];
        } v0;
        struct tsdev_mqtt_client_config_pars_v1_t
        {
            uint8_t http_address_ipv4[4]; // IP address
            uint8_t pad1[4];              // padding

            uint16_t http_address_ipv6[8]; // IP address
            uint16_t http_port;            // port
            uint8_t connect_type;          // 0:4g 1:wifi 2:ethernet
            uint8_t pad2[5];               // padding

            struct tsdev_mqtt_client_config_protocol_t
            {
                uint16_t keep_alive;         // uint:s
                uint8_t protocol_version;    // version first number, e.g. 3, 4, 5
                uint8_t clean_session;       // 0:clean    1:not clean
                uint8_t qos_level;           // 0:at most; 1:at least; 2:just once
                uint8_t pad3[1];             // padding
                uint16_t connection_timeout; // uint:0.5s
            } protocol;

            struct tsdev_mqtt_client_config_topic_t
            {
                uint8_t sub_topic_nums;
                uint8_t pub_topic_nums;
                uint8_t pad4[6]; // padding

                struct tsdev_mqtt_client_config_topic_sub_t
                {
                    uint8_t sub_pub; // 1:sub 2:pub
                    uint8_t topic_len;
                    uint8_t pad5[6];
                    char topic[128];
                    uint8_t qos_level;
                    uint8_t pad6[7]; // padding
                } sub_list[1];
            } topic;
        } v1;
    } pars;
};

#endif