/*
Copyright (c) 2024:Shanghai TOSUN Technology Ltd.

The software mentioned in this copyright statement includes the automatic code generator function module of TSMaster software and the embedded code it generates. Among them, the copyright of the automatic code generation
function module of TSMaster software is owned by Shanghai TOSUN Technology Ltd..It is protected by the Copyright Law of the People's Republic of China, the Regulations on the Protection of Computer Software, the Intellectual
Property Protection Law, the Patent Law of the People's Republic of China and relevant international copyright treaties, laws, regulations, and other intellectual property laws and treaties.

The embedded code generated by the automatic code generation function of the TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN Technology Ltd. or the original copyright owner of the embedded code,
and is only for personal learning and use. Shanghai TOSUN Technology Ltd. does not provide any kind of warranty, whether express or implied. All risks are borne by the user, and Shanghai TOSUN Technology Ltd. does not
assume any joint responsibility.

The semiconductor manufacturer's LOGO and product model displayed in the TSMaster are only for the convenience of user selection and useage,its copyright and ownership remain with the respective copyright owners,
Shanghai TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for this, and does not assume joint and several liability for any possible infringement.

Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the software mentioned in this copyright statement without notifying users, and reserves the right to modify this license agreement.
*/
#ifndef TSDEV_USR_MODULE_PRIVATE_H
#define TSDEV_USR_MODULE_PRIVATE_H

#include "tsdev_usr_module.h"

struct tsdev_usr_module_core_desc {
	const char* name;
	uint16_t sch_prescaler;
	struct sim_callbacks callbacks;
	uint32_t sig_cnt;
	struct tsdev_cal_sig_def_t* sig_defs;
};

struct tsdev_usr_module_config {
	uint8_t core_cnt;
	const struct tsdev_usr_module_core_desc* cores;
};

extern const struct tsdev_usr_module_config tsdev_usr_module_config;

#endif /* TSDEV_USR_MODULE_PRIVATE_H */
