/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_DISTURB_LIN_H
#define __TSDEV_API_DISTURB_LIN_H
#include "tsdev_types.h"


#define TSDEV_TH7012_NORMAL                   (1 << 0)
#define TSDEV_TH7012_RESET                    (0 << 0)
#define th7012_reset_mask               (1 << 0)

#define TSDEV_TH7012_LIN_BREAK                    (0b00 << 1)
#define TSDEV_TH7012_LIN_BREAK_SYNC               (0b01 << 1)
#define TSDEV_TH7012_LIN_BREAK_SYNC_PID           (0b10 << 1)
#define TSDEV_TH7012_BREAK_TYPE_MASK          (0b11 << 1)

#define TSDEV_TH7012_MASTER_MODE              (1 << 3)
#define TSDEV_TH7012_SLAVE_MODE               (0 << 3)
#define TSDEV_TH7012_MODE_SET_MASK            (1 << 3)

#define TSDEV_TH7012_TX_NODE                  (1 << 4)
#define TSDEV_TH7012_RX_NODE                  (0 << 4)
#define TSDEV_TH7012_NODE_SET_MASK            (1 << 4)

#define TSDEV_TH7012_CHECKSUM_CARRY           (0 << 5)
#define TSDEV_TH7012_CHECKSUM_NO_CARRY        (1 << 5)
#define TSDEV_TH7012_CHECKSUM_CARRY_MASK      (1 << 5)

#define TSDEV_TH7012_CHECKSUM_INVERT          (0 << 6)
#define TSDEV_TH7012_CHECKSUM_NO_INVERT       (1 << 6)
#define TSDEV_TH7012_CHECKSUM_INVERT_MASK     (1 << 6)

#define TSDEV_TH7012_CHECKSUM                 (0 << 7)
#define TSDEV_TH7012_NO_CHECKSUM              (1 << 7)
#define TSDEV_TH7012_CHECKSUM_MASK            (1 << 7)

#define TSDEV_TH7012_DAM_BREAK_MODE           (1 << 8)
#define TSDEV_TH7012_NO_DAM_BREAK_MODE        (0 << 8)
#define TSDEV_TH7012_DAM_MASK                 (1 << 8)

#define TSDEV_TH7012_SEL_POSEDGE_TRIG         (1 << 9)
#define TSDEV_TH7012_SEL_NEGEDGE_TRIG        (0 << 9)
#define TSDEV_TH7012_SEL_EDGE_MASK            (1 << 9)

#define TSDEV_TH7012_INVERT_LIN_BIT_START              (0b0000000001)
#define TSDEV_TH7012_INVERT_LIN_BIT_0                  (0b0000000010)
#define TSDEV_TH7012_INVERT_LIN_BIT_1                  (0b0000000100)
#define TSDEV_TH7012_INVERT_LIN_BIT_2                  (0b0000001000)
#define TSDEV_TH7012_INVERT_LIN_BIT_3                  (0b0000010000)
#define TSDEV_TH7012_INVERT_LIN_BIT_4                  (0b0000100000)
#define TSDEV_TH7012_INVERT_LIN_BIT_5                  (0b0001000000)
#define TSDEV_TH7012_INVERT_LIN_BIT_6                  (0b0010000000)
#define TSDEV_TH7012_INVERT_LIN_BIT_7                  (0b0100000000)
#define TSDEV_TH7012_INVERT_LIN_BIT_STOP               (0b1000000000)

typedef enum {
    tsdev_th7012_invert_disable = 0,
    tsdev_th7012_invert_sync_field = 1,
    tsdev_th7012_invert_pid_field = 2,
    tsdev_th7012_invert_byte0_field = 3,
    tsdev_th7012_invert_byte1_field = 4,
    tsdev_th7012_invert_byte2_field = 5,
    tsdev_th7012_invert_byte3_field = 6,
    tsdev_th7012_invert_byte4_field = 7,
    tsdev_th7012_invert_byte5_field = 8,
    tsdev_th7012_invert_byte6_field = 9,
    tsdev_th7012_invert_byte7_field = 10,
    tsdev_th7012_invert_checksum_field = 11,
}tsdev_disturb_invert_lin_field;
typedef enum {
    tsdev_th7012_disturb_break_field = 0,
    tsdev_th7012_disturb_sync_field = 1,
    tsdev_th7012_disturb_pid_field = 2,
    tsdev_th7012_disturb_byte0_field,
    tsdev_th7012_disturb_byte1_field,
    tsdev_th7012_disturb_byte2_field,
    tsdev_th7012_disturb_byte3_field,
    tsdev_th7012_disturb_byte4_field,
    tsdev_th7012_disturb_byte5_field,
    tsdev_th7012_disturb_byte6_field,
    tsdev_th7012_disturb_byte7_field,
    tsdev_th7012_disturb_byte8_field,
}tsdev_disturb_disturb_lin_field;

typedef enum {
    tsdev_7011 = 0,
    tsdev_7012,
    tsdev_16845,
    tsdev_null,
}th7012_dev_mod;

#ifdef __cplusplus
extern "C"
{
#endif
    typedef struct th7012_lin_segment_config {
        uint16_t bit_segment_div;//bit_segment_div*bit_segment_timming*25ns=TBit;bps=40M/(bit_segment_div*bit_segment_timming)
        uint16_t bit_segment_timming;
        uint32_t break_bit_len;
        uint32_t break_del_bit_len;
        uint32_t resp_space_delay;
        uint32_t ibs0;
        uint32_t ibs1;
        uint32_t ibs2;
        uint32_t ibs3;
        uint32_t ibs4;
        uint32_t ibs5;
        uint32_t ibs6;
        uint32_t ibs7;
        uint32_t sync_del;
        uint32_t pid_del;
        uint32_t sync_byte;
    }th7012_lin_segment_config;

    typedef struct th7012_lin_segment_config_sp {
        uint32_t break_bit_len;
        uint32_t break_del_bit_len;
        uint32_t sync_byte;
        uint32_t sync_del;
        uint32_t pid;
        uint32_t pid_del;
        uint32_t pos;
        uint32_t pos_status;
        uint32_t ebs_sp_result;
        uint32_t lbs_sp_result;
    }th7012_lin_segment_config_sp;

    typedef struct th7012_sample_point {
        float ebs_sp_result;
        float lbs_sp_result;
    }th7012_sample_point;

    typedef struct th7012_lin_field_timing {
        uint32_t break_time;
        uint32_t break_del_time;
        uint32_t header_time;
        uint32_t respon_time;
        uint32_t respon_del_time;
        uint32_t frame_time;
        uint32_t wakeup_frame_time;
        uint32_t rx_pid;
    }th7012_lin_field_timing;


    typedef struct th7012_lin_transmit_data
    {
        uint8_t send_mode;
        uint8_t pid;
        uint8_t data_len;
        uint8_t data[8];
    }th7012_lin_transmit_data;
    typedef int (*tsdev_th7012_lin_recv)(tsdev_handle_t handle, void* usr_arg, uint8_t pid, const uint8_t* Data, uint8_t Len, uint8_t checksum);
    struct th7012_instance
    {
        uint32_t timeout_ms;
        tsdev_th7012_lin_recv lin_recv_call;
        void* lin_recv_call_usr_arg;

    };

#ifdef __cplusplus
}
#endif

#endif