/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef TSDEV_API_TX1000_TYPES_H
#define TSDEV_API_TX1000_TYPES_H

#include "tsdev_types.h"




#define TSDEV_TX1000_GET_WORD(x,off)      (*( (unsigned int *)((unsigned long long)x + (unsigned long long)off) ) )
#define TSDEV_TX1000_SET_WORD(x,off,data) (*( (unsigned int *)((unsigned long long)x + (unsigned long long)off) ) = data)


typedef enum
{
    tsdev_cycle_0 = 0,
    tsdev_cycle_1,
    tsdev_cycle_2,
    tsdev_cycle_3,
    tsdev_cycle_4,
    tsdev_cycle_5,
    tsdev_cycle_6,
    tsdev_cycle_7,
    tsdev_cycle_8,
    tsdev_cycle_9
}tsdev_tx1000_cycle_idx;
typedef enum tsdev_ChipType
{
    tsdev_TC39x,
    tsdev_TC234,
    tsdev_SupportChipNum
}tsdev_tx1000_DebugPortChipType;
typedef enum tsdev_SupportDebugProtocol
{
    tsdev_DapProtocol,
    tsdev_SwdProtocol,
    tsdev_JtagProtocol,
    tsdev_SupportProtocolNum
}tsdev_tx1000_DebugPortProtocol;

typedef enum tsdev_DapSubProtocol
{
    tsdev_DapStandardMode,
    tsdev_DapWideMode,
    tsdev_UnidirectionalMode,
    tsdev_UnidirectionalWideMode,
}tsdev_tx1000_DebugPortDapSubProtocol;
//#define ARM_SWD         (2u)
struct xcp_init_pars_t {
    uint8_t addr_bits;
    uint8_t enable_slave_block_mode;
    uint8_t enable_daq;
    uint8_t enable_pgm;
    uint8_t enable_stim;
    uint8_t enable_cal_pag;
    uint8_t enable_get_comm_mode_info;
    uint8_t timestamp_size;
    uint8_t max_unlock_attempts;
    uint8_t checksum_type;
    uint8_t daq_timestamp_unit;
    uint8_t max_event;
    uint8_t max_cto_len;
    uint8_t max_daq_cnt;
    uint8_t max_odt_cnt;
    uint8_t id_type;
    uint16_t max_dto_len;
    uint16_t rev[3];
    //struct xcp_if_event_par_t* event_pars;
};
struct tosun_xcp_packet_header_t {
    uint64_t timestamp_us;
    uint16_t len;
    uint16_t rev[3];
    //payload data
    //payload format n*(2 bytes len,len bytes xcp packet)
    //for example data[0x00,0x01,0xff,0x00,0x01,0xff] xcp packet is 2 positive response,first byte and second byte is len of first xcp packet(little-endian),the third byte is xcp packet payload;
};
typedef tsdev_err_t(*xcp_rx_callback_t)(tsdev_handle_t handle, void* usr_arg
    , tsdev_tsmsg_t msg,
    const void* header,
    struct tosun_xcp_packet_header_t* data);
#endif
