/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_IO_H
#define __TSDEV_API_IO_H

#include "tsdev_types.h"

#ifdef __cplusplus
extern "C"
{
#endif

	TSDEV_API tsdev_api_io_cmd_async(tsdev_handle_t handle,
									 const union tsdev_dev_io_cmd_resp *cmd);
	/**
	 * @brief Execute multiple IO commands asynchronously in one transaction
	 *		  Results arrive via callback, resp is an array which has elements of cmd_cnt.
	 *
	 * @param handle Device handle
	 * @param cmd_array Array of command structures
	 * @param cmd_cnt Number of commands (1-120)
	 * @return 0 if commands queued successfully, error code otherwise
	 *
	 * @example
	 * union tsdev_dev_io_cmd_resp cmds[n];
	 * cmds[0] = {}; // Read DIDO inputs
	 * cmds[1] = {}; // Set AIAO outputs
	 * cmds[2] = {}; // Set PWM outputs
	 * ...
	 * cmds[n - 1] = {}; // Read/Set xxx input/ouput
	 *
	 * tsdev_api_io_cmd_burst_async(handle, cmds, n);
	 */
	TSDEV_API tsdev_api_io_cmd_burst_async(tsdev_handle_t handle,
									 const union tsdev_dev_io_cmd_resp* cmd_array, 
								     uint8_t cmd_cnt);
#ifndef LIBTSDEVBASERT_EXPORTS
	TSDEV_API tsdev_api_io_cmd_reg_event(tsdev_handle_t handle,
										 void *usr_arg,
										 const tsdev_io_cmd_event_t event);
	TSDEV_API tsdev_api_io_cmd_unreg_event(tsdev_handle_t handle,
										   void *usr_arg,
										   const tsdev_io_cmd_event_t event);
	TSDEV_API tsdev_api_io_cmd_unreg_events(tsdev_handle_t handle);

	TSDEV_API tsdev_api_io_daq_reg_event(tsdev_handle_t handle,
										 void *usr_arg,
										 const tsdev_io_daq_event_t event);
	TSDEV_API tsdev_api_io_daq_unreg_event(tsdev_handle_t handle,
										   void *usr_arg,
										   const tsdev_io_daq_event_t event);
	TSDEV_API tsdev_api_io_daq_unreg_events(tsdev_handle_t handle);
#endif
#ifdef __cplusplus
}
#endif

#endif
