/**
 * Copyright (c) 2025:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_ECAT_TYPES_H
#define __TSDEV_API_ECAT_TYPES_H
#include "tsdev_api_base_types.h"

typedef tsdev_err_t(*tsdev_api_ethercat_data_stream_event_t)(tsdev_handle_t handle, void* usr_arg, tsdev_tsmsg_t msg,
	uint16_t rev, uint16_t fsize, const struct tsdev_ecat_data_stream_data_t* dataset);

/*--------------------------------------------------------------for ethercat----------------------------------------------------*/
enum tsdev_ecat_status {
	tsdev_ecat_boot = 0
	, tsdev_ecat_init
	, tsdev_ecat_preop
	, tsdev_ecat_safeop
	, tsdev_ecat_op
};
struct tsdev_ecat_master_status_t {
	//bit 0- Master is connected to a slave.
	//bit 1- redundancyEffective
	//bit 2-7:rev
	uint8_t status;
	uint8_t masterState;//enum tsdev_ecat_status
	uint16_t slavesOnline;//Number of slaves online.
	uint16_t slavesCreated;//Number of created virtual slave objects.
	uint16_t slavesCreatedAndOnline;//Number of created slaves that are online.
	uint16_t framesSent;
	uint16_t framesLost;
	uint32_t rev;
};
struct tsdev_ecat_slave_status_t {
	//bit 0- slave is online
	//bit 1- Virtual slave object has been created
	//bit 2-7:rev
	uint8_t status;
	uint8_t slaveState; //enum tsdev_ecat_status
	uint16_t vendor;
	uint16_t product;
	uint16_t revision;
	uint16_t id; //ID of the slave(0 means no ID).
	uint16_t relPosition;//Relative position to the last slave with ID.
	uint16_t absPosition; //Absolute position of the slave.
	uint8_t linkState[4];
	/*
	0x0000	No error
	0x0001	Unspecified error
	0x0002	No Memory
	0x0003	Invalid Device Setup
	0x0005	Reserved due to compatibility reasons
	0x0011	Invalid requested state change
	0x0012	Unknown requested state
	0x0013	Bootstrap not supported
	0x0014	No valid firmware
	0x0015	Invalid mailbox configuration
	0x0016	Invalid mailbox configuration
	0x0017	Invalid sync manager configuration
	0x0018	No valid inputs available
	0x0019	No valid outputs
	0x001A	Synchronization error
	0x001B	Sync manager watchdog
	0x001C	Invalid sync manager types
	0x001D	Invalid output configuration
	0x001E	Invalid input configuration
	0x001F	Invalid watchdog configuration
	0x0020	Slave needs cold start
	0x0021	Slave needs INIT
	0x0022	Slave needs PREOP
	0x0023	Slave needs SAFEOP
	0x0024	Invalid input mapping
	0x0025	Invalid output mapping
	0x0026	Inconsistent settings
	0x0027	FreeRun not supported
	0x0028	SyncMode not supported
	0x0029	FreeRun needs 3Buffer Mode
	0x002A	Background watchdog
	0x002B	No valid inputs or outputs
	0x002C	Fatal sync error
	0x002D	No sync error
	0x0030	Invalid DC sync configuration
	0x0031	Invalid DC latch configuration
	0x0032	PLL error
	0x0033	DC sync IO error
	0x0034	DC sync timeout error
	0x0035	DC invalid sync cycle time
	0x0036	DC sync0 cycle time
	0x0037	DC sync1 cycle time
	0x0041	MBX_AOE
	0x0042	MBX_EOE
	0x0043	MBX_COE
	0x0044	MBX_FOE
	0x0045	MBX_SOE
	0x004F	MBX_VOE
	0x0050	EEPROM no access
	0x0051	EEPROM error
	*/
	uint16_t statusCode;
	uint8_t rev[6];
};

enum tsdev_ecat_data_type_t {
	tsdev_ecat_type_unknown = 0
	, tsdev_ecat_type_boolean
	, tsdev_ecat_type_int8
	, tsdev_ecat_type_int16
	, tsdev_ecat_type_int24
	, tsdev_ecat_type_int32
	, tsdev_ecat_type_int40
	, tsdev_ecat_type_int48
	, tsdev_ecat_type_int56
	, tsdev_ecat_type_int64
	, tsdev_ecat_type_uint8
	, tsdev_ecat_type_uint16
	, tsdev_ecat_type_uint24
	, tsdev_ecat_type_uint32
	, tsdev_ecat_type_uint40
	, tsdev_ecat_type_uint48
	, tsdev_ecat_type_uint56
	, tsdev_ecat_type_uint64
	, tsdev_ecat_type_real32
	, tsdev_ecat_type_real64
	, tsdev_ecat_type_visible_string
	, tsdev_ecat_type_octet_string
	, tsdev_ecat_type_unicode_string
	, tsdev_ecat_type_time_of_day
	, tsdev_ecat_type_time_difference
	, tsdev_ecat_type_domain
};
enum tsdev_ecat_obj_type_t {
	tsdev_ecat_obj_pdo = 1
	, tsdev_ecat_obj_sdo = 2
	, tsdev_ecat_obj_idn = 4
	, tsdev_ecat_obj_readable = 8
	, tsdev_ecat_obj_writeable = 16
	, tsdev_ecat_obj_active = 32
	, tsdev_ecat_obj_mappable = 64
	, tsdev_ecat_obj_safety = 128
};

struct tsdev_ecat_datavar_info_t {
	//mask according to tsdev_ecat_obj_type_t
	uint8_t obj_type;
	uint8_t data_type; // tsdev_ecat_data_type_t
	uint16_t sub_index;
	uint32_t bit_length;
	char name[32];
};
struct tsdev_ecat_dataobj_info_t {
	//mask according to tsdev_ecat_obj_type_t
	uint8_t obj_type;
	uint8_t rev;
	uint16_t var_count;
	uint16_t index;
	uint16_t syncIndex;
	char name[32];
	uint32_t bitLength;
	uint32_t rev1;
};

struct tsdev_ecat_slave_dc_info_t {
	char dc_op_mode[256];
	char dc_op_mode_desc[256];
};
struct tsdev_ecat_slave_dc_par_t {
	uint16_t assignActivate; //Command word for DC activation and assignment(comes from device XML).
	//Bit 0	0 continous / 1 single of positive Edge.
	//Bit 1	0 continous / 1 single of negative Edge.
	uint8_t latch0Control;
	//Bit 0	0 continous / 1 single of positive Edge.
	//Bit 1	0 continous / 1 single of negative Edge.
	uint8_t latch1Control;
	//= 0	Acknowledge Mode.
	//> 0	Auto reset.
	int32_t pulseLength;
	//=0	Single shot.
	//> 0	Cyclic mode.
	int32_t cycleTimeSync0;
	//>= 0	calculated with factor * cycle time of timer.
	//< 0	calculated with - factor / cycle time of timer.
	int32_t cycleTimeSync0Factor;
	//Shift time of Sync0 relative to timer.
	int32_t shiftTimeSync0;
	//>=0	calculated with factor * cycle time of timer.
	//< 0	calculated with - factor / cycle time of timer.
	int32_t shiftTimeSync0Factor;
	//Cycle time of Sync1.
	int32_t cycleTimeSync1;
	//>=0	calculated with factor * cycle time of Sync0.
	//< 0	calculated with - factor / cycle time of timer.
	int32_t cycleTimeSync1Factor;
	//Shift time of Sync1 relative Sync0.
	int32_t shiftTimeSync1;
	//>=0	calculated with factor * cycle time of Sync0.
	//< 0	calculated with - factor / cycle time of timer.
	int32_t shiftTimeSync1Factor;
};

struct tsdev_ecat_slave_info_t {
	uint16_t revision;
	uint32_t serial;
	char group[32];
	char image[32];
	char order[32];
	char name[32];
	uint16_t obj_cnt;
	uint16_t dc_cnt;
};
struct tsdev_ecat_dataset_map_per_t {
	uint16_t slave_idx;
	uint16_t obj_idx;
	uint16_t cur_obj_idx;
	uint16_t var_idx;
	uint16_t cur_var_idx;
	uint16_t byte_offset;
	uint16_t bit_offset;
	uint16_t bit_length;
	uint16_t rev;
};

struct tsdev_ecat_data_stream_data_t {
	union tsdev_ecat_data_stream_data_t_type {
		struct tsdev_ecat_data_stream_data_t_type_dataset {
			//0-dataset post, 1-dataset update
			uint8_t type;
			uint8_t rev[1];
			uint16_t dataset_idx;
			uint16_t rev1;
			uint16_t cnt;
		}dataset;
		struct tsdev_ecat_data_stream_data_t_type_dataobj {
			//2-data object post, 3-data object update
			uint8_t type;
			uint8_t rev[1];
			uint16_t slave_idx;
			uint16_t var_idx;
			uint16_t cnt;
		}dataobj;
		struct tsdev_ecat_data_stream_data_t_type_mem {
			//4-slave mem read, 5-slave mem write
			uint8_t type;
			uint8_t rev[1];
			uint16_t slave_idx;
			uint16_t mem_addr;
			uint16_t cnt;
		}mem;
	}header;
	uint64_t time_stamp_us;
	uint8_t data[4096];
};

#endif