/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_USRMODULE_TYPES_H
#define __TSDEV_API_USRMODULE_TYPES_H
#include "tsdev_types.h"
#include "tsdev_api_base_types.h"

enum usrmodule_cmd_t
{
    USRMODULE_CMD_START_DOWNLOAD_IMAGE = 0,
    USRMODULE_CMD_START_RUN_IMAGE,
    USRMODULE_CMD_SET_RUN_IMAGE_TIME,
    USRMODULE_CMD_SET_CYCLE_IMAGE_TIME,
    USRMODULE_CMD_STOP_RUN_IMAGE,
    USRMODULE_CMD_ENABLE_AUTOSTART,
    USRMODULE_CMD_TYPE_MAX_CNT,
};
struct tsdev_dev_usrmodule_cmd_t
{
    uint8_t cmd_type;
    uint8_t rev[7];
    uint32_t image_runtime;
};
// total_len: total len of transmit (TX/RX)
// data: data trans complete of this callback
typedef void (*tsdev_usrmodule_data_trans_callback_t)(tsdev_handle_t handle,
                                                uint64_t total_len,
                                                const uint8_t *data,
                                                uint16_t len,
                                                tsdev_err_t err);

typedef tsdev_err_t (*tsdev_dev_usrmodule_cmd_event_t)(tsdev_handle_t handle, void* usr_arg, tsdev_tsmsg_t msg,
 uint16_t fdid, uint16_t fsize, const struct tsdev_dev_usrmodule_cmd_t* cmd_p);

#endif
