/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_SENT_TYPES_H
#define __TSDEV_API_SENT_TYPES_H
#include "tsdev_api_base_types.h"

typedef tsdev_err_t (*tsdev_sent_cmd_event_t)(tsdev_handle_t handle, void *usr_arg, tsdev_tsmsg_t msg,
                                              uint16_t rev, uint16_t fsize, const struct tsdev_sentif_ecu_ch_cmd_rsp_t *data);
typedef tsdev_err_t (*tsdev_sent_frame_event_t)(tsdev_handle_t handle, void *usr_arg, tsdev_tsmsg_t msg,
                                                uint16_t rev, uint16_t fsize, const struct tsdev_sentif_ecu_ch_frame_rx_t *data);

typedef enum
{
    tsdev_sent_success,
    tsdev_sent_error_with_out_of_range,
    tsdev_sent_error_with_not_support
} tsdev_sentif_ecu_ch_status_t;

struct tsdev_sentif_ecu_spc_cfg_t
{
    uint8_t trigger_mode;       /*Single trigger or loop trigger, 0 for single trigger and 1 for loop trigger*/
    uint8_t pulse_length;       /*Trigger signal low level time.*/
    uint8_t pulse_delay_length; /*Trigger signal low level delay activation time*/
    uint8_t rev;
    uint32_t trigger_period; /*The time for loop triggering, unit is microseconds*/
};

struct tsdev_sentif_ecu_common_msg_t
{
    uint32_t data;
    uint8_t statusNibble;
    uint8_t crc;
    uint8_t rev[2];
};

struct tsdev_sentif_ecu_serial_msg_t
{
    uint8_t msg_id;
    uint8_t rev1[1];
    uint16_t msg_data;
    uint8_t crc;
    uint8_t rev2[3];
};

struct tsdev_sentif_ecu_ch_config_t
{
    uint8_t utick;        /* The communication time for one tick in SNET is mostly 3 microseconds, ranging from 3 to 90 microseconds.*/
    uint8_t frame_length; /* SENT data supports a length of 0 to 8 half-bytes.*/
    uint8_t spc_mode;     /* Enable SPC mode for the above parameters to be effective. 0 for disabled, 1 for enabled.*/
    uint8_t rev[5];
    struct tsdev_sentif_ecu_spc_cfg_t spc_cfg; /* SPC configuration parameters*/
};

struct tsdev_sentif_ecu_ch_cmd_req_t
{
    uint8_t ch_idx; // TC4016 support 20 sent channel
    uint8_t sent_per_handle;
    uint8_t ch_en;
    uint8_t rev[5];
    struct tsdev_sentif_ecu_ch_config_t config;
};

struct tsdev_sentif_ecu_ch_cmd_rsp_t
{
    uint8_t ch_idx; // TC4016 support 20 sent channel
    uint8_t cmd_rsp;
    uint8_t rev[6];
};

struct tsdev_sentif_ecu_ch_frame_rx_t
{
    uint64_t timestamp;
    uint8_t ch_idx;
    uint8_t msg_type; // 0: no message; 1 common message; 2 serial message;
    /** error_status: */
    // bit0: rxOverflow;              /*  Receive Buffer Overflow */
    // bit1: txUnderflow;             /*  Transmit Buffer Overflow error */
    // bit2: errorFreqRange;          /*  Frequency Range error */
    // bit3: errorFreqDrift;          /*  Frequency Drift error */
    // bit4: errorWrongNumOfNibbles;  /*  Wrong Number of Nibbles error */
    // bit5: errorNibbleValueRange;   /*  Wrong Nibble Value error */
    // bit6: errorCrcFast;            /*  CRC error for Fast Message */
    // bit7: errorWrongStatusCom;     /*  Wrong Status Nibble */
    // bit8: errorCrcSlowSerial;      /*  CRC error for Short Serial Message */
    // bit9: errorWatchdog;           /*  Watchdog errors */
    // bit10 - 15: rev
    uint16_t error_status;
    uint8_t tx_info;
    uint8_t rev[3];
    union sentif_ch_data
    {
        struct tsdev_sentif_ecu_common_msg_t common_msg;
        struct tsdev_sentif_ecu_serial_msg_t serial_msg;
    } ch_data;
};

#endif /* __TSDEV_API_SENT_TYPES_H */