/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_TH7011_H
#define __TSDEV_API_TH7011_H
#include "tsdev_types.h"
#include "tsdev_api_disturb_can.h"
#include "tsdev_api_dev_th7012.h"

#ifdef __cplusplus
extern "C"
{
#endif

     /**
     * @delivering initialization data.
     * @param[in] handle pointer to tsdev handle.
     * @param[in] conf pointer to application layer specific data.
     * @param[in] timeout timeout in ms.
     * @return refer to tsdev_err_t.
     */
    TSDEV_API tsdev_api_th7011_init(tsdev_handle_t handle, const tsdev_th7011_can_Control_t* conf);

    /**
    * @sampling point test and secondary sampling point(unopen).
    * @param[in] handle pointer to tsdev handle.
    * @param[in] conf pointer to application layer specific data.
    * @param[out] sample_point_result returned test results.
    * @return refer to tsdev_err_t.
    */
	TSDEV_API tsdev_api_tsdev_sample_point_test(tsdev_handle_t handle, const tsdev_sample_point_t* conf, tsdev_sample_point_result_t* sample_point_result);
	
    /**
    * @delivery disturb configuration.
    * @param[in] handle pointer to tsdev handle.
    * @param[in] conf pointer to application layer specific data.
    * @return refer to tsdev_err_t.
    */
    TSDEV_API tsdev_api_th7011_disturb_config(tsdev_handle_t handle, const tsdev_disturb_Frame_t* conf);

    /**
    * @delivery disturb configuration.
    * @param[in] handle pointer to tsdev handle.
    * @param[in] conf pointer to application layer specific data.
    * @return refer to tsdev_err_t.
    */
    TSDEV_API tsdev_api_th7011_disturb_config_trans(tsdev_handle_t handle, const tsdev_disturb_Frame_t* conf);

    /**
    * @delivering initialization data.
    * @param[in] handle pointer to tsdev handle.
    * @param[in] conf pointer to application layer specific data.
    * @param[in] timeout timeout in ms.
    * @return refer to tsdev_err_t.
    */
    TSDEV_API tsdev_api_th7011_send_can_frame(tsdev_handle_t handle, struct tsdev_tx_frame_config_t* conf);

    /**
    * @delivering frame sequence configuration data.
    * @param[in] handle pointer to tsdev handle.
    * @param[in] conf pointer to application layer specific data.
    * @return refer to tsdev_err_t.
    */
    TSDEV_API tsdev_api_th7011_send_sequence(tsdev_handle_t handle, tsdev_sequence_config_t* conf);

    /**
    * @delivering configuration of port data.
    * @param[in] handle pointer to tsdev handle.
    * @param[in] conf pointer to application layer specific data.
    * @return refer to tsdev_err_t.
    */
    TSDEV_API tsdev_api_th7011_port_config(tsdev_handle_t handle, tsdev_port_config_t* conf);

    /**
    * @delivering stop jamming command data.
    * @param[in] handle pointer to tsdev handle.
    * @param[in] conf pointer to application layer specific data.
    * @return refer to tsdev_err_t.
    */
    TSDEV_API tsdev_api_th7011_stop(tsdev_handle_t handle);

    /**
    * @Query Result.
    * @param[in] handle pointer to tsdev handle.
    * @param[out] times returns the result of the number of queries.
    * @return refer to tsdev_err_t.
    */
    TSDEV_API tsdev_api_th7011_query(tsdev_handle_t handle, times_query_t * times_query);
                                          

#ifdef __cplusplus
}
#endif

#endif