/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_ETH_H
#define __TSDEV_API_ETH_H
#include "tsdev_types.h"

#ifdef __cplusplus
extern "C"
{
#endif

#ifndef LIBTSDEVBASERT_EXPORTS
	//api for host only
    TSDEV_API tsdev_api_eth_register_cmd_event(tsdev_handle_t handle, void* usr_arg, const tsdev_api_eth_cmd_event_t ACmdEvent);
    TSDEV_API tsdev_api_eth_unregister_cmd_event(tsdev_handle_t handle, void* usr_arg, const tsdev_api_eth_cmd_event_t ACmdEvent);
    TSDEV_API tsdev_api_eth_unregister_cmd_events(tsdev_handle_t handle);

    TSDEV_API tsdev_api_eth_register_frame_event(tsdev_handle_t handle, void* usr_arg, const tsdev_api_eth_frame_event_t AFrameEvent);
    TSDEV_API tsdev_api_eth_unregister_frame_event(tsdev_handle_t handle, void* usr_arg, const tsdev_api_eth_frame_event_t AFrameEvent);
    TSDEV_API tsdev_api_eth_unregister_frame_events(tsdev_handle_t handle);
#endif
	//api for host and rt
    TSDEV_API tsdev_api_eth_tx_cmd_async(tsdev_handle_t handle,
        const struct tsdev_PC_ETH_CMD_REQ* ACmdReq);

    TSDEV_API tsdev_api_eth_transmit_async(tsdev_handle_t handle,
        const struct tsdev_ETH_Header* AEthernetHeader);

    TSDEV_API tsdev_api_eth_fifo_receive_msgs(tsdev_handle_t handle,
        void* usr_arg,
        uint32_t max_rx_cnt,
        tsdev_api_eth_frame_event_t frame_handle);
#ifdef __cplusplus
}
#endif

#endif
