/**
 * Copyright (c) 2025:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_SIM_H
#define __TSDEV_API_SIM_H

#include "tsdev_types.h"



#ifdef __cplusplus
extern "C"
{
#endif

#ifndef LIBTSDEVBASERT_EXPORTS
#ifdef _MSC_VER
	TSDEV_API tsdev_api_sim_avaliabli_resource(uint32_t* core_sys, uint32_t* core_rt, uint32_t* ram_kb);
#endif
	//api for host only
	TSDEV_API tsdev_api_sim_load(tsdev_handle_t handle, const char* sim_module_path, uint8_t disable_auto_start);
	TSDEV_API tsdev_api_sim_app_start(tsdev_handle_t handle);
	TSDEV_API tsdev_api_sim_app_stop(tsdev_handle_t handle);
	TSDEV_API tsdev_api_sim_unload(tsdev_handle_t handle);
#ifdef _MSC_VER
	//windows rt only
	TSDEV_API tsdev_api_sim_share_mem(tsdev_handle_t handle, void** mem_p);
#endif
	TSDEV_API tsdev_api_sim_sig_get_cnt(tsdev_handle_t handle, uint8_t core_idx, uint32_t* cnt);
	TSDEV_API tsdev_api_sim_sig_get_defs(tsdev_handle_t handle, uint8_t core_idx, uint32_t sig_start_idx, uint32_t read_cnt, struct tsdev_cal_sig_def_t* sig_defs);

	TSDEV_API tsdev_api_sim_sig_poll(tsdev_handle_t handle, uint8_t core_idx, uint32_t sig_idx, tsdev_cal_sig_val_t* val);
	TSDEV_API tsdev_api_sim_sig_cal(tsdev_handle_t handle, uint8_t core_idx, uint32_t sig_idx, const tsdev_cal_sig_val_t* val);
	TSDEV_API tsdev_api_sim_layout_overview(tsdev_handle_t handle, struct tsdev_sim_layout_overview_t* overview);
	TSDEV_API tsdev_api_sim_layout_get_component(tsdev_handle_t handle, uint8_t component_idx, struct tsdev_sim_component_desc_t* desc);
	TSDEV_API tsdev_api_sim_layout_get_thread(tsdev_handle_t handle, uint8_t thread_idx, struct tsdev_sim_thread_desc_t* desc);

	// layout_out->revision increases after each signal/group register or unregister.
	// layout_out->groups stays valid until the next revision or until the simulation is unloaded.
	TSDEV_API tsdev_api_sim_dp_layout_query(tsdev_handle_t handle,
		struct tsdev_dp_pool_static_cfg* layout_out);

	TSDEV_API tsdev_api_sim_dp_signal_query(tsdev_handle_t handle,
		tsdev_dp_signal_id_t sig_id,
		struct tsdev_cal_sig_def_t* cal_def); // cal_def content is copied to caller-provided storage
	// h_p and data_p are copied by function
	TSDEV_API tsdev_api_sim_dp_group_publish(tsdev_handle_t handle,
		const struct tsdev_dp_group_publish_header* h_p, const void* data_p, size_t data_len);
	TSDEV_API tsdev_api_sim_register_dp_group_event(tsdev_handle_t handle, void* usr_arg, const tsdev_api_dp_group_event_t ACmdEvent);
	TSDEV_API tsdev_api_sim_unregister_dp_group_event(tsdev_handle_t handle, void* usr_arg, const tsdev_api_dp_group_event_t ACmdEvent);
	TSDEV_API tsdev_api_sim_unregister_dp_group_events(tsdev_handle_t handle);
	TSDEV_API tsdev_api_sim_dp_group_publish_get(tsdev_handle_t handle,
		tsdev_dp_group_id_t group_id,
		uint8_t* publish_enabled,
		uint8_t target_bitmap[TSDEV_DP_TARGET_BITMAP_BYTES]);
	TSDEV_API tsdev_api_sim_dp_group_publish_set(tsdev_handle_t handle,
		tsdev_dp_group_id_t group_id,
		uint8_t publish_enabled,
		const uint8_t target_bitmap[TSDEV_DP_TARGET_BITMAP_BYTES]);
	TSDEV_API tsdev_api_sim_dp_group_set_active(tsdev_handle_t handle,
		tsdev_dp_group_id_t group_id,
		uint8_t is_active);
	TSDEV_API tsdev_api_sim_dp_signal_register(tsdev_handle_t handle,
		const struct tsdev_cal_sig_def_t* sig_def,
		tsdev_dp_signal_id_t* new_signal_id);
	TSDEV_API tsdev_api_sim_dp_signal_set_active(tsdev_handle_t handle,
		tsdev_dp_signal_id_t sig_id,
		uint8_t is_active);
	TSDEV_API tsdev_api_sim_dp_group_register(tsdev_handle_t handle,
		const struct tsdev_dp_group_desc* desc,
		tsdev_dp_group_id_t* new_group_id);
	TSDEV_API tsdev_api_sim_dp_group_fifo_receive_msgs(tsdev_handle_t handle,
		void* usr_arg,
		uint32_t max_rx_cnt,
		tsdev_api_dp_group_event_t event_handle);

	TSDEV_API tsdev_api_sim_dp_signal_map_register(tsdev_handle_t handle,
		tsdev_dp_signal_id_t source_signal_id,
		tsdev_dp_signal_id_t target_signal_id,
		uint8_t force_raw_map);
	TSDEV_API tsdev_api_sim_dp_signal_map_unregister(tsdev_handle_t handle,
		tsdev_dp_signal_id_t source_signal_id,
		tsdev_dp_signal_id_t target_signal_id);
	TSDEV_API tsdev_api_sim_dp_signal_map_query(tsdev_handle_t handle,
		tsdev_dp_signal_id_t source_signal_id,
		tsdev_dp_signal_id_t target_signal_id,
		uint8_t *is_maped, uint8_t* is_phy_map);
	TSDEV_API tsdev_api_sim_dp_signal_map_flush(tsdev_handle_t handle);


#endif
#ifdef __cplusplus
}
#endif

#endif
