/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */

#ifndef __TSDEV_API_ECAT_CONFIG_TYPES_H
#define __TSDEV_API_ECAT_CONFIG_TYPES_H

#include "tsdev_api_base_types.h"

typedef enum tsdev_ecat_can_filter_type_e
{
    range_filter,
    specified_id_filter,
    mask_filter
} tsdev_ecat_can_filter_type_t;

typedef enum tsdev_ecat_can_filter_option_e
{
    recv_msg,
    reject_msg,
} tsdev_ecat_can_filter_option_t;

typedef enum tsdev_ecat_mode_e
{
    default_mode,
    flexible_mapping_mode,
    tsdev_mode,
} tsdev_ecat_mode_t;

typedef enum tsdev_ecat_can_id_type_e
{
    std_id_frame,
    ext_id_frame,
} tsdev_ecat_can_id_type_t;

typedef enum tsdev_ecat_config_type_e
{
    ecat_config = 0,
    can_filter_config,
} tsdev_ecat_config_type_t;

// ATTENTION!!!!
// The standard frame filter and extended frame filter share a 160-byte memory space
// A standard frame filter occupies 4 bytes, while an extended frame filter occupies 8 bytes
// It supports up to 40 standard frame filters or 20 extended frame filters
// A flexible combination of both is also allowed, provided that the total memory usage does not exceed 160 bytes
// This description applies only to gw1040
typedef struct tsdev_ecat_can_filter_config_s
{
    uint64_t config_type;   // tsdev_ecat_config_type_t
    union config_info_u {
        struct ecat_config
        {
            uint8_t if_report_tx_msg;
            uint8_t ecat_running_mode;
            uint8_t resv[6];
        } ecat_config;
        struct can_filter_config_s
        {
            uint8_t can_chn;
            uint8_t filter_cnt;
            uint8_t resv[6];
            struct filter_config_s {
                uint8_t can_id_type;    // tsdev_ecat_can_id_type_t
                uint8_t filter_type;    // tsdev_ecat_can_filter_type_t
                uint8_t filter_option;  // tsdev_ecat_can_filter_option_t
                uint8_t resv[5];
                union filter_pars_u {
                    struct range_filter_s {
                        uint32_t start_id;
                        uint32_t end_id;
                    } range_filter;
                    struct specified_id_filter_s {
                        uint32_t id1;
                        uint32_t id2;
                    } specified_id_filter;
                    struct mask_filter_s {
                        uint32_t filter_id;
                        uint32_t filter_mask;
                    } mask_filter;
                } filter_pars;
            } filter_config_list[40];
        } can_filter_config;
    } config_info;    
} tsdev_ecat_can_filter_config_t;

typedef struct tsdev_ecat_config_rsp_s
{
    uint16_t config_type;   // tsdev_ecat_config_type_t
    uint16_t can_chn;
    uint32_t config_rsp;
} tsdev_ecat_config_rsp_t;

typedef tsdev_err_t (*tsdev_ecat_config_cmd_event_t)(tsdev_handle_t handle, void* usr_arg, tsdev_tsmsg_t msg,
    uint16_t fdid, uint16_t fsize, const tsdev_ecat_config_rsp_t* data);


#endif // __TSDEV_API_ECAT_CONFIG_TYPES_H