/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_PSI5_TYPES_H
#define __TSDEV_API_PSI5_TYPES_H
#include "tsdev_api_base_types.h"

typedef tsdev_err_t (*tsdev_psi5_cmd_event_t)(tsdev_handle_t handle, void *usr_arg, tsdev_tsmsg_t msg,
                                              uint16_t rev, uint16_t fsize, const struct tsdev_psi5if_ecu_ch_cmd_rsp_t *data);
typedef tsdev_err_t (*tsdev_psi5_frame_event_t)(tsdev_handle_t handle, void *usr_arg, tsdev_tsmsg_t msg,
                                                uint16_t rev, uint16_t fsize, const struct tsdev_psi5if_ecu_ch_frame_rx_t *data);

typedef enum
{
    tsdev_psi5_common_mode,   // 4.8V typical (common mode)
    tsdev_psi5_low_power_mode // 3.7V typical (low power mode)
} tsdev_psi5if_ecu_ch_vsync_t;

typedef enum
{
    tsdev_psi5_vbus_515, // internal 5.15V
    tsdev_psi5_vbus_665, // internal 6.65V
    tsdev_psi5_vbus_770  // internal 7.70V
} tsdev_psi5if_ecu_ch_vbus_t;

typedef enum
{
    tsdev_psi5_is_26, // current threshold for the data comparator (Is_CHx) 26mA
    tsdev_psi5_is_13  // current threshold for the data comparator (Is_CHx) 13mA
} tsdev_psi5if_ecu_ch_current_t;

typedef enum
{
    tsdev_psi5_sync, // channel in synchronous configuration
    tsdev_psi5_async // channel in asynchronous configuration
} tsdev_psi5if_ecu_ch_mode_t;

typedef enum
{
    tsdev_psi5_ch_125kbps, // bit time equal to 8us (=125kbps)
    tsdev_psi5_ch_189kbps  // bit time equal to 5.3us (=189kbps)
} tsdev_psi5if_ecu_ch_bps_t;

typedef enum
{
    tsdev_psi5_no_check, // disable check
    tsdev_psi5_parity,   // parity mode
    tsdev_psi5_crc       // CRC mode
} tsdev_psi5if_ecu_ch_check_mode_t;

typedef enum
{
    tsdev_psi5_short_sync, // short sync pulses
    tsdev_psi5_long_sync   // long  sync pulses
} tsdev_psi5if_ecu_ch_sync_t;

typedef enum
{
    tsdev_psi5_success,
    tsdev_psi5_error_with_out_of_range,
    tsdev_psi5_error_with_not_support
} tsdev_psi5if_ecu_ch_status_t;

struct tsdev_psi5if_ecu_slot_cfg_t
{
    uint8_t chk_type; // parameter check type , more details refer to enum tsdev_psi5if_ecu_ch_check_mode.
    uint8_t tsn_flen; // slot bit length , include (start bit + data + parity/crc)  0x01~0x17 [11...33].
    uint16_t tn_len;  // slot period length , TC4016 support the following values n*32  n is [0:15].
    uint8_t rev[4];
};

struct tsdev_psi5if_ecu_ch_slot_data_t
{
    uint32_t slot_data;
    uint8_t frame_id; // In synchronous mode, display data from which slot, and only loop count in asynchronous mode.
    uint8_t rev[1];
    /** error_status: */
    // bit0:    vbusover;                /* VBUS over voltage */
    // bit1:    overtemperatur;          /* over temperature */
    // bit2:    rxslotnexpect;           /* unexpected frame received */
    // bit3:    rxslotnoframe;           /* no frame received */
    // bit4:    rxslotframeerror;        /* frame error detected */
    // bit5:    rxperrerror;             /* parity/CRC error detected */
    // bit6:    revcur;                  /* reverse current detected*/
    // bit7:    reoc;                    /* over current */
    // bit8:    cherror;                 /* leakage to GND/VBAT , 1 leakage to GND, 2 leakage to VBAT */
    // bit9:    invalid_data
    // bit10 - 15: rev
    uint16_t error_status;
};

struct tsdev_psi5if_ecu_ch_config_t
{
    uint8_t mode;               // channel mode , more details refer to enum tsdev_psi5if_ecu_ch_mode.
    uint8_t vsync;              // channel sync sustain voltage , more details refer to enum tsdev_psi5if_ecu_ch_vsync.
    uint8_t vbus;               // VBUS selection , for TC4016, the voltage parameters of channels 0 to 3,4 to 7,8 to 11,12 to 15 on Vbus must be the same. If the configuration parameters are different, the last configuration will take precedence.
    uint8_t current;            // current threshold for the data comparator ( Is_CHx) ,  more details refer to enum tsdev_psi5if_ecu_ch_current.
    uint8_t bps;                // channel baud rate  ,  more details refer to enum tsdev_psi5if_ecu_ch_bps.
    uint8_t slot_number;        // number of slots per channel
    uint16_t sync_cycle_period; // channel sync loop generation period, 0~65535us (TC4016 support min 100 us).
    uint16_t sync_delay;        // channel sync delay generation time.
    uint8_t rev[6];
    struct tsdev_psi5if_ecu_slot_cfg_t slot_cfg[6]; // the parameters of the slot, unused slots are disabled by default.
};

struct tsdev_psi5if_ecu_ch_cmd_req_t
{
    uint8_t ch_idx; // TC4016 support 16 psi5 channel
    uint8_t psi5_per_handle;
    uint8_t ch_en;
    uint8_t rev[5];
    struct tsdev_psi5if_ecu_ch_config_t config;
};

struct tsdev_psi5if_ecu_ch_cmd_rsp_t
{
    uint8_t ch_idx; // TC4016 support 16 psi5 channel
    uint8_t cmd_rsp;
    uint8_t rev[6];
};

struct tsdev_psi5if_ecu_ch_frame_rx_t
{
    uint64_t timestamp; // time stamp, in microseconds
    uint8_t ch_idx;
    uint8_t data_type; // 0: Normal slot data, 1: Sync data sent, 2: Error state.
    uint8_t tx_info;
    uint8_t rev[5];
    struct tsdev_psi5if_ecu_ch_slot_data_t slot_data[6];
};

#endif // __TSDEV_API_PSI5_TYPES_H