/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_MNG_TYUPES_H
#define __TSDEV_API_MNG_TYUPES_H
#include "tsdev_api_base_types.h"

struct tsdev_apl_data_t {
	uint16_t length;
	uint8_t data[1024 - 2];//var add 2024-8-16
};

struct tsdevm_device_immutable_desc_t {
	uint16_t length;
	char data[1024 - 2];//var add 2024-8-16
};

struct tsdev_mutable_desc_t {
	uint16_t length;
	char data[2048 - 2];//var add 2024-8-16
};
struct framework_packet_r_t
{
	uint8_t type;//0 for hex framework
	uint8_t rev;
	uint16_t rev2;
	uint32_t rev4;
	uint64_t time_gen; //second since 1970-1-1
	uint64_t time_update; //set by pc software
};


#endif