/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __tsdev_TYPES_H
#define __tsdev_TYPES_H


#define FILE_VERSION_MAIN 0
#define FILE_VERSION_MID 1
#define FILE_VERSION_SUB 0
#define FILER_VERSION "0,0,0"

#include <stdint.h>
#ifdef __cplusplus
#include <cstddef>
#else
#include <stddef.h>
#endif
#include "tsdev_api_base_types.h"
#include "tsdev_api_eth_types.h"
#include "tsdev_api_can_types.h"
#include "tsdev_api_lin_types.h"
#include "tsdev_api_psi5_types.h"
#include "tsdev_api_sent_types.h"
#include "tsdev_api_flexray_types.h"
#include "tsdev_api_mng_types.h"
#include "tsdev_api_sim_types.h"
#include "tsdev_api_io_types.h"
#include "tsdev_api_logger_types.h"
#include "tsdev_api_dev_config_types.h"
#include "tsdev_api_mqtt_types.h"
#include "tsdev_api_ta1015_types.h"
#include "tsdev_api_ecat_config_types.h"
#include "tsdev_api_usrmodule_types.h"
#include "tsdev_api_ethercat_types.h"

typedef void(*tsdev_log_out_callback_t)(tsdev_handle_t handle, void* usr_arg, tsdev_log_lvl_t lvl, const char* msg);
struct tsdev_rt_par_t {
	uint16_t usr_write_depth; //use 0 for default value
	uint16_t usr_read_depth; //use 0 for default value
	uint8_t usr_write_burst; //0: no limit, 1-255 * 4096
	uint8_t usr_read_burst; //0: no limit, 1-255 * 4096
	//bit0: disable usr space write
	//bit1: disable usr space read
	uint8_t config0;
	uint8_t rev[3+32];
};
struct tsdev_context_t_local_rt_callbacks {
	void* usr_arg;
	void (*callback)(tsdev_handle_t handle, void* usr_arg, int idx);
	uint64_t affinity_mask;
	uint8_t is_busy_th;
	uint8_t rev[7];
};
struct tsdev_context_t
{
    /** enum tsdev_devtype_t */
    uint16_t dev_type;
    /** enum tsdev_com_t */
    uint8_t com;
    /* tsdev_log_lvl_t */
    uint8_t min_print_lvl;
    uint8_t rev[4];
    union
    {
		uint8_t rev[1024];
		struct tdev_none_t
		{
			uint8_t rev[8];
		} none;
		struct tdev_netif_t
		{
			//uint8_t scan_vm_eth : 1;
			// uint8_t scan_wireless_eth : 1;
			uint8_t config0;//bit 0: con_by_udp
			uint8_t rev[3 + 4];
			char netif_name[256 - 8]; // NULL string mean scan default
			uint64_t affinity_mask;
		} eth;
		struct tdev_tcp_t
		{
			uint8_t target_addr[4 * 4]; //ipv6 is not support now
			uint16_t target_port;
			uint16_t rev;
			uint8_t rev1[4];
			uint64_t affinity_mask;
		} tcp;
		struct tsdev_can_t {
			uint8_t config0; //bit0: is_fd
			uint8_t rev[3 + 4];
			//todo: tx fun
			//todo: read rx_fun
		} canfd;
		struct tsdev_usb_t {
			//bit0: 0-hid; 1-winusb
			//bit1: 0-do not support legcy usb device, 1. support legcy usb device, this opt used for windows only
			//bit2: 0-do not support socketcan device, 1. support socketcan device, this opt used for windows only
			uint16_t config0;
			uint16_t rev[1 + 2];
			uint64_t affinity_mask;
		} usb;
		struct tsdev_serial_t {
			uint16_t baudrate;//todo
			uint16_t num;
			uint16_t rev[2];
		} serial;

		struct tsdev_local_rt_t {
			uint8_t core_used;
			uint8_t prio;  //10-254
			uint8_t is_usr_mode;
			uint8_t callback_cnt; //0-47
			uint32_t cycle_us_default; //can not less than 50
			uint32_t sim_start_delay_us; //can not less than 100000
			uint32_t share_ram_size;
			const struct tsdev_context_t_local_rt_callbacks* callbacks;
		} local_rt;
        struct tsdev_pcie_rt_t {
            int8_t venId[8];
            int8_t devId[8];
            uint8_t is_usr_mode;
            uint8_t rev[7];
		} pcie_rt;
		struct tsdev_tcp_rt_t {
			//all rt device have rt_par as default
			struct tsdev_rt_par_t rt_par;
			tsdev_handle_t local_rt;
			uint8_t core_offset;
			uint8_t rev0;
			uint16_t rev;
			uint32_t rev1;

			char netif_name[128];
			uint8_t local_ip[4];
			uint8_t local_gw[4];
			uint8_t local_mask[4];
			uint8_t target_addr[4];
			uint16_t target_port;

		} tcp_rt;
		struct tsdev_usb_rt_t {
			//all rt device have rt_par as default
			struct tsdev_rt_par_t rt_par;
			tsdev_handle_t local_rt;
			uint16_t core_offset;

			uint16_t config0;//bit0: 0-hid; 1-winusb
			char usb_controler[128];
		} usb_rt;
		struct tsdev_ethercat_t {
			struct tsdev_rt_par_t rt_par;
			tsdev_handle_t local_rt;
			uint8_t core_offset;
			//bit0: enable xml info output
			//bit1: force upload from eeprom
            //bit2: 0 - rx pipe abondon new msg(safe); 1 - rx pipe abondon old msg(Low probability of abnormal consistency in reading data)
			uint8_t config;
			uint16_t rev;
			uint32_t rev1;
			//The parameter libraryPath should lead to one or more folders which are containing XML files with ecatT slave information (ESI)
			// . Multiple paths can be specified when separated by semicolons.
			const char* xml_path;
			char netif_name[128];
			char netif_redundancy_name[128];

		} ethercat_rt;
    }com_par;

    struct tsdev_rpc_host_t
    {
        uint8_t max_client_cnt;
        uint8_t rev;
        //uint8_t rpc_sec_type;//0-usr_name:key, 1-by cert, 0xff-no sec is need
        uint16_t host_tcp_port;
        uint8_t rev4[4];
        uint8_t host_uid[tsdev_UID_LEN];
    }rpc;

    void* usr_arg;

	tsdev_log_out_callback_t log_callback;
};

struct tsdev_host_usr_in_params_t
{
    uint16_t version;
    uint8_t rev[2 + 4];
    union tsdev_host_usr_in_params_def_t
    {
        uint8_t rev[128 - 8];
        struct tsdev_host_usr_in_params_v0_t
        {
            uint32_t fifo_depth; //default is 50
        }v0;
    }defs;
};


 //--------------------------------------------------------------for device manage----------------------------------------------------
#define DEV_WITH_START (0X8000)
enum tsdev_devtype_t {
    tsdev_devtype_all = 0,
    tsdev_devtype_host = 1,
	tsdev_devtype_usb_legacy = 2,
	tsdev_devtype_ethercat_rt = 3,
	tsdev_devtype_usb_legacy_tc1001 = 10,
	tsdev_devtype_usb_legacy_tc1011 = 11,
	tsdev_devtype_usb_legacy_tc1012 = 12,
	tsdev_devtype_usb_legacy_tc1013 = 13,
	tsdev_devtype_usb_legacy_tc1014 = 14,
	tsdev_devtype_usb_legacy_tc1016 = 15,
	tsdev_devtype_usb_legacy_tc1017 = 16,
	tsdev_devtype_usb_legacy_tc1018 = 17,
	tsdev_devtype_usb_legacy_tc1026 = 18,
	tsdev_devtype_usb_legacy_tc1034 = 19,
	tsdev_devtype_usb_legacy_tc1113 = 20,
	tsdev_devtype_usb_legacy_tc1114 = 21,
	tsdev_devtype_usb_legacy_tl1001 = 22,
	tsdev_devtype_usb_legacy_tl1011 = 23,
	tsdev_devtype_usb_legacy_tlog1002 = 24,
	tsdev_devtype_usb_legacy_tlog1004 = 25,
	tsdev_devtype_usb_legacy_to1013 = 26,
	tsdev_devtype_usb_legacy_tp1013 = 27,
	tsdev_devtype_usb_legacy_tp1018 = 28,
	tsdev_devtype_usb_legacy_tp1026 = 29,
	tsdev_devtype_usb_legacy_tp1034 = 30,
	tsdev_devtype_usb_legacy_tts1016pro = 31,
	tsdev_devtype_usb_legacy_tts1018 = 32,
	tsdev_devtype_usb_legacy_tts1026 = 33,
	tsdev_devtype_usb_legacy_tts1034 = 34,
	tsdev_devtype_tc111 = 35,
	tsdev_devtype_tc113 = 36,
	tsdev_devtype_tc114 = 37,
	tsdev_devtype_tc3014 = 38,
    // old device type idx
    tsdev_devtype_tlog1038 = DEV_WITH_START,
    tsdev_devtype_th7011 = DEV_WITH_START + 1,
    tsdev_devtype_tc1054 = DEV_WITH_START + 2,
    tsdev_devtype_tc1054pro = DEV_WITH_START + 3,
    tsdev_devtype_tc1038pro = DEV_WITH_START + 4,
    tsdev_devtype_ta1038 = DEV_WITH_START + 5,
    tsdev_devtype_tc4016 = DEV_WITH_START + 6,
    tsdev_devtype_tc1055pro = DEV_WITH_START + 7,
    tsdev_devtype_tc1056pro = DEV_WITH_START + 8,
    tsdev_devtype_tc1057pro = DEV_WITH_START + 9,
    tsdev_devtype_th7012 = DEV_WITH_START + 10,
    tsdev_devtype_tx1000 = DEV_WITH_START + 11,
    tsdev_devtype_gw2208 = DEV_WITH_START + 12,
    tsdev_devtype_tlog1039 = DEV_WITH_START + 13,
    tsdev_devtype_gw1040 = DEV_WITH_START + 14,
    tsdev_devtype_XXX0 = DEV_WITH_START + 15,
    tsdev_devtype_tc1016p_cache = DEV_WITH_START + 16,
    tsdev_devtype_tre048 = DEV_WITH_START + 17,
    tsdev_devtype_ta1101 = DEV_WITH_START + 18,
    tsdev_devtype_gw2204 = DEV_WITH_START + 19,
    tsdev_devtype_gw2202 = DEV_WITH_START + 20,
    tsdev_devtype_gw2212 = DEV_WITH_START + 21,
    tsdev_devtype_tc1052 = DEV_WITH_START + 22,
    tsdev_devtype_XXX = DEV_WITH_START + 23,
    tsdev_devtype_XX1 = DEV_WITH_START + 24,
    tsdev_devtype_XXX2 = DEV_WITH_START + 25,
    tsdev_devtype_tts8027 = DEV_WITH_START + 26,
    tsdev_devtype_tts8036 = DEV_WITH_START + 27,
    tsdev_devtype_tts1017pro_c = DEV_WITH_START + 28,
    tsdev_devtype_ta821 = DEV_WITH_START + 29,
    tsdev_devtype_tlog1057 = DEV_WITH_START + 30,
    tsdev_devtype_tts8848 = DEV_WITH_START + 31,
    tsdev_devtype_tts8031 = DEV_WITH_START + 32,
    tsdev_devtype_tts8517 = DEV_WITH_START + 33,
    tsdev_devtype_ta422 = DEV_WITH_START + 34,
    tsdev_devtype_tts8018 = DEV_WITH_START + 35,
    tsdev_devtype_tc1055pro_plus = DEV_WITH_START + 36,
}; // uint16_t

#endif
