/**
 * Copyright (c) 2025:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_ECAT_H
#define __TSDEV_API_ECAT_H
#include "tsdev_types.h"

#ifdef __cplusplus
extern "C"
{
#endif

TSDEV_API tsdev_api_ecat_open(tsdev_handle_t handle, uint8_t eth_idx, uint32_t timeout_ms);
TSDEV_API tsdev_api_ecat_close(tsdev_handle_t handle, uint8_t eth_idx);

TSDEV_API tsdev_api_ecat_master_status_read_sync(tsdev_handle_t handle, uint8_t eth_idx, struct tsdev_ecat_master_status_t* status, uint32_t timeout_ms);

TSDEV_API tsdev_api_ecat_slave_status_read_sync(tsdev_handle_t handle, uint8_t eth_idx, uint16_t slave_idx, struct tsdev_ecat_slave_status_t* status, uint32_t timeout_ms);
/*status ref to tsdev_ecat_status*/
TSDEV_API tsdev_api_ecat_slave_state_change_sync(tsdev_handle_t handle, uint8_t eth_idx, uint16_t slave_idx, uint8_t status, uint32_t timeout_ms);
TSDEV_API tsdev_api_ecat_slave_info_read_sync(tsdev_handle_t handle, uint8_t eth_idx, uint16_t slave_idx, struct tsdev_ecat_slave_info_t* info, uint32_t timeout_ms);
TSDEV_API tsdev_api_ecat_slave_obj_read_sync(tsdev_handle_t handle, uint8_t eth_idx, uint16_t slave_idx, uint16_t obj_idx, struct tsdev_ecat_dataobj_info_t* info, uint32_t timeout_ms);
TSDEV_API tsdev_api_ecat_slave_var_read_sync(tsdev_handle_t handle, uint8_t eth_idx, uint16_t slave_idx, uint16_t obj_idx, uint16_t var_idx, struct tsdev_ecat_datavar_info_t* info, uint32_t timeout_ms);
//dc is not support now
TSDEV_API tsdev_api_ecat_slave_dc_info_read_sync(tsdev_handle_t handle, uint8_t eth_idx, uint16_t slave_idx, uint16_t dc_idx, struct tsdev_ecat_slave_dc_info_t* info, uint32_t timeout_ms);
TSDEV_API tsdev_api_ecat_slave_dc_par_read_sync(tsdev_handle_t handle, uint8_t eth_idx, uint16_t slave_idx, uint16_t dc_idx, struct tsdev_ecat_slave_dc_par_t* par, uint32_t timeout_ms);
TSDEV_API tsdev_api_ecat_slave_dc_par_write_sync(tsdev_handle_t handle, uint8_t eth_idx, uint16_t slave_idx, uint16_t dc_idx, const struct tsdev_ecat_slave_dc_par_t* par, uint32_t timeout_ms);


TSDEV_API tsdev_api_ecat_create_dataset_sync(tsdev_handle_t handle, uint8_t eth_idx, uint16_t* dataset_idx, uint8_t disable_read, uint8_t disable_idle_tx, uint16_t cycle_rep, uint16_t cycle_offset, uint16_t cycle_inhibit, uint32_t timeout_ms);
//sm_idx: >=0 real sm idx, -1 sm all, -2 sm input, -3 sm output
//location: 0	Right after the last assigned.  <0	Relative offset after the last assigned.  >0	Absolute offset.
TSDEV_API tsdev_api_ecat_assign_dataset_sync(tsdev_handle_t handle, uint8_t eth_idx, uint16_t dataset_idx, uint16_t slave_idx, int32_t sm_idx, uint32_t location, uint32_t timeout_ms);
TSDEV_API tsdev_api_ecat_start_dataset_sync(tsdev_handle_t handle, uint8_t eth_idx, uint16_t dataset_idx);
TSDEV_API tsdev_api_ecat_stop_dataset_sync(tsdev_handle_t handle, uint8_t eth_idx, uint16_t dataset_idx);
TSDEV_API tsdev_api_ecat_dataset_map_get_sync(tsdev_handle_t handle, uint8_t eth_idx, uint16_t dataset_idx, uint32_t* len, uint16_t* var_cnt
	, const struct tsdev_ecat_dataset_map_per_t** dataset_map_pp, uint32_t timeout_ms);
//ecat signal operate
TSDEV_API tsdev_api_ecat_dataset_var_update(tsdev_handle_t handle, uint8_t eth_idx, uint16_t dataset_idx, uint16_t var_idx, const uint8_t* var_p);
TSDEV_API tsdev_api_ecat_dataset_var_update_fast(tsdev_handle_t handle, uint8_t eth_idx, uint16_t dataset_idx, uint16_t var_idx, const uint8_t* var_p);
TSDEV_API tsdev_api_ecat_dataset_var_get(tsdev_handle_t handle, uint8_t eth_idx, uint16_t dataset_idx, uint16_t var_idx, uint8_t* var_p);
TSDEV_API tsdev_api_ecat_dataset_var_get_fast(tsdev_handle_t handle, uint8_t eth_idx, uint16_t dataset_idx, uint16_t var_idx, uint8_t* var_p);
TSDEV_API tsdev_api_ecat_dataset_get_last_read_time_us(tsdev_handle_t handle, uint8_t eth_idx, uint16_t dataset_idx, uint64_t* time_us_p);
TSDEV_API tsdev_api_ecat_dataset_post_async(tsdev_handle_t handle, uint8_t eth_idx, uint16_t dataset_idx);
//ecat packet operate
TSDEV_API tsdev_api_ecat_dataset_tx_buff_ptr_get(tsdev_handle_t handle, uint8_t eth_idx, uint16_t dataset_idx, uint8_t** buff_pp);
TSDEV_API tsdev_api_ecat_dataset_rx_buff_ptr_get(tsdev_handle_t handle, uint8_t eth_idx, uint16_t dataset_idx, const uint8_t** buff_pp);
//ignore_history: read last packet, each dataset have 128(abondon new)/125(abondon old) packet buff
TSDEV_API tsdev_api_ecat_dataset_rx_packet_clear(tsdev_handle_t handle, uint8_t eth_idx, uint16_t dataset_idx);
TSDEV_API tsdev_api_ecat_dataset_rx_packet_get(tsdev_handle_t handle, uint8_t eth_idx, uint16_t dataset_idx, uint64_t* time_us_p
	, uint8_t* buff_p, uint8_t ignore_history);

TSDEV_API tsdev_api_ecat_slave_dataobj_write_sync(tsdev_handle_t handle, uint8_t eth_idx, uint8_t slave_idx, uint16_t obj_index, uint16_t var_idx
	, const uint8_t* var_p, uint16_t size, uint32_t timeout_ms);
TSDEV_API tsdev_api_ecat_slave_dataobj_read_sync(tsdev_handle_t handle, uint8_t eth_idx, uint8_t slave_idx, uint16_t obj_index, uint16_t var_idx
	, uint8_t* pData, uint16_t* pSize, uint32_t timeout_ms);

TSDEV_API tsdev_api_ecat_slave_mem_write_sync(tsdev_handle_t handle, uint8_t eth_idx, uint8_t slave_idx, uint16_t address
	, const uint8_t* pData, uint16_t size, uint32_t timeout_ms);
TSDEV_API tsdev_api_ecat_slave_mem_read_sync(tsdev_handle_t handle, uint8_t eth_idx, uint8_t slave_idx, uint16_t address
	, uint8_t* pData, uint16_t size, uint32_t timeout_ms);

#ifdef __cplusplus
}
#endif

#endif
