/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_CAN_TYPES_H
#define __TSDEV_API_CAN_TYPES_H
#include "tsdev_api_base_types.h"

typedef tsdev_err_t(*tsdev_can_cmd_event_t)(tsdev_handle_t handle, void* usr_arg, tsdev_tsmsg_t msg,
	uint16_t rev, uint16_t fsize, const struct tsdev_THW_GetHWFDConf* data);
typedef tsdev_err_t(*tsdev_can_frame_event_t)(tsdev_handle_t handle, void* usr_arg, tsdev_tsmsg_t msg,
	uint16_t rev, uint16_t fsize, const struct tsdev_canfd_rx_t* data);



//--------------------------------------------------------------for CAN bus----------------------------------------------------
struct tsdev_TPC_FDHardwareConf
{
	uint8_t FAutoReportGrp;         // 1:default = 0xFF, masked status see THW_GetHWConf
	uint8_t FStoreInNVM;            // STORE_IN_NVM, RESET_CHANNEL_MASK Etc
	//TCANFDCoreConf FCANFDConf; // 14:fd core configuration
	uint8_t FIdx;              //     can fd channel index, 0xFF = no set
	uint8_t FChannelTypeIdx;   //     channel type index
	uint8_t FPrescalerArb;     //     can clock prescaler
	uint8_t FBTR0Arb;          //     can btr0 register
	uint8_t FBTR1Arb;          //     can btr1 register
	uint8_t FSJWArb;           //     can sync. jump width
	uint8_t FPrescalerData;    //     can clock prescaler
	uint8_t FBTR0Data;         //     can btr0 register
	uint8_t FBTR1Data;         //     can btr1 register
	uint8_t FSJWData;          //     can sync. jump width
	uint8_t F120OhmRes;        //     0: do not install; 1: install
	uint8_t FControllerType;   //     0: Classic CAN; 1: ISO CAN; 2: Non-ISO CAN; 3: CANXL
	uint8_t FControllerMode;   //     0: Normal; 1: No ACK; 2: restricted; 3: internal loop-back mode; 4: external loop-back mode; 5: noraml-with self ack
	uint8_t config; //    bit0: FAutoRecoverOnErr 0: do not recover; 1: auto recover
	//BIT1: switch between 40MHz and 80MHz mode, 0 for 40MHz, 1 for 80MHz //reserve  xl 160M
	//bit6: err signaling, 0 for off, 1 for on;
	//bit7: enable xl fast mode, 0 for normal mode, 1 for xl fast mode;
	uint8_t FPrescalerData_XL;    //     can clock prescaler
	uint8_t FBTR0Data_XL;         //     can btr0 register
	uint8_t FBTR1Data_XL;         //     can btr1 register
	uint8_t FSJWData_XL;          //     can sync. jump width
};
struct tsdev_THW_GetHWFDConf
{
	uint64_t FTimestamp;       // hw local timestamp when this command is issued
	uint8_t FAutoReportGrp;    // default = 0xFF, masked status:
	// [7-4] tbd
	// [3] report io samples periodically, the period can be set by TPC_GetIO
	// [2] report lin events
	// [1] report can events
	// [0] report system status
	uint8_t FReserved;          // reserved to keep align

	uint8_t FIdx;              //     can fd channel index, 0xFF = no set
	uint8_t FChannelTypeIdx;   //     channel type index
	uint8_t FPrescalerArb;     //     can clock prescaler
	uint8_t FBTR0Arb;          //     can btr0 register
	uint8_t FBTR1Arb;          //     can btr1 register
	uint8_t FSJWArb;           //     can sync. jump width
	uint8_t FPrescalerData;    //     can clock prescaler
	uint8_t FBTR0Data;         //     can btr0 register
	uint8_t FBTR1Data;         //     can btr1 register
	uint8_t FSJWData;          //     can sync. jump width
	uint8_t F120OhmRes;        //     0: do not install; 1: install
	uint8_t FControllerType;   //     0: Classic CAN; 1: ISO CAN; 2: Non-ISO CAN
	uint8_t FControllerMode;   //     0: Normal; 1: No ACK; 2: restricted
	uint8_t config; //    bit0: FAutoRecoverOnErr 0: do not recover; 1: auto recover
	//BIT1: switch between 40MHz and 80MHz mode, 0 for 40MHz, 1 for 80MHz
	//bit6: err signaling, 0 for off, 1 for on;
	//bit7: enable xl fast mode, 0 for normal mode, 1 for xl fast mode;
	uint8_t FPrescalerData_XL;    //     can clock prescaler
	uint8_t FBTR0Data_XL;         //     can btr0 register
	uint8_t FBTR1Data_XL;         //     can btr1 register
	uint8_t FSJWData_XL;          //     can sync. jump width
};
struct tsdev_canfd_tx_t  //_TPC_TXCANFD_LVL0
{
	uint32_t FIdentifier;       // CAN identifier
	uint8_t FIdxChn;            // channel index starting from 0
	//uint8_t FReserved;         // hw buffer index assigned when being transmitted, not used by PC
	uint8_t FCtrlGrp;           // default 0, masked status:
	// [7] 0-normal frame, 1-error frame
	// [6] LOGGED
	// [5] Cached J1939
	// [4] tbd
	// [3] 0-non xl frame, 1-xl frame;
	// [2] 0-std frame, 1-extended frame
	// [1] 0-data frame, 1-remote frame
	// [0] dir: 0-RX, 1-TX
	uint8_t FFDProperties;      // [7-5] tbd                            <> CAN
	// [3-4] tx frame qos, 00: fifo; 01: cycle; 10; tbd; 11: fast cycle
	// [2] ESI, The ERROR STATE INDICATOR (ESI) flag is transmitted dominant by error active nodes, recessive by error passive nodes. ESI does not exist in CAN format frames
	// [1] BRS, If the bit is transmitted recessive, the bit rate is switched from the standard bit rate of the A RBITRATION P HASE to the preconfigured alternate bit rate of the D ATA P HASE . If it is transmitted dominant, the bit rate is not switched. BRS does not exist in CAN format frames.
	// [0] EDL: 0-normal CAN frame, 1-FD frame, added 2020-02-12, The EXTENDED DATA LENGTH (EDL) bit is recessive. It only exists in CAN FD format frames
	uint8_t FDLC;               // dlc from 0 to 64
	uint8_t FData[64];          // 64 data bytes to send
};
struct tsdev_canfd_tx_xl_t  //_TPC_TXCANFD_LVL0
{
	uint32_t FIdentifier;       // CAN identifier
	uint8_t FIdxChn;            // channel index starting from 0
	//uint8_t FReserved;         // hw buffer index assigned when being transmitted, not used by PC
	uint8_t FCtrlGrp;           // default 0, masked status:
	// [7] 0-normal frame, 1-error frame
	// [6] LOGGED
	// [5] Cached J1939
	// [4] tbd
	// [3] 0-non xl frame, 1-xl frame;
	// [2] 0-std frame, 1-extended frame
	// [1] 0-data frame, 1-remote frame
	// [0] dir: 0-RX, 1-TX
	uint8_t FFDProperties;      // [7-5] tbd                            <> CAN
	// [3-4] tx frame qos, 00: fifo; 01: cycle; 10; tbd; 11: fast cycle
	// [2] ESI, The ERROR STATE INDICATOR (ESI) flag is transmitted dominant by error active nodes, recessive by error passive nodes. ESI does not exist in CAN format frames
	// [1] BRS, If the bit is transmitted recessive, the bit rate is switched from the standard bit rate of the A RBITRATION P HASE to the preconfigured alternate bit rate of the D ATA P HASE . If it is transmitted dominant, the bit rate is not switched. BRS does not exist in CAN format frames.
	// [0] EDL: 0-normal CAN frame, 1-FD frame, added 2020-02-12, The EXTENDED DATA LENGTH (EDL) bit is recessive. It only exists in CAN FD format frames
	uint8_t VCID;
	uint16_t FDLC;
	uint8_t SDT;
	uint8_t Ctrl_0;
	//bit2: SEC;   
	uint32_t AF;
	uint8_t FData[2048];          // data bytes to send
};
struct tsdev_canfd_rx_t
{
	uint64_t FTimestamp;       // hw local timestamp when this command is issued
	uint32_t FIdentifier;      // 0x55, can identifier
	uint8_t FIdxChn;           // 0, 0-channel 1, 1-channel 2
	uint8_t FDLC;              // 8, range from 0 to 15
	uint8_t FStatusGrp;  // 0, masked status:
	// [7] 0-normal frame, 1-error frame
	// [6] LOGGED
	// [5] Cached J1939
	// [4] tbd
	// [3] 0-non xl frame, 1-xl frame;
	// [2] 0-std frame, 1-extended frame
	// [1] 0-data frame, 1-remote frame
	// [0] dir: 0-RX, 1-TX
	uint8_t FFDProperties;      // [7-5] tbd                            <> CAN
	// [3-4] tx frame qos, 00: fifo; 01: cycle; 10; tbd; 11: fast cycle
	// [2] ESI, The E RROR S TATE I NDICATOR (ESI) flag is transmitted dominant by error active nodes, recessive by error passive nodes. ESI does not exist in CAN format frames
	// [1] BRS, If the bit is transitted recessive, the bit rate is switched from the standard bit rate of the A RBITRATION P HASE to the preconfigured alternate bit rate of the D ATA P HASE . If it is transmitted dominant, the bit rate is not switched. BRS does not exist in CAN format frames.
	// [0] EDL: 0-normal CAN frame, 1-FD frame, added 2020-02-12, The E XTENDED D ATA L ENGTH (EDL) bit is recessive. It only exists in CAN FD format frames
	uint8_t FData[64];          // 64 bytes array
	//if FStatusGrp bit7 is error then only FData[0] is used for error code
	//include ERROR_GENERIC  ERROR_STUFF ERROR_FORM ERROR_ACK ERROR_BIT_RECESSIVE  ERROR_BIT_DOMINAT ERROR_CRC
};

struct tsdev_canfd_rx_xl_t
{
	uint64_t FTimestamp;       // hw local timestamp when this command is issued
	uint32_t FIdentifier;      // 0x55, can identifier
	uint8_t FIdxChn;           // 0, 0-channel 1, 1-channel 2
	uint8_t VCID;//only for xl mode
	uint8_t FStatusGrp;  // 0, masked status:
	// [7] 0-normal frame, 1-error frame
	// [6] LOGGED
	// [5] Cached J1939
	// [4] tbd
	// [3] 0-non xl frame, 1-xl frame;
	// [2] 0-std frame, 1-extended frame
	// [1] 0-data frame, 1-remote frame
	// [0] dir: 0-RX, 1-TX
	uint8_t FFDProperties;      // [7-5] tbd                            <> CAN
	// [3-4] tx frame qos, 00: fifo; 01: cycle; 10; tbd; 11: fast cycle
	// [2] ESI, The E RROR S TATE I NDICATOR (ESI) flag is transmitted dominant by error active nodes, recessive by error passive nodes. ESI does not exist in CAN format frames
	// [1] BRS, If the bit is transmitted recessive, the bit rate is switched from the standard bit rate of the A RBITRATION P HASE to the preconfigured alternate bit rate of the D ATA P HASE . If it is transmitted dominant, the bit rate is not switched. BRS does not exist in CAN format frames.
	// [0] EDL: 0-normal CAN frame, 1-FD frame, added 2020-02-12, The E XTENDED D ATA L ENGTH (EDL) bit is recessive. It only exists in CAN FD format frames
	uint16_t FDLC;
	uint8_t SDT;
	uint8_t Ctrl_0; 
	//bit1: FAST;
	//bit2: SEC;   
	//bit4-7: ADS;
	uint32_t AF;
	uint8_t Data[2048];     
};

struct tsdev_canfd_rx_v1_err_can_t
{
	uint64_t FTimestamp;       // hw local timestamp when this command is issued
	uint32_t FIdentifier;      // 0x55, can identifier
	uint8_t FIdxChn;           // 0, 0-channel 1, 1-channel 2
	uint8_t FDLC;              // 8, range from 0 to 8
	uint8_t FStatusGrp;  // 0, masked status:
	// [7] 0-normal frame, 1-error frame
	// [6] LOGGED
	// [5] Cached J1939
	// [4] tbd
	// [3] 0-non xl frame, 1-xl frame;
	// [2] 0-std frame, 1-extended frame
	// [1] 0-data frame, 1-remote frame
	// [0] dir: 0-RX, 1-TX
	uint8_t FFDProperties;      // [7-5] tbd                            <> CAN
	// [3-4] tx frame qos, 00: fifo; 01: cycle; 10; tbd; 11: fast cycle
	// [2] ESI, The E RROR S TATE I NDICATOR (ESI) flag is transmitted dominant by error active nodes, recessive by error passive nodes. ESI does not exist in CAN format frames
	// [1] BRS, If the bit is transmitted recessive, the bit rate is switched from the standard bit rate of the A RBITRATION P HASE to the preconfigured alternate bit rate of the D ATA P HASE . If it is transmitted dominant, the bit rate is not switched. BRS does not exist in CAN format frames.
	// [0] EDL: 0-normal CAN frame, 1-FD frame, added 2020-02-12, The E XTENDED D ATA L ENGTH (EDL) bit is recessive. It only exists in CAN FD format frames

	uint32_t property;
	//0-dir: 0-rx, 1-tx;
	//1-typ: 0-dom to rev, 1-rev to dom; 
	//[2:3]-err: 0-ok, 1-err, 2-overload;
	//[4:6]-err cnt0
	//[7:17]-err cnt1
	//[18:20]-err field: 0-arb, 1-ctrl, 2-data, 3-crc, 4-ack, 5-eof
	//[21:23]-err type: 0-bit err, 1-crc err, 2-ack err, 3-form err, 4-stuff err

	uint32_t ext_info;
	//bit0: SRR;
	//bit1: R0;
	//bit2: R1;
	//bit3-17: CRC;        
	//bit18: CRC_DEL;         
	//bit19: ACK;  
	//bit20: ACK_DEL;  
	//bit21-27: EOF;
	//bit28-31: rev;
	uint8_t Data[8];     
};
struct tsdev_canfd_rx_v1_err_canfd_t
{
	uint64_t FTimestamp;       // hw local timestamp when this command is issued
	uint32_t FIdentifier;      // 0x55, can identifier
	uint8_t FIdxChn;           // 0, 0-channel 1, 1-channel 2
	uint8_t FDLC;              // 8, range from 0 to 8
	uint8_t FStatusGrp;  // 0, masked status:
	// [7] 0-normal frame, 1-error frame
	// [6] LOGGED
	// [5] Cached J1939
	// [4] tbd
	// [3] 0-non xl frame, 1-xl frame;
	// [2] 0-std frame, 1-extended frame
	// [1] 0-data frame, 1-remote frame
	// [0] dir: 0-RX, 1-TX
	uint8_t FFDProperties;      // [7-5] tbd                            <> CAN
	// [3-4] tx frame qos, 00: fifo; 01: cycle; 10; tbd; 11: fast cycle
	// [2] ESI, The E RROR S TATE I NDICATOR (ESI) flag is transmitted dominant by error active nodes, recessive by error passive nodes. ESI does not exist in CAN format frames
	// [1] BRS, If the bit is transmitted recessive, the bit rate is switched from the standard bit rate of the A RBITRATION P HASE to the preconfigured alternate bit rate of the D ATA P HASE . If it is transmitted dominant, the bit rate is not switched. BRS does not exist in CAN format frames.
	// [0] EDL: 0-normal CAN frame, 1-FD frame, added 2020-02-12, The E XTENDED D ATA L ENGTH (EDL) bit is recessive. It only exists in CAN FD format frames

	uint32_t property;
	//0-dir: 0-rx, 1-tx;
	//1-typ: 0-dom to rev, 1-rev to dom; 
	//[2:3]-err: 0-ok, 1-err, 2-overload;
	//[4:6]-err cnt0
	//[7:17]-err cnt1
	//[18:20]-err field: 0-arb, 1-ctrl, 2-data, 3-crc, 4-ack, 5-eof
	//[21:23]-err type: 0-bit err, 1-crc err, 2-ack err, 3-form err, 4-stuff err

	struct tsdev_canfd_rx_v1_err_canfd_ext_t{
		uint32_t Field0;
		//bit0: SRR;
		//bit1: RRS;
		//bit2: RES;
		//bit3: ESI;
		//bit4-7: SBC;
		//bit8-28: CRC;        
		//bit29: CRC_DEL;         
		//bit30: ACK;  
		//bit31: ACK_DEL;  
		
		uint32_t Field1;
		//bit0-6: EOF;
		//bit7-31: rev;
	} ext_info;
	uint8_t Data[64];     
};
struct tsdev_canfd_rx_v1_err_canxl_t
{
	uint64_t FTimestamp;       // hw local timestamp when this command is issued
	uint32_t FIdentifier;      // 0x55, can identifier
	uint8_t FIdxChn;           // 0, 0-channel 1, 1-channel 2
	uint8_t VCID;//only for xl mode
	uint8_t FStatusGrp;  // 0, masked status:
	// [7] 0-normal frame, 1-error frame
	// [6] LOGGED
	// [5] Cached J1939
	// [4] tbd
	// [3] 0-non xl frame, 1-xl frame;
	// [2] 0-std frame, 1-extended frame
	// [1] 0-data frame, 1-remote frame
	// [0] dir: 0-RX, 1-TX
	uint8_t FFDProperties;      // [7-5] tbd                            <> CAN
	// [3-4] tx frame qos, 00: fifo; 01: cycle; 10; tbd; 11: fast cycle
	// [2] ESI, The E RROR S TATE I NDICATOR (ESI) flag is transmitted dominant by error active nodes, recessive by error passive nodes. ESI does not exist in CAN format frames
	// [1] BRS, If the bit is transmitted recessive, the bit rate is switched from the standard bit rate of the A RBITRATION P HASE to the preconfigured alternate bit rate of the D ATA P HASE . If it is transmitted dominant, the bit rate is not switched. BRS does not exist in CAN format frames.
	// [0] EDL: 0-normal CAN frame, 1-FD frame, added 2020-02-12, The E XTENDED D ATA L ENGTH (EDL) bit is recessive. It only exists in CAN FD format frames

	uint16_t FDLC;
	uint8_t SDT;
	uint8_t Ctrl_0; 
	//bit1: FAST;
	//bit2: SEC;   
	//bit4-7: ADS;
	uint32_t AF;

	uint32_t property;
	//0-dir: 0-rx, 1-tx;
	//1-typ: 0-dom to rev, 1-rev to dom; 
	//[2:3]-err: 0-ok, 1-err, 2-overload;
	//[4:6]-err cnt0
	//[7:17]-err cnt1
	//[18:20]-err field: 0-arb, 1-ctrl, 2-data, 3-crc, 4-ack, 5-eof
	//[21:23]-err type: 0-bit err, 1-crc err, 2-ack err, 3-form err, 4-stuff err
	
	struct tsdev_canxl_done_frm_ext_t{
		uint32_t Field0;
		//bit0: RRS;
		//bit1: IDE;
		//bit2: FDF;
		//bit3: XLF;
		//bit4: resXL;
		//bit5-7: SBC;        
		//bit8-20: PCRC;         
		//bit21-24: FCP;  
		//bit25-28: DAS; 
		//bit29: ACK; 
		//bit30: ACK_DEL;
		//bit31: rev;
		
		uint32_t Field1;
		//bit0-31: FCRC
				  
		uint32_t Field2;  
		//bit0-6: EOF;
		//bit7-31: rev;
	} ext_info;
	uint8_t Data[2048];     
};

struct tsdev_TPC_CANFD_Stream_Gen_Cfg
{
	//Frm
	struct tsdev_canfd_tx_t frm_info;

	//when TX: is stream frame, Stream cfg
	struct Stream_Gen_Ctrl {
		uint16_t ctrl;
		// [15] 0-stop, 1-start
		// [14] 0-once, 1-loop
		// [13-12] rev
		// [6-11] inc_len;//0-63
		// [0-5] inc_pos;//0-63
		uint16_t frm_gap;//us
		uint32_t frm_num;
	} stream_ctrl;
};


#endif