  /**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_IMU_TYPES_H
#define __TSDEV_API_IMU_TYPES_H
#include "tsdev_types.h"
#include "tsdev_api_base_types.h"

/**\name    Accel Bandwidth */
#define BMI08_ACCEL_BW_OSR4                     (0x08)
#define BMI08_ACCEL_BW_OSR2                     (0x09)
#define BMI08_ACCEL_BW_NORMAL                   (0x0A)
/**\name    Accel Output data rate */
#define BMI08_ACCEL_ODR_12_5_HZ                 (0x05)
#define BMI08_ACCEL_ODR_25_HZ                   (0x06)
#define BMI08_ACCEL_ODR_50_HZ                   (0x07)
#define BMI08_ACCEL_ODR_100_HZ                  (0x08)
#define BMI08_ACCEL_ODR_200_HZ                  (0x09)
#define BMI08_ACCEL_ODR_400_HZ                  (0x0A)
#define BMI08_ACCEL_ODR_800_HZ                  (0x0B)
#define BMI08_ACCEL_ODR_1600_HZ                 (0x0C)
/**\name    Accel Power mode */
#define BMI08_ACCEL_PM_ACTIVE                   (0x00)
#define BMI08_ACCEL_PM_SUSPEND                  (0x03)
/**\name    Accel range */
#define BMI088_ACCEL_RANGE_3G                   (0x00)
#define BMI088_ACCEL_RANGE_6G                   (0x01)
#define BMI088_ACCEL_RANGE_12G                  (0x02)
#define BMI088_ACCEL_RANGE_24G                  (0x03)

/**\name    Gyro Range */
#define BMI08_GYRO_RANGE_2000_DPS               (0x00)
#define BMI08_GYRO_RANGE_1000_DPS               (0x01)
#define BMI08_GYRO_RANGE_500_DPS                (0x02)
#define BMI08_GYRO_RANGE_250_DPS                (0x03)
#define BMI08_GYRO_RANGE_125_DPS                (0x04)
/**\name    Gyro Output data rate and bandwidth */
#define BMI08_GYRO_BW_532_ODR_2000_HZ           (0x00)
#define BMI08_GYRO_BW_230_ODR_2000_HZ           (0x01)
#define BMI08_GYRO_BW_116_ODR_1000_HZ           (0x02)
#define BMI08_GYRO_BW_47_ODR_400_HZ             (0x03)
#define BMI08_GYRO_BW_23_ODR_200_HZ             (0x04)
#define BMI08_GYRO_BW_12_ODR_100_HZ             (0x05)
#define BMI08_GYRO_BW_64_ODR_200_HZ             (0x06)
#define BMI08_GYRO_BW_32_ODR_100_HZ             (0x07)
/**\name    Gyro Power mode */
#define BMI08_GYRO_PM_NORMAL                    (0x00)
#define BMI08_GYRO_PM_DEEP_SUSPEND              (0x20)
#define BMI08_GYRO_PM_SUSPEND                   (0x80)

enum bmi08_cmd_type_t {
	imu_cmd_set_cfg = 0,
	imu_cmd_get_cfg,
};

struct bmi08_cfg {
    uint8_t power;
    uint8_t range;
    uint8_t bw;
    uint8_t odr;
};

struct bmi08_dev {
    struct bmi08_cfg accel_cfg;
    struct bmi08_cfg gyro_cfg;
};

struct bmi08_cmd_t {
	uint8_t type;
	uint8_t err_code;
	uint8_t res[6];
	struct bmi08_dev cfg_dat;
};

struct bmi08_data_float_to_fixed {
	int32_t x;
	int32_t y;
	int32_t z;
};

struct bmi08_upload_dat_t {
	struct bmi08_data_float_to_fixed accel_fixed;
	struct bmi08_data_float_to_fixed gyro_fixed;
	int32_t temperature;
};

typedef tsdev_err_t (*tsdev_imu_cmd_event_t)(tsdev_handle_t handle, void* usr_arg, tsdev_tsmsg_t msg,
 uint16_t fdid, uint16_t fsize, const struct bmi08_cmd_t* cmd_p);

typedef tsdev_err_t (*tsdev_imu_data_event_t)(tsdev_handle_t handle, void* usr_arg, tsdev_tsmsg_t msg,
 uint16_t fdid, uint16_t fsize, const struct bmi08_upload_dat_t* data_p);

#endif