/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_CANFD_H
#define __TSDEV_API_CANFD_H
#include "tsdev_types.h"


#ifdef __cplusplus
extern "C"
{
#endif

#ifndef LIBTSDEVBASERT_EXPORTS
	//api for host only
	/**
	 * config CAN(FD) channel by baudrate, 80% sample rate.
	 * @param: handle, device handle
	 * @param: chn_idx, channel index from 0. (e.g. 0, 1, 2, 3 ...)
	 * @param: arb_baudrate_kbps: arbitrition field baudrate, kbps
	 * @param: data_baudrate_kbps: data field baudrate, kbps (no effect on Classic CAN)
	 * @param: controller_type: Classic CAN; 1: ISO CAN; 2: Non-ISO CAN
	 * @param: controller_mode: Normal;1: No ACK; 2: restricted; 3: internal loop-back mode; 4: external loop-back mode; 5: noraml-with self ack
	 * @param: enable_120res 0 - diable, 1 - enable
	 * @return: 0 - ok, !0 - nok
	 */
	TSDEV_API tsdev_api_can_configure_baudrate_async(tsdev_handle_t handle,
		uint8_t chn_idx, uint32_t arb_baudrate_kbps, uint32_t data_baudrate_kbps,
		uint8_t controller_type, uint8_t controller_mode, uint8_t enable_120res);

	TSDEV_API tsdev_api_can_cmd_reg_event(tsdev_handle_t handle,
		void* usr_arg,
		tsdev_can_cmd_event_t event);

	TSDEV_API tsdev_api_can_cmd_unreg_event(tsdev_handle_t handle,
		void* usr_arg,
		tsdev_can_cmd_event_t event);

	TSDEV_API tsdev_api_can_cmd_unreg_events(tsdev_handle_t handle);

	TSDEV_API tsdev_api_can_frame_reg_event(tsdev_handle_t handle,
		void* usr_arg,
		tsdev_can_frame_event_t event);

	TSDEV_API tsdev_api_can_frame_unreg_event(tsdev_handle_t handle,
		void* usr_arg,
		tsdev_can_frame_event_t event);

	TSDEV_API tsdev_api_can_frame_unreg_events(tsdev_handle_t handle);
#endif
	//api for host and rt
	TSDEV_API tsdev_api_can_configure_regs_async(tsdev_handle_t handle,
		const struct tsdev_TPC_FDHardwareConf* conf);

	TSDEV_API tsdev_api_can_transmit_async(tsdev_handle_t handle,
		const struct tsdev_canfd_tx_t* can);

	TSDEV_API tsdev_api_can_transmit_async_data_p(tsdev_handle_t handle,
		const struct tsdev_canfd_tx_t* can, uint8_t* data_p);

	TSDEV_API tsdev_api_can_stream_gen_cfg_async(tsdev_handle_t handle,
		const struct tsdev_TPC_CANFD_Stream_Gen_Cfg* config);

	TSDEV_API tsdev_api_can_frame_receive(tsdev_handle_t handle,
		void* usr_arg,
		uint32_t max_rx_cnt,
		tsdev_can_frame_event_t event);

#ifdef __cplusplus
}
#endif

#endif
