/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_HOST_LIB_C_H
#define __TSDEV_HOST_LIB_C_H
#include "tsdev_types.h"

#ifdef __cplusplus
extern "C"
{
#endif

	static inline tsdev_err_t tsdev_api_chk_version_pri(uint8_t v1, uint8_t v2, uint8_t v3)
	{
		if (v1 != FILE_VERSION_MAIN || v2 != FILE_VERSION_MID)
		{
			return tsdev_err_nok;
		}
		return tsdev_err_ok;
	}
#ifndef LIBTSDEVBASERT_EXPORTS
	//api for host only
	TSDEV_API tsdev_api_version(uint8_t* main_v, uint8_t* mid_v, uint8_t* sub_v, const char** gen_time);
	/**
	 * @brief create tsdev api handle.
	 * @param[in] ctx pointer to struct tsdev_context_t.
	 * @param[out] handle pointer to tsdev api handle.
	 * @return if 0, ok, else nok.
	 * @note
	 */
	TSDEV_API tsdev_api_create(const struct tsdev_context_t* ctx, tsdev_handle_t* handle, const struct tsdev_host_usr_in_params_t* over_write_par);
	/**
	 * @brief destroy tsdev api handle.
	 * @param[in] handle pointer to tsdev api handle.
	 * @return if 0, ok, else nok.
	 * @note
	 */
	TSDEV_API tsdev_api_destory(tsdev_handle_t handle);
	//same as tsdev_api_destory
	TSDEV_API tsdev_api_destroy(tsdev_handle_t handle);
	TSDEV_API tsdev_api_get_usr_arg(tsdev_handle_t handle, void** usr_arg_p);
	static inline tsdev_err_t tsdev_api_chk_version(void)
	{
		uint8_t v1, v2, v3;
		const char* gen_time;
		tsdev_api_version(&v1, &v2, &v3, &gen_time);
		return tsdev_api_chk_version_pri(v1, v2, v3);
	}

	/**
	 * @brief get usb interface speed by handle.
	 * @param[in] handle pointer to tsdev api handle.
	 * @param[in] speed_p 1-low, 2-full, 3-high, 4-super
	 * @return if 0, ok, else nok.
	 * @note
	 */
	TSDEV_API tsdev_api_get_usb_speed(tsdev_handle_t handle, int* speed_p);
	/* only for hm system */
	TSDEV_API tsdev_api_set_usb_deviceid(uint32_t cnt, const uint64_t* device_id_p);
	//todo: add map function
#endif

#ifdef __cplusplus
}
#endif

#include "tsdev_api_base.h"
#include "tsdev_api_netif.h"
#include "tsdev_api_rpc.h"
#include "tsdev_api_can.h"
#include "tsdev_api_lin.h"
#include "tsdev_api_eth.h"
#include "tsdev_api_win_rt.h"
#include "tsdev_api_sim.h"
#include "tsdev_api_ethercat.h"
#include "tsdev_api_logger.h"
#include "tsdev_api_logger_v1.h"
#include "tsdev_api_dev_th7012.h"
#include "tsdev_api_th7011.h"
#include "tsdev_api_th7012.h"
#include "tsdev_api_tx1000.h"
#include "tsdev_api_16845.h"
#include "tsdev_api_sent.h"
#include "tsdev_api_psi5.h"
#include "tsdev_api_flexray.h"
#include "tsdev_api_can_uds.h"
#include "tsdev_api_mng.h"
#include "tsdev_api_io.h"
#include "tsdev_api_tac.h"
#include "tsdev_api_dev_config.h"
#include "tsdev_api_imu.h"
#include "tsdev_api_mqtt.h"
#include "tsdev_api_ta1015.h"
#include "tsdev_api_usrmodule.h"
#include "tsdev_api_io_tts8848.h"
#include "tsdev_api_ecat_config.h"
#endif
