/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_NETIF_H
#define __TSDEV_API_NETIF_H

#include "tsdev_types.h"




#ifdef __cplusplus
extern "C"
{
#endif

#ifndef LIBTSDEVBASERT_EXPORTS
	//api for host only
	TSDEV_API tsdev_api_get_netif_cnt(uint16_t* count);
	TSDEV_API tsdev_api_get_netif_name(uint16_t idx, const char** name);
	TSDEV_API tsdev_api_get_netif_ip(uint16_t idx, const char** ip);
	TSDEV_API tsdev_api_get_netif_gw(uint16_t idx, const char** ip);
	TSDEV_API tsdev_api_get_netif_mask(uint16_t idx, const char** mask);
	TSDEV_API tsdev_api_get_netif_mac(uint16_t idx, const char** mac);
	//type:	 other=0,virtual=1,wired=2,wireless=3
	TSDEV_API tsdev_api_get_netif_type(uint16_t idx, uint32_t* type);
	//connect_status: disconnected = 0,connected = 1
	TSDEV_API tsdev_api_get_netif_connect_status(uint16_t idx, uint8_t* connect_status);
#endif

#ifdef __cplusplus
}
#endif

#endif
