/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_16845_H
#define __TSDEV_API_16845_H
#include "tsdev_types.h"

#ifdef __cplusplus
extern "C"
{
#endif
#include <stdint.h>	

#define ARRAY_SIZE_40M (10*1024)	
	typedef enum th7011_16845_test_state {
		tsdev_th7011_16845_test_state_idle = 0,
		tsdev_th7011_16845_test_state_running_testcase,
		tsdev_th7011_16845_test_state_config_baudrate,
		tsdev_th7011_16845_test_state_not_device,
	}th7011_16845_test_state_t;
	typedef enum th7011_16845_test_case_num {
		tsdev_th7011_16845_test_case_num_error = 0,
		tsdev_th7011_16845_test_case_num_config_baudrate,
		tsdev_th7011_16845_test_case_num_07_1_1 = 0x711,
		tsdev_th7011_16845_test_case_num_07_1_2,
		tsdev_th7011_16845_test_case_num_07_1_3,
		tsdev_th7011_16845_test_case_num_07_1_4,
		tsdev_th7011_16845_test_case_num_07_1_5,
		tsdev_th7011_16845_test_case_num_07_1_6,
		tsdev_th7011_16845_test_case_num_07_1_7,
		tsdev_th7011_16845_test_case_num_07_1_8,
		tsdev_th7011_16845_test_case_num_07_1_9,
		tsdev_th7011_16845_test_case_num_07_1_10,
		tsdev_th7011_16845_test_case_num_07_1_11,
		tsdev_th7011_16845_test_case_num_07_1_12,
		tsdev_th7011_16845_test_case_num_07_2_1,
		tsdev_th7011_16845_test_case_num_07_2_2,
		tsdev_th7011_16845_test_case_num_07_2_3,
		tsdev_th7011_16845_test_case_num_07_2_4,
		tsdev_th7011_16845_test_case_num_07_2_5,
		tsdev_th7011_16845_test_case_num_07_2_6,
		tsdev_th7011_16845_test_case_num_07_2_7,
		tsdev_th7011_16845_test_case_num_07_2_8,
		tsdev_th7011_16845_test_case_num_07_2_9,
		tsdev_th7011_16845_test_case_num_07_2_10,
		tsdev_th7011_16845_test_case_num_07_2_11,
		tsdev_th7011_16845_test_case_num_07_3_1,
		tsdev_th7011_16845_test_case_num_07_3_2,
		tsdev_th7011_16845_test_case_num_07_3_3,
		tsdev_th7011_16845_test_case_num_07_3_4,
		tsdev_th7011_16845_test_case_num_07_4_1,
		tsdev_th7011_16845_test_case_num_07_4_2,
		tsdev_th7011_16845_test_case_num_07_4_3,
		tsdev_th7011_16845_test_case_num_07_4_4,
		tsdev_th7011_16845_test_case_num_07_4_5,
		tsdev_th7011_16845_test_case_num_07_4_6,
		tsdev_th7011_16845_test_case_num_07_4_7,
		tsdev_th7011_16845_test_case_num_07_5_1,
		tsdev_th7011_16845_test_case_num_07_5_2,
		tsdev_th7011_16845_test_case_num_07_5_3,
		tsdev_th7011_16845_test_case_num_07_5_4,
		tsdev_th7011_16845_test_case_num_07_5_5,
		tsdev_th7011_16845_test_case_num_07_5_6,
		tsdev_th7011_16845_test_case_num_07_5_7,
		tsdev_th7011_16845_test_case_num_07_6_1,
		tsdev_th7011_16845_test_case_num_07_6_2,
		tsdev_th7011_16845_test_case_num_07_6_3,
		tsdev_th7011_16845_test_case_num_07_6_4,
		tsdev_th7011_16845_test_case_num_07_6_5,
		tsdev_th7011_16845_test_case_num_07_6_6,
		tsdev_th7011_16845_test_case_num_07_6_7,
		tsdev_th7011_16845_test_case_num_07_6_8,
		tsdev_th7011_16845_test_case_num_07_6_9,
		tsdev_th7011_16845_test_case_num_07_6_10,
		tsdev_th7011_16845_test_case_num_07_6_11,
		tsdev_th7011_16845_test_case_num_07_6_12,
		tsdev_th7011_16845_test_case_num_07_6_13,
		tsdev_th7011_16845_test_case_num_07_6_14,
		tsdev_th7011_16845_test_case_num_07_6_15,
		tsdev_th7011_16845_test_case_num_07_6_16,
		tsdev_th7011_16845_test_case_num_07_6_17,
		tsdev_th7011_16845_test_case_num_07_6_18,
		tsdev_th7011_16845_test_case_num_07_6_19,
		tsdev_th7011_16845_test_case_num_07_6_20,
		tsdev_th7011_16845_test_case_num_07_6_21,
		tsdev_th7011_16845_test_case_num_07_6_22,
		tsdev_th7011_16845_test_case_num_07_6_23,
		tsdev_th7011_16845_test_case_num_07_7_1,
		tsdev_th7011_16845_test_case_num_07_7_2,
		tsdev_th7011_16845_test_case_num_07_7_3,
		tsdev_th7011_16845_test_case_num_07_7_4,
		tsdev_th7011_16845_test_case_num_07_7_5,
		tsdev_th7011_16845_test_case_num_07_7_6,
		tsdev_th7011_16845_test_case_num_07_7_7,
		tsdev_th7011_16845_test_case_num_07_7_8,
		tsdev_th7011_16845_test_case_num_07_7_9,
		tsdev_th7011_16845_test_case_num_07_7_10,
		tsdev_th7011_16845_test_case_num_07_7_11,
		tsdev_th7011_16845_test_case_num_07_8_1,
		tsdev_th7011_16845_test_case_num_07_8_2,
		tsdev_th7011_16845_test_case_num_07_8_3,
		tsdev_th7011_16845_test_case_num_07_8_4,
		tsdev_th7011_16845_test_case_num_07_8_5,
		tsdev_th7011_16845_test_case_num_07_8_6,
		tsdev_th7011_16845_test_case_num_07_8_7,
		tsdev_th7011_16845_test_case_num_07_8_8,
		tsdev_th7011_16845_test_case_num_07_8_9,
		tsdev_th7011_16845_test_case_num_08_1_1,
		tsdev_th7011_16845_test_case_num_08_1_2,
		tsdev_th7011_16845_test_case_num_08_1_3,
		tsdev_th7011_16845_test_case_num_08_1_4,
		tsdev_th7011_16845_test_case_num_08_1_5,
		tsdev_th7011_16845_test_case_num_08_1_6,
		tsdev_th7011_16845_test_case_num_08_1_7,
		tsdev_th7011_16845_test_case_num_08_1_8,
		tsdev_th7011_16845_test_case_num_08_1_9,
		tsdev_th7011_16845_test_case_num_08_2_1,
		tsdev_th7011_16845_test_case_num_08_2_2,
		tsdev_th7011_16845_test_case_num_08_2_3,
		tsdev_th7011_16845_test_case_num_08_2_4,
		tsdev_th7011_16845_test_case_num_08_2_5,
		tsdev_th7011_16845_test_case_num_08_2_6,
		tsdev_th7011_16845_test_case_num_08_2_7,
		tsdev_th7011_16845_test_case_num_08_2_8,
		tsdev_th7011_16845_test_case_num_08_3_1,
		tsdev_th7011_16845_test_case_num_08_3_2,
		tsdev_th7011_16845_test_case_num_08_3_3,
		tsdev_th7011_16845_test_case_num_08_3_4,
		tsdev_th7011_16845_test_case_num_08_4_1,
		tsdev_th7011_16845_test_case_num_08_4_2,
		tsdev_th7011_16845_test_case_num_08_4_3,
		tsdev_th7011_16845_test_case_num_08_4_4,
		tsdev_th7011_16845_test_case_num_08_4_5,
		tsdev_th7011_16845_test_case_num_08_5_1,
		tsdev_th7011_16845_test_case_num_08_5_2,
		tsdev_th7011_16845_test_case_num_08_5_3,
		tsdev_th7011_16845_test_case_num_08_5_4,
		tsdev_th7011_16845_test_case_num_08_5_5,
		tsdev_th7011_16845_test_case_num_08_5_6,
		tsdev_th7011_16845_test_case_num_08_5_7,
		tsdev_th7011_16845_test_case_num_08_5_8,
		tsdev_th7011_16845_test_case_num_08_5_9,
		tsdev_th7011_16845_test_case_num_08_5_10,
		tsdev_th7011_16845_test_case_num_08_5_11,
		tsdev_th7011_16845_test_case_num_08_5_12,
		tsdev_th7011_16845_test_case_num_08_5_13,
		tsdev_th7011_16845_test_case_num_08_5_14,
		tsdev_th7011_16845_test_case_num_08_5_15,
		tsdev_th7011_16845_test_case_num_08_6_1,
		tsdev_th7011_16845_test_case_num_08_6_2,
		tsdev_th7011_16845_test_case_num_08_6_3,
		tsdev_th7011_16845_test_case_num_08_6_4,
		tsdev_th7011_16845_test_case_num_08_6_5,
		tsdev_th7011_16845_test_case_num_08_6_6,
		tsdev_th7011_16845_test_case_num_08_6_7,
		tsdev_th7011_16845_test_case_num_08_6_8,
		tsdev_th7011_16845_test_case_num_08_6_9,
		tsdev_th7011_16845_test_case_num_08_6_10,
		tsdev_th7011_16845_test_case_num_08_6_11,
		tsdev_th7011_16845_test_case_num_08_6_12,
		tsdev_th7011_16845_test_case_num_08_6_13,
		tsdev_th7011_16845_test_case_num_08_6_14,
		tsdev_th7011_16845_test_case_num_08_6_15,
		tsdev_th7011_16845_test_case_num_08_6_16,
		tsdev_th7011_16845_test_case_num_08_6_17,
		tsdev_th7011_16845_test_case_num_08_6_18,
		tsdev_th7011_16845_test_case_num_08_6_19,
		tsdev_th7011_16845_test_case_num_08_6_20,
		tsdev_th7011_16845_test_case_num_08_6_21,
		tsdev_th7011_16845_test_case_num_08_7_1,
		tsdev_th7011_16845_test_case_num_08_7_2,
		tsdev_th7011_16845_test_case_num_08_7_3,
		tsdev_th7011_16845_test_case_num_08_7_4,
		tsdev_th7011_16845_test_case_num_08_7_5,
		tsdev_th7011_16845_test_case_num_08_7_6,
		tsdev_th7011_16845_test_case_num_08_7_7,
		tsdev_th7011_16845_test_case_num_08_7_8,
		tsdev_th7011_16845_test_case_num_08_7_9,
		tsdev_th7011_16845_test_case_num_08_8_1,
		tsdev_th7011_16845_test_case_num_08_8_2,
		tsdev_th7011_16845_test_case_num_08_8_3,
		tsdev_th7011_16845_test_case_num_08_8_4,
		tsdev_th7011_16845_test_case_num_08_8_5,
		tsdev_th7011_16845_test_case_num_09_6_1,
		tsdev_th7011_16845_test_case_num_09_6_2
	}th7011_16845_test_case_num_t;
	typedef enum controller_type {
		tsdev_16845_controller_can,
		tsdev_16845_controller_can_fd,
		tsdev_16845_controller_non_can_fd_dnon,
	}can_version_enum_t;
	typedef enum frame_format {
		cbff,
		canfd_cbff,
		canfd_fbff,
		ceff,
		canfd_ceff,
		canfd_feff
	}frame_format_t;
	struct classical_cbff_ctrl {
		uint8_t dlc : 4;
		uint8_t fdf : 1;
		uint8_t ide : 1;
		uint8_t rtr : 1;
		uint8_t rev : 1;
	};
	struct fdcan_fbff_ctrl {
		uint16_t dlc : 4;
		uint16_t esi : 1;
		uint16_t brs : 1;
		uint16_t res : 1;
		uint16_t fdf : 1;
		uint16_t ide : 1;
		uint16_t rrs : 1;
		uint16_t rev : 6;
	};
	struct classical_ceff_ctrl {
		uint16_t dlc : 4;
		uint16_t r0 : 1;
		uint16_t fdf : 1;
		uint16_t rtr : 1;
		uint16_t ide : 1;
		uint16_t srr : 1;
		uint16_t rev : 7;
	};
	struct fdcan_feff_ctrl {
		uint16_t dlc : 4;
		uint16_t esi : 1;
		uint16_t brs : 1;
		uint16_t res : 1;
		uint16_t fdf : 1;
		uint16_t rrs : 1;
		uint16_t ide : 1;
		uint16_t srr : 1;
		uint16_t rev : 5;
	};
	union ctrl_t {
		uint16_t val;
		struct classical_cbff_ctrl cbff;
		struct fdcan_fbff_ctrl fbff;
		struct classical_ceff_ctrl ceff;
		struct fdcan_feff_ctrl feff;
	};
	struct __frame_data_t {
		uint32_t id;
		union ctrl_t  ctrl;
		uint16_t rev;//0 cbff ,1 canfd cbff ,2 canfd fbff, 3 ceff , 4 canfd ceff ,5 canfd feff ,others rev
		uint8_t data[64];
	};
	typedef struct tsdev_th7011_16845_test_canset {
		uint8_t can_version;				// can_version_enum
		uint8_t FPrescalerArb;     //     can clock prescaler
		uint8_t FBTR0Arb;          //     can btr0 register
		uint8_t FBTR1Arb;          //     can btr1 register

		uint8_t FSJWArb;           //     can sync. jump width
		uint8_t FPrescalerData;    //     can clock prescaler
		uint8_t FBTR0Data;         //     can btr0 register
		uint8_t FBTR1Data;         //     can btr1 register

		uint8_t FSJWData;          //     can sync. jump width
		uint8_t rev[7];
	}tsdev_th7011_16845_test_canset_t;

	typedef struct th7011_16845_test_7_1_1_set {
		/**  only pass in the 5th ID (random id), because the other IDs are fixed values.
		 *	For the classic CAN bus protocol, the maximum value of the ID is 0x7FF.
		 */
		uint32_t id;
		/** Set the timeout waiting time, with a minimum of 8 seconds;
		 *  if the specified time is less than 8, then this value will be set to 8.
		 *  0 : unlimited waiting  uint : seconds/s
		 */
		uint8_t canfd_tx_brs;
		uint8_t rev[7];
		/** Classical CAN: The length of incoming data corresponding to each ID ranges  [1, 8],
		 *				   data with a DLC of 0 does not need to be setted.
		 *		data[0]~data[7]   : id is 0x555
		 *		data[8]~data[15]  : id is 0x2AA
		 *		data[16]~data[23] : id is 0x000
		 *		data[24]~data[31] : id is 0x7FF
		 *		data[32]~data[39] : id is a random value
		 *	Can Fd: The length of incoming data corresponding to each ID ranges  [1, 8] & [12] & [16] & [20] & [24] & [32] & [48] & [64]
		 *			data with a DLC of 0 does not need to be setted.
		 *		data[40]~data[54] : id is 0x555
		 *		data[55]~data[69] : id is 0x2AA
		 *		data[70]~data[84] : id is 0x000
		 *		data[85]~data[99] : id is 0x7FF
		 *		data[100]~data[114] : id is a random value
		 */
		uint8_t data[115][64];
	}th7011_16845_test_7_1_1_set_t;
	typedef struct th7011_16845_test_7_1_3_set {
		struct __frame_data_t data[6];
	}th7011_16845_test_7_1_3_set_t;
	typedef struct th7011_16845_test_7_1_4_set {
		struct __frame_data_t data;	// (cbff && classical can && fdf = 1) or (fbff && can fd && fdf = 1 && rrs = 1)
	}th7011_16845_test_7_1_4_set_t;
	typedef struct th7011_16845_test_7_1_5_set {
		uint64_t can_mode; // 0 classical can  1 can_fd tolerant  2 can_fd enabled
		struct __frame_data_t data[7];	// ceff && classical can   && {srr, fdf, r0}
		// ceff && can_fd tolerant && {srr, fdf = 0, r0}
		// feff && can_fd enabled  && {srr, rrs, fdf = 1}
	}th7011_16845_test_7_1_5_set_t;
	typedef struct th7011_16845_test_7_1_6_set {
		uint64_t can_mode;	// mode == 0: can_fd tolerant	 mode == 1: can_fd enabled
		struct __frame_data_t data;
		tsdev_th7011_16845_test_canset_t can_set;
	}th7011_16845_test_7_1_6_set_t;
	typedef struct th7011_16845_test_7_1_7_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_7_1_7_set_t;
	typedef struct th7011_16845_test_7_1_8_set {
		uint32_t canid;
		uint32_t ide;
		uint8_t data[7][8];
	}th7011_16845_test_7_1_8_set_t;
	typedef struct th7011_16845_test_7_1_9_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_7_1_9_set_t;
	typedef struct th7011_16845_test_7_1_10_set {
		uint64_t can_mode;//testcase 710   0 classical,1 fd can ,std frame,2 fd can,can fd frame
	}th7011_16845_test_7_1_10_set_t;
	typedef struct th7011_16845_test_7_1_11_set {
		uint64_t can_mode;	//testcase 711	0 classical ext ,1 fd can ext ,2 fd can,can fd ext frame
	}th7011_16845_test_7_1_11_set_t;
	typedef struct th7011_16845_test_7_1_12_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_1_12_set_t;

	typedef struct th7011_16845_test_7_2_1_set {
		struct __frame_data_t data;//tx any frame
	}th7011_16845_test_7_2_1_set_t;
	typedef struct th7011_16845_test_7_2_2_set {
		uint64_t can_mode;
		uint8_t disturb_pos[10];
	}th7011_16845_test_7_2_2_set_t;
	typedef struct th7011_16845_test_7_2_3_set {
		uint64_t can_mode;
		uint8_t disturb_pos[11];
	}th7011_16845_test_7_2_3_set_t;
	typedef struct th7011_16845_test_7_2_4_set {
		struct __frame_data_t data[8];	//canfd enabled fbff
		uint8_t disturb_pos[8];	// user set disturb bit with every frame
	}th7011_16845_test_7_2_4_set_t;
	typedef struct th7011_16845_test_7_2_5_set {
		struct __frame_data_t data[6];
	}th7011_16845_test_7_2_5_set_t;
	typedef struct th7011_16845_test_7_2_6_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_7_2_6_set_t;
	typedef struct th7011_16845_test_7_2_7_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_2_7_set_t;
	typedef struct th7011_16845_test_7_2_8_set {
		struct __frame_data_t data[22];	//canfd enabled
	}th7011_16845_test_7_2_8_set_t;
	typedef struct th7011_16845_test_7_2_9_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_2_9_set_t;
	typedef struct th7011_16845_test_7_2_10_set {
		struct __frame_data_t data;//tx any frame
	}th7011_16845_test_7_2_10_set_t;
	typedef struct th7011_16845_test_7_2_11_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_2_11_set_t;

	typedef struct th7011_16845_test_7_3_1_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_7_3_1_set_t;
	typedef struct th7011_16845_test_7_3_2_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_3_2_set_t;
	typedef struct th7011_16845_test_7_3_3_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_7_3_3_set_t;
	typedef struct th7011_16845_test_7_3_4_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_7_3_4_set_t;

	typedef struct th7011_16845_test_7_4_1_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_7_4_1_set_t;
	typedef struct th7011_16845_test_7_4_2_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_4_2_set_t;
	typedef struct th7011_16845_test_7_4_3_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_7_4_3_set_t;
	typedef struct th7011_16845_test_7_4_4_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_7_4_4_set_t;
	typedef struct th7011_16845_test_7_4_5_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_7_4_5_set_t;
	typedef struct th7011_16845_test_7_4_6_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_7_4_6_set_t;
	typedef struct th7011_16845_test_7_4_7_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_7_4_7_set_t;

	typedef struct th7011_16845_test_7_5_1_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_7_5_1_set_t;
	typedef struct th7011_16845_test_7_5_2_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_5_2_set_t;
	typedef struct th7011_16845_test_7_5_3_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_7_5_3_set_t;
	typedef struct th7011_16845_test_7_5_4_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_5_4_set_t;
	typedef struct th7011_16845_test_7_5_5_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_7_5_5_set_t;
	typedef struct th7011_16845_test_7_5_6_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_7_5_6_set_t;
	typedef struct th7011_16845_test_7_5_7_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_5_7_set_t;

	typedef struct th7011_16845_test_7_6_1_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_7_6_1_set_t;
	typedef struct th7011_16845_test_7_6_2_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_7_6_2_set_t;
	typedef struct th7011_16845_test_7_6_3_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_6_3_set_t;
	typedef struct th7011_16845_test_7_6_4_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_6_4_set_t;
	typedef struct th7011_16845_test_7_6_5_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_6_5_set_t;
	typedef struct th7011_16845_test_7_6_6_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_6_6_set_t;
	typedef struct th7011_16845_test_7_6_7_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_6_7_set_t;
	typedef struct th7011_16845_test_7_6_8_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_7_6_8_set_t;
	typedef struct th7011_16845_test_7_6_9_set {
		struct __frame_data_t data[8];
	}th7011_16845_test_7_6_9_set_t;
	typedef struct th7011_16845_test_7_6_10_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_7_6_10_set_t;
	typedef struct th7011_16845_test_7_6_11_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_6_11_set_t;
	typedef struct th7011_16845_test_7_6_12_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_7_6_12_set_t;
	typedef struct th7011_16845_test_7_6_13_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_7_6_13_set_t;

	typedef struct th7011_16845_test_7_7_1_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_7_1_set_t;
	typedef struct th7011_16845_test_7_7_2_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_7_2_set_t;
	typedef struct th7011_16845_test_7_7_3_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_7_3_set_t;
	typedef struct th7011_16845_test_7_7_4_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_7_4_set_t;
	typedef struct th7011_16845_test_7_7_5_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_7_5_set_t;
	typedef struct th7011_16845_test_7_7_6_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_7_6_set_t;
	typedef struct th7011_16845_test_7_7_7_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_7_7_set_t;
	typedef struct th7011_16845_test_7_7_8_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_7_8_set_t;
	typedef struct th7011_16845_test_7_7_9_set {
		uint8_t child_num;	// comment replaced to ASCII
		struct __frame_data_t data;
	}th7011_16845_test_7_7_9_set_t;
	typedef struct th7011_16845_test_7_7_10_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_7_10_set_t;
	typedef struct th7011_16845_test_7_7_11_set {
		struct __frame_data_t data;
	}th7011_16845_test_7_7_11_set_t;

	typedef struct th7011_16845_test_7_8_1_set {
		uint8_t child_num;	// comment replaced to ASCII
		struct __frame_data_t data[2];
	}th7011_16845_test_7_8_1_set_t;
	typedef struct th7011_16845_test_7_8_2_set {
		uint8_t child_num;	// comment replaced to ASCII
		struct __frame_data_t data;
	}th7011_16845_test_7_8_2_set_t;

	typedef struct th7011_16845_test_8_1_1_set {
		struct __frame_data_t data[125];
	}th7011_16845_test_8_1_1_set_t;
	typedef struct th7011_16845_test_8_1_2_set {
		struct __frame_data_t data[125];
	}th7011_16845_test_8_1_2_set_t;
	typedef struct th7011_16845_test_8_1_3_set {
		struct __frame_data_t data[11];
	}th7011_16845_test_8_1_3_set_t;
	typedef struct th7011_16845_test_8_1_4_set {
		struct __frame_data_t data[31];
	}th7011_16845_test_8_1_4_set_t;
	typedef struct th7011_16845_test_8_1_5_set {
		struct __frame_data_t data;
	}th7011_16845_test_8_1_5_set_t;
	typedef struct th7011_16845_test_8_1_6_set {
		struct __frame_data_t data[10];
	}th7011_16845_test_8_1_6_set_t;
	typedef struct th7011_16845_test_8_1_7_set {
		struct __frame_data_t data[10];
	}th7011_16845_test_8_1_7_set_t;
	typedef struct th7011_16845_test_8_1_8_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_8_1_8_set_t;

	typedef struct th7011_16845_test_8_2_1_set {
		struct __frame_data_t data[21];
	}th7011_16845_test_8_2_1_set_t;
	typedef struct th7011_16845_test_8_2_2_set {
		struct __frame_data_t data[21];
	}th7011_16845_test_8_2_2_set_t;
	typedef struct th7011_16845_test_8_2_3_set {
		struct __frame_data_t data[10];
		uint8_t disturb_pos[10];
	}th7011_16845_test_8_2_3_set_t;
	typedef struct th7011_16845_test_8_2_4_set {
		struct __frame_data_t data[10];
	}th7011_16845_test_8_2_4_set_t;
	typedef struct th7011_16845_test_8_2_5_set {
		struct __frame_data_t data[7];
	}th7011_16845_test_8_2_5_set_t;
	typedef struct th7011_16845_test_8_2_6_set {
		struct __frame_data_t data;
	}th7011_16845_test_8_2_6_set_t;
	typedef struct th7011_16845_test_8_2_7_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_8_2_7_set_t;
	typedef struct th7011_16845_test_8_2_8_set {
		struct __frame_data_t data[8];
	}th7011_16845_test_8_2_8_set_t;

	typedef struct th7011_16845_test_8_3_1_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_8_3_1_set_t;
	typedef struct th7011_16845_test_8_3_2_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_8_3_2_set_t;
	typedef struct th7011_16845_test_8_3_3_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_8_3_3_set_t;
	typedef struct th7011_16845_test_8_3_4_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_8_3_4_set_t;

	typedef struct th7011_16845_test_8_4_1_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_8_4_1_set_t;
	typedef struct th7011_16845_test_8_4_2_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_8_4_2_set_t;
	typedef struct th7011_16845_test_8_4_3_set {
		struct __frame_data_t data[2];
	}th7011_16845_test_8_4_3_set_t;
	typedef struct th7011_16845_test_8_4_4_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_8_4_4_set_t;
	typedef struct th7011_16845_test_8_4_5_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_8_4_5_set_t;

	typedef struct th7011_16845_test_8_5_1_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_8_5_1_set_t;
	typedef struct th7011_16845_test_8_5_2_set {
		struct __frame_data_t data;
	}th7011_16845_test_8_5_2_set_t;
	typedef struct th7011_16845_test_8_5_3_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_8_5_3_set_t;
	typedef struct th7011_16845_test_8_5_4_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_8_5_4_set_t;
	typedef struct th7011_16845_test_8_5_5_set {
		struct __frame_data_t data;
	}th7011_16845_test_8_5_5_set_t;
	typedef struct th7011_16845_test_8_5_6_set {
		struct __frame_data_t data;
	}th7011_16845_test_8_5_6_set_t;
	typedef struct th7011_16845_test_8_5_7_set {
		struct __frame_data_t data;
	}th7011_16845_test_8_5_7_set_t;
	typedef struct th7011_16845_test_8_5_8_set {
		struct __frame_data_t data;
	}th7011_16845_test_8_5_8_set_t;
	typedef struct th7011_16845_test_8_5_9_set {
		struct __frame_data_t data[3];
	}th7011_16845_test_8_5_9_set_t;

	typedef struct th7011_16845_test_8_7_1_set {
		struct __frame_data_t data;
	}th7011_16845_test_8_7_1_set_t;
	typedef struct th7011_16845_test_8_7_2_set {
		struct __frame_data_t data;
	}th7011_16845_test_8_7_2_set_t;
	typedef struct th7011_16845_test_8_7_4_set {
		struct __frame_data_t data;
	}th7011_16845_test_8_7_4_set_t;

	typedef struct th7011_16845_test_8_8_1_set {
		uint8_t child_num;	// comment replaced to ASCII
		struct __frame_data_t data[2];
	}th7011_16845_test_8_8_1_set_t;
	typedef struct th7011_16845_test_case_frame_data {
		uint64_t testcase_num;//th7011_16845_test_case_num_t
		tsdev_th7011_16845_test_canset_t can;
		uint16_t timeout;
		/* config
			[0]:   use_single_failed_continue,	bit position:[0]
						Should testing continue with other frames after encountering an error in a test frame ?  1:yes 0:no
			[1:15]: reserved bit
		 */
		uint16_t test_config;
		uint32_t wave_mask;
		union {
			th7011_16845_test_7_1_1_set_t data_0711;
			th7011_16845_test_7_1_1_set_t data_0712;
			th7011_16845_test_7_1_3_set_t data_0713;
			th7011_16845_test_7_1_4_set_t data_0714;
			th7011_16845_test_7_1_5_set_t data_0715;
			th7011_16845_test_7_1_6_set_t data_0716;
			th7011_16845_test_7_1_7_set_t data_0717;
			th7011_16845_test_7_1_8_set_t data_0718;
			th7011_16845_test_7_1_9_set_t data_0719;
			th7011_16845_test_7_1_10_set_t data_071_10;
			th7011_16845_test_7_1_11_set_t data_071_11;
			th7011_16845_test_7_1_12_set_t data_071_12;
			th7011_16845_test_7_2_1_set_t data_0721;
			th7011_16845_test_7_2_2_set_t data_0722;
			th7011_16845_test_7_2_3_set_t data_0723;
			th7011_16845_test_7_2_4_set_t data_0724;
			th7011_16845_test_7_2_5_set_t data_0725;
			th7011_16845_test_7_2_6_set_t data_0726;
			th7011_16845_test_7_2_7_set_t data_0727;
			th7011_16845_test_7_2_8_set_t data_0728;
			th7011_16845_test_7_2_9_set_t data_0729;
			th7011_16845_test_7_2_10_set_t data_072_10;
			th7011_16845_test_7_2_11_set_t data_072_11;
			th7011_16845_test_7_3_1_set_t data_0731;
			th7011_16845_test_7_3_2_set_t data_0732;
			th7011_16845_test_7_3_3_set_t data_0733;
			th7011_16845_test_7_3_4_set_t data_0734;
			th7011_16845_test_7_4_1_set_t data_0741;
			th7011_16845_test_7_4_2_set_t data_0742;
			th7011_16845_test_7_4_3_set_t data_0743;
			th7011_16845_test_7_4_4_set_t data_0744;
			th7011_16845_test_7_4_5_set_t data_0745;
			th7011_16845_test_7_4_6_set_t data_0746;
			th7011_16845_test_7_4_7_set_t data_0747;
			th7011_16845_test_7_5_1_set_t data_0751;
			th7011_16845_test_7_5_2_set_t data_0752;
			th7011_16845_test_7_5_3_set_t data_0753;
			th7011_16845_test_7_5_4_set_t data_0754;
			th7011_16845_test_7_5_5_set_t data_0755;
			th7011_16845_test_7_5_6_set_t data_0756;
			th7011_16845_test_7_5_7_set_t data_0757;
			th7011_16845_test_7_6_1_set_t data_0761;
			th7011_16845_test_7_6_2_set_t data_0762;
			th7011_16845_test_7_6_3_set_t data_0763;
			th7011_16845_test_7_6_4_set_t data_0764;
			th7011_16845_test_7_6_5_set_t data_0765;
			th7011_16845_test_7_6_6_set_t data_0766;
			th7011_16845_test_7_6_7_set_t data_0767;
			th7011_16845_test_7_6_8_set_t data_0768;
			th7011_16845_test_7_6_9_set_t data_0769;
			th7011_16845_test_7_6_10_set_t data_076_10;
			th7011_16845_test_7_6_11_set_t data_076_11;
			th7011_16845_test_7_6_12_set_t data_076_12;
			th7011_16845_test_7_6_13_set_t data_076_13;
			th7011_16845_test_7_7_1_set_t data_0771;
			th7011_16845_test_7_7_2_set_t data_0772;
			th7011_16845_test_7_7_3_set_t data_0773;
			th7011_16845_test_7_7_4_set_t data_0774;
			th7011_16845_test_7_7_5_set_t data_0775;
			th7011_16845_test_7_7_6_set_t data_0776;
			th7011_16845_test_7_7_7_set_t data_0777;
			th7011_16845_test_7_7_8_set_t data_0778;
			th7011_16845_test_7_7_9_set_t data_0779;
			th7011_16845_test_7_7_10_set_t data_077_10;
			th7011_16845_test_7_7_11_set_t data_077_11;
			th7011_16845_test_7_8_1_set_t data_0781;
			th7011_16845_test_7_8_2_set_t data_0782;
			th7011_16845_test_8_1_1_set_t data_0811;
			th7011_16845_test_8_1_2_set_t data_0812;
			th7011_16845_test_8_1_3_set_t data_0813;
			th7011_16845_test_8_1_4_set_t data_0814;
			th7011_16845_test_8_1_5_set_t data_0815;
			th7011_16845_test_8_1_6_set_t data_0816;
			th7011_16845_test_8_1_7_set_t data_0817;
			th7011_16845_test_8_1_8_set_t data_0818;
			th7011_16845_test_8_2_1_set_t data_0821;
			th7011_16845_test_8_2_2_set_t data_0822;
			th7011_16845_test_8_2_3_set_t data_0823;
			th7011_16845_test_8_2_4_set_t data_0824;
			th7011_16845_test_8_2_5_set_t data_0825;
			th7011_16845_test_8_2_6_set_t data_0826;
			th7011_16845_test_8_2_7_set_t data_0827;
			th7011_16845_test_8_2_8_set_t data_0828;
			th7011_16845_test_8_3_1_set_t data_0831;
			th7011_16845_test_8_3_2_set_t data_0832;
			th7011_16845_test_8_3_3_set_t data_0833;
			th7011_16845_test_8_3_4_set_t data_0834;
			th7011_16845_test_8_4_1_set_t data_0841;
			th7011_16845_test_8_4_2_set_t data_0842;
			th7011_16845_test_8_4_3_set_t data_0843;
			th7011_16845_test_8_4_4_set_t data_0844;
			th7011_16845_test_8_4_5_set_t data_0845;
			th7011_16845_test_8_5_1_set_t data_0851;
			th7011_16845_test_8_5_2_set_t data_0852;
			th7011_16845_test_8_5_3_set_t data_0853;
			th7011_16845_test_8_5_4_set_t data_0854;
			th7011_16845_test_8_5_5_set_t data_0855;
			th7011_16845_test_8_5_6_set_t data_0856;
			th7011_16845_test_8_5_7_set_t data_0857;
			th7011_16845_test_8_5_8_set_t data_0858;
			th7011_16845_test_8_5_9_set_t data_0859;
			th7011_16845_test_8_7_1_set_t data_0871;
			th7011_16845_test_8_7_2_set_t data_0872;
			th7011_16845_test_8_7_4_set_t data_0874;
			th7011_16845_test_8_8_1_set_t data_0881;
		}frame_data;
	}th7011_16845_test_case_frame_data_t;
	typedef enum th7011_16845_test_status {
		/** the interface function executed successfully. */
		tsdev_th7011_16845_test_ok = 0,
		tsdev_th7011_16845_test_handle_invalid,
		tsdev_th7011_16845_test_license_invalid,
		/** error parameters entered. */
		tsdev_th7011_16845_test_param_err,
		/** testing is ongoing. */
		tsdev_th7011_16845_test_busy,
		/** communication with device has timed out. */
		tsdev_th7011_16845_test_call_timeout,
	}th7011_16845_test_status_t;

	typedef enum th7011_16845_test_result {
		tsdev_th7011_16845_test_pass = 0,
		tsdev_th7011_16845_test_failed,
		tsdev_th7011_16845_test_timeout,
		tsdev_th7011_16845_test_abort,
		/** the measured data is not tested. */
		tsdev_th7011_16845_test_not_run,
	} th7011_16845_test_result_t;
	typedef struct th7011_16845_test_cmd {
		uint8_t abort_cur_test;//abort test,if state is busy
		uint8_t rev[7];
	}th7011_16845_test_cmd_t;
	typedef struct th7011_16845_test_rsp {
		uint32_t cur_state;//th7011_16845_test_state_t
		uint32_t rsp_cmd;//0 ok,1 not run,others todo
		uint32_t cur_testcase_num;//th7011_16845_test_case_num_t
		uint32_t rev;
	}th7011_16845_test_rsp_t;
	typedef enum {
		tsdev_th7011_16845_host_state_idle,
		tsdev_th7011_16845_host_state_wait_result,
		tsdev_th7011_16845_host_state_get_result_end,
		tsdev_th7011_16845_host_state_wait_abort,
	}th7011_16845_host_state_t;
	typedef struct th7011_16845_test_case_single_return_info {
		/** th7011_16845_test_result_t */
		uint8_t test_result;
		/** 1 : err flag  0 : no err flag*/
		uint8_t err_flag;
		/** 1 : ack success  0 : ack error*/
		uint8_t ack_status;
		/** 1 : data match  0 : data not match*/
		uint8_t data_match;
		uint8_t err_location;//[0] fdf,[1] ext, [2] rtr, [3] dlc, [4] id,[5] brs,[6 - 7] rev
		uint8_t err_type;//[0] ack,[1] bit, [2] form, [3] crc, [4] stuff,[5 - 7] rev
		uint8_t rev[2];
	}th7011_16845_test_case_single_return_info_t;          //test results of each can frame(id, dlc, data)
	typedef struct th7011_16845_test_case_wave_data {
		uint16_t len;
		uint16_t id : 8;
		uint16_t total_cnt : 8;
		uint32_t wave_mask;
		uint8_t tx_array_40m[ARRAY_SIZE_40M];
		uint8_t rx_array_40m[ARRAY_SIZE_40M];
	}th7011_16845_test_case_wave_data_t;
	typedef struct rec_counter {
		uint8_t before;	// before frame corrupted
		uint8_t after;		// after frame corrupted
	}rec_counter_t;
	typedef struct th7011_16845_test_7_1_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[4];
		th7011_16845_test_7_1_1_set_t recovery_data;
		th7011_16845_test_case_single_return_info_t result_arry[125];
	}th7011_16845_test_7_1_1_result_info_t;
	typedef struct th7011_16845_test_7_1_3_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[4];
		th7011_16845_test_case_single_return_info_t result_arry[6];
		struct __frame_data_t LT_origin_frame[6];	// LT send frame
		struct __frame_data_t frame_data[6];	// IUT recv
	}th7011_16845_test_7_1_3_result_info_t;
	typedef struct th7011_16845_test_7_1_4_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[4];
		th7011_16845_test_case_single_return_info_t result;
		struct __frame_data_t frame_data;
	}th7011_16845_test_7_1_4_result_info_t;
	typedef struct th7011_16845_test_7_1_5_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[4];
		th7011_16845_test_case_single_return_info_t result_arry[7];
		struct __frame_data_t frame_data[7];
	}th7011_16845_test_7_1_5_result_info_t;
	typedef struct th7011_16845_test_7_1_6_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[4];
		th7011_16845_test_case_single_return_info_t result;
		struct __frame_data_t frame_data;
	}th7011_16845_test_7_1_6_result_info_t;
	typedef struct th7011_16845_test_7_1_7_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[4];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_7_1_7_result_info_t;
	typedef struct th7011_16845_test_7_1_8_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[4];
		th7011_16845_test_7_1_8_set_t recovery;
		th7011_16845_test_case_single_return_info_t result_arry[7];
	}th7011_16845_test_7_1_8_result_info_t;
	typedef struct th7011_16845_test_7_1_9_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[4];
		th7011_16845_test_case_single_return_info_t result_arry[2];
	}th7011_16845_test_7_1_9_result_info_t;
	typedef struct th7011_16845_test_7_1_10_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[4];
		th7011_16845_test_case_single_return_info_t result_arry[10];
		struct __frame_data_t frame_data[10];
	}th7011_16845_test_7_1_10_result_info_t;
	typedef struct th7011_16845_test_7_1_11_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[4];
		th7011_16845_test_case_single_return_info_t result_arry[11];
		struct __frame_data_t frame_data[11];
	}th7011_16845_test_7_1_11_result_info_t;
	typedef struct th7011_16845_test_7_1_12_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[4];
		th7011_16845_test_case_single_return_info_t result;
		struct __frame_data_t frame_data;
	}th7011_16845_test_7_1_12_result_info_t;

	typedef struct th7011_16845_test_7_2_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[4];//rev[0] 1 generate active error frame,0 do not generate active error frame
		th7011_16845_test_case_single_return_info_t result;//bit err
	}th7011_16845_test_7_2_1_result_info_t;
	typedef struct th7011_16845_test_7_2_2_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		//rev[0] [0] 1 generate active error frame,0 do not generate active error frame ... [9]
		//rev[1] [0] 1 bit postion ok,0 error ... [9]
		th7011_16845_test_case_single_return_info_t result_arry[10];
	}th7011_16845_test_7_2_2_result_info_t;
	typedef struct th7011_16845_test_7_2_3_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[11];
	}th7011_16845_test_7_2_3_result_info_t;
	typedef struct th7011_16845_test_7_2_4_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[8];
	}th7011_16845_test_7_2_4_result_info_t;
	typedef struct th7011_16845_test_7_2_5_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[6];
	}th7011_16845_test_7_2_5_result_info_t;
	typedef struct th7011_16845_test_7_2_6_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
	}th7011_16845_test_7_2_6_result_info_t;
	typedef struct th7011_16845_test_7_2_7_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_7_2_7_result_info_t;
	typedef struct th7011_16845_test_7_2_8_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[22];
	}th7011_16845_test_7_2_8_result_info_t;
	typedef struct th7011_16845_test_7_2_9_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_7_2_9_result_info_t;
	typedef struct th7011_16845_test_7_2_10_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[4];
		th7011_16845_test_case_single_return_info_t result_arry[5];
	}th7011_16845_test_7_2_10_result_info_t;
	typedef struct th7011_16845_test_7_2_11_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_7_2_11_result_info_t;

	typedef struct th7011_16845_test_7_3_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_7_3_1_result_info_t;
	typedef struct th7011_16845_test_7_3_2_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
		struct __frame_data_t frame_data;
	}th7011_16845_test_7_3_2_result_info_t;
	typedef struct th7011_16845_test_7_3_3_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_7_3_3_result_info_t;
	typedef struct th7011_16845_test_7_3_4_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_7_3_4_result_info_t;

	typedef struct th7011_16845_test_7_4_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
	}th7011_16845_test_7_4_1_result_info_t;
	typedef struct th7011_16845_test_7_4_2_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_7_4_2_result_info_t;
	typedef struct th7011_16845_test_7_4_3_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
	}th7011_16845_test_7_4_3_result_info_t;
	typedef struct th7011_16845_test_7_4_4_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_7_4_4_result_info_t;
	typedef struct th7011_16845_test_7_4_5_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_7_4_5_result_info_t;
	typedef struct th7011_16845_test_7_4_6_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
	}th7011_16845_test_7_4_6_result_info_t;
	typedef struct th7011_16845_test_7_4_7_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
	}th7011_16845_test_7_4_7_result_info_t;

	typedef struct th7011_16845_test_7_5_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_7_5_1_result_info_t;
	typedef struct th7011_16845_test_7_5_2_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_7_5_2_result_info_t;
	typedef struct th7011_16845_test_7_5_3_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_7_5_3_result_info_t;
	typedef struct th7011_16845_test_7_5_4_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[9];
	}th7011_16845_test_7_5_4_result_info_t;
	typedef struct th7011_16845_test_7_5_5_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_7_5_5_result_info_t;
	typedef struct th7011_16845_test_7_5_6_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_7_5_6_result_info_t;
	typedef struct th7011_16845_test_7_5_7_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_7_5_7_result_info_t;

	typedef struct th7011_16845_test_7_6_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
		rec_counter_t IUT_rec[3];
	}th7011_16845_test_7_6_1_result_info_t;
	typedef struct th7011_16845_test_7_6_2_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
		rec_counter_t IUT_rec[3];
	}th7011_16845_test_7_6_2_result_info_t;
	typedef struct th7011_16845_test_7_6_3_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
		rec_counter_t IUT_rec;
	}th7011_16845_test_7_6_3_result_info_t;
	typedef struct th7011_16845_test_7_6_4_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
		rec_counter_t IUT_rec;
	}th7011_16845_test_7_6_4_result_info_t;
	typedef struct th7011_16845_test_7_6_5_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
		rec_counter_t IUT_rec;
	}th7011_16845_test_7_6_5_result_info_t;
	typedef struct th7011_16845_test_7_6_6_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
		rec_counter_t IUT_rec;
	}th7011_16845_test_7_6_6_result_info_t;
	typedef struct th7011_16845_test_7_6_7_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
		rec_counter_t IUT_rec;
	}th7011_16845_test_7_6_7_result_info_t;
	typedef struct th7011_16845_test_7_6_8_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
		rec_counter_t IUT_rec[3];
	}th7011_16845_test_7_6_8_result_info_t;
	typedef struct th7011_16845_test_7_6_9_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[8];
		rec_counter_t IUT_rec[8];
	}th7011_16845_test_7_6_9_result_info_t;
	typedef struct th7011_16845_test_7_6_10_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
		rec_counter_t IUT_rec[2];
	}th7011_16845_test_7_6_10_result_info_t;
	typedef struct th7011_16845_test_7_6_11_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
		rec_counter_t IUT_rec;
	}th7011_16845_test_7_6_11_result_info_t;
	typedef struct th7011_16845_test_7_6_12_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
		rec_counter_t IUT_rec[2];
	}th7011_16845_test_7_6_12_result_info_t;
	typedef struct th7011_16845_test_7_6_13_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
		rec_counter_t IUT_rec[2];
	}th7011_16845_test_7_6_13_result_info_t;

	typedef struct th7011_16845_test_7_7_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_7_7_1_result_info_t;
	typedef struct th7011_16845_test_7_7_2_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		uint16_t test_N;
		th7011_16845_test_case_single_return_info_t result_arry[256];
	}th7011_16845_test_7_7_2_result_info_t;
	typedef struct th7011_16845_test_7_7_3_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		uint16_t test_N;
		th7011_16845_test_case_single_return_info_t result_arry[256];
	}th7011_16845_test_7_7_3_result_info_t;
	typedef struct th7011_16845_test_7_7_4_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		uint16_t test_N;
		th7011_16845_test_case_single_return_info_t result_arry[256];
	}th7011_16845_test_7_7_4_result_info_t;
	typedef struct th7011_16845_test_7_7_5_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		uint16_t test_N;
		th7011_16845_test_case_single_return_info_t result_arry[256];
	}th7011_16845_test_7_7_5_result_info_t;
	typedef struct th7011_16845_test_7_7_6_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		uint16_t test_N;
		th7011_16845_test_case_single_return_info_t result_arry[256];
	}th7011_16845_test_7_7_6_result_info_t;
	typedef struct th7011_16845_test_7_7_7_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_7_7_7_result_info_t;
	typedef struct th7011_16845_test_7_7_8_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_7_7_8_result_info_t;
	typedef struct th7011_16845_test_7_7_9_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
		uint8_t child_num;
	}th7011_16845_test_7_7_9_result_info_t;
	typedef struct th7011_16845_test_7_7_10_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_7_7_10_result_info_t;
	typedef struct th7011_16845_test_7_7_11_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		uint16_t test_N;
		th7011_16845_test_case_single_return_info_t result_arry[256];
	}th7011_16845_test_7_7_11_result_info_t;

	typedef struct th7011_16845_test_7_8_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
		uint8_t child_num;
	}th7011_16845_test_7_8_1_result_info_t;
	typedef struct th7011_16845_test_7_8_2_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint16_t rev[2];
		uint16_t test_N;
		th7011_16845_test_case_single_return_info_t result_arry[256];
		uint8_t child_num;
	}th7011_16845_test_7_8_2_result_info_t;

	typedef struct th7011_16845_test_8_1_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[125];
		struct __frame_data_t frame_data[125];
	}th7011_16845_test_8_1_1_result_info_t;
	typedef struct th7011_16845_test_8_1_2_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[125];
		struct __frame_data_t frame_data[125];
	}th7011_16845_test_8_1_2_result_info_t;
	typedef struct th7011_16845_test_8_1_3_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[11];
		struct __frame_data_t frame_data[11];
	}th7011_16845_test_8_1_3_result_info_t;
	typedef struct th7011_16845_test_8_1_4_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[31];
		struct __frame_data_t frame_data[31];
	}th7011_16845_test_8_1_4_result_info_t;
	typedef struct th7011_16845_test_8_1_5_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_8_1_5_result_info_t;
	typedef struct th7011_16845_test_8_1_6_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[10];
	}th7011_16845_test_8_1_6_result_info_t;
	typedef struct th7011_16845_test_8_1_7_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[10];
	}th7011_16845_test_8_1_7_result_info_t;
	typedef struct th7011_16845_test_8_1_8_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
	}th7011_16845_test_8_1_8_result_info_t;

	typedef struct th7011_16845_test_8_2_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[21];
	}th7011_16845_test_8_2_1_result_info_t;
	typedef struct th7011_16845_test_8_2_2_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[21];
	}th7011_16845_test_8_2_2_result_info_t;
	typedef struct th7011_16845_test_8_2_3_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[10];
	}th7011_16845_test_8_2_3_result_info_t;
	typedef struct th7011_16845_test_8_2_4_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[79];
	}th7011_16845_test_8_2_4_result_info_t;
	typedef struct th7011_16845_test_8_2_5_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[18];
	}th7011_16845_test_8_2_5_result_info_t;
	typedef struct th7011_16845_test_8_2_6_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_8_2_6_result_info_t;
	typedef struct th7011_16845_test_8_2_7_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
	}th7011_16845_test_8_2_7_result_info_t;
	typedef struct th7011_16845_test_8_2_8_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[1008];
	}th7011_16845_test_8_2_8_result_info_t;

	typedef struct th7011_16845_test_8_3_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_8_3_1_result_info_t;
	typedef struct th7011_16845_test_8_3_2_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
	}th7011_16845_test_8_3_2_result_info_t;
	typedef struct th7011_16845_test_8_3_3_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_8_3_3_result_info_t;
	typedef struct th7011_16845_test_8_3_4_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_8_3_4_result_info_t;

	typedef struct th7011_16845_test_8_4_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
	}th7011_16845_test_8_4_1_result_info_t;
	typedef struct th7011_16845_test_8_4_2_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
	}th7011_16845_test_8_4_2_result_info_t;
	typedef struct th7011_16845_test_8_4_3_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
	}th7011_16845_test_8_4_3_result_info_t;
	typedef struct th7011_16845_test_8_4_4_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_8_4_4_result_info_t;
	typedef struct th7011_16845_test_8_4_5_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_8_4_5_result_info_t;

	typedef struct th7011_16845_test_8_5_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_8_5_1_result_info_t;
	typedef struct th7011_16845_test_8_5_2_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_8_5_2_result_info_t;
	typedef struct th7011_16845_test_8_5_3_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_8_5_3_result_info_t;
	typedef struct th7011_16845_test_8_5_4_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_8_5_4_result_info_t;
	typedef struct th7011_16845_test_8_5_5_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_8_5_5_result_info_t;
	typedef struct th7011_16845_test_8_5_6_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_8_5_6_result_info_t;
	typedef struct th7011_16845_test_8_5_7_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_8_5_7_result_info_t;
	typedef struct th7011_16845_test_8_5_8_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_8_5_8_result_info_t;
	typedef struct th7011_16845_test_8_5_9_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[3];
	}th7011_16845_test_8_5_9_result_info_t;

	typedef struct th7011_16845_test_8_7_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_8_7_1_result_info_t;
	typedef struct th7011_16845_test_8_7_2_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result;
	}th7011_16845_test_8_7_2_result_info_t;
	typedef struct th7011_16845_test_8_7_4_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		uint16_t test_N;
		th7011_16845_test_case_single_return_info_t result_arry[256];
	}th7011_16845_test_8_7_4_result_info_t;

	typedef struct th7011_16845_test_8_8_1_result_info {
		uint8_t total_result;
		uint8_t tsdev_th7011_16845_test_passed_num;
		uint8_t tsdev_th7011_16845_test_failed_num;
		uint8_t not_run_number;
		uint8_t rev[2];
		th7011_16845_test_case_single_return_info_t result_arry[2];
		uint8_t child_num;
	}th7011_16845_test_8_8_1_result_info_t;
	typedef struct th7011_16845_test_case_result_info {
		uint64_t test_case_num;//th7011_16845_test_case_num_t
		union {
			th7011_16845_test_7_1_1_result_info_t testcase0711_result;
			th7011_16845_test_7_1_1_result_info_t testcase0712_result;
			th7011_16845_test_7_1_3_result_info_t testcase0713_result;
			th7011_16845_test_7_1_4_result_info_t testcase0714_result;
			th7011_16845_test_7_1_5_result_info_t testcase0715_result;
			th7011_16845_test_7_1_6_result_info_t testcase0716_result;
			th7011_16845_test_7_1_7_result_info_t testcase0717_result;
			th7011_16845_test_7_1_8_result_info_t testcase0718_result;
			th7011_16845_test_7_1_9_result_info_t testcase0719_result;
			th7011_16845_test_7_1_10_result_info_t testcase07110_result;
			th7011_16845_test_7_1_11_result_info_t testcase07111_result;
			th7011_16845_test_7_1_12_result_info_t testcase07112_result;
			th7011_16845_test_7_2_1_result_info_t testcase0721_result;
			th7011_16845_test_7_2_2_result_info_t testcase0722_result;
			th7011_16845_test_7_2_3_result_info_t testcase0723_result;
			th7011_16845_test_7_2_4_result_info_t testcase0724_result;
			th7011_16845_test_7_2_5_result_info_t testcase0725_result;
			th7011_16845_test_7_2_6_result_info_t testcase0726_result;
			th7011_16845_test_7_2_7_result_info_t testcase0727_result;
			th7011_16845_test_7_2_8_result_info_t testcase0728_result;
			th7011_16845_test_7_2_9_result_info_t testcase0729_result;
			th7011_16845_test_7_2_10_result_info_t testcase07210_result;
			th7011_16845_test_7_2_11_result_info_t testcase07211_result;
			th7011_16845_test_7_3_1_result_info_t testcase0731_result;
			th7011_16845_test_7_3_2_result_info_t testcase0732_result;
			th7011_16845_test_7_3_3_result_info_t testcase0733_result;
			th7011_16845_test_7_3_4_result_info_t testcase0734_result;
			th7011_16845_test_7_4_1_result_info_t testcase0741_result;
			th7011_16845_test_7_4_2_result_info_t testcase0742_result;
			th7011_16845_test_7_4_3_result_info_t testcase0743_result;
			th7011_16845_test_7_4_4_result_info_t testcase0744_result;
			th7011_16845_test_7_4_5_result_info_t testcase0745_result;
			th7011_16845_test_7_4_6_result_info_t testcase0746_result;
			th7011_16845_test_7_4_7_result_info_t testcase0747_result;
			th7011_16845_test_7_5_1_result_info_t testcase0751_result;
			th7011_16845_test_7_5_2_result_info_t testcase0752_result;
			th7011_16845_test_7_5_3_result_info_t testcase0753_result;
			th7011_16845_test_7_5_4_result_info_t testcase0754_result;
			th7011_16845_test_7_5_5_result_info_t testcase0755_result;
			th7011_16845_test_7_5_6_result_info_t testcase0756_result;
			th7011_16845_test_7_5_7_result_info_t testcase0757_result;
			th7011_16845_test_7_6_1_result_info_t testcase0761_result;
			th7011_16845_test_7_6_2_result_info_t testcase0762_result;
			th7011_16845_test_7_6_3_result_info_t testcase0763_result;
			th7011_16845_test_7_6_4_result_info_t testcase0764_result;
			th7011_16845_test_7_6_5_result_info_t testcase0765_result;
			th7011_16845_test_7_6_6_result_info_t testcase0766_result;
			th7011_16845_test_7_6_7_result_info_t testcase0767_result;
			th7011_16845_test_7_6_8_result_info_t testcase0768_result;
			th7011_16845_test_7_6_9_result_info_t testcase0769_result;
			th7011_16845_test_7_6_10_result_info_t testcase07610_result;
			th7011_16845_test_7_6_11_result_info_t testcase07611_result;
			th7011_16845_test_7_6_12_result_info_t testcase07612_result;
			th7011_16845_test_7_6_13_result_info_t testcase07613_result;
			th7011_16845_test_7_7_1_result_info_t testcase0771_result;
			th7011_16845_test_7_7_2_result_info_t testcase0772_result;
			th7011_16845_test_7_7_3_result_info_t testcase0773_result;
			th7011_16845_test_7_7_4_result_info_t testcase0774_result;
			th7011_16845_test_7_7_5_result_info_t testcase0775_result;
			th7011_16845_test_7_7_6_result_info_t testcase0776_result;
			th7011_16845_test_7_7_7_result_info_t testcase0777_result;
			th7011_16845_test_7_7_8_result_info_t testcase0778_result;
			th7011_16845_test_7_7_9_result_info_t testcase0779_result;
			th7011_16845_test_7_7_10_result_info_t testcase07710_result;
			th7011_16845_test_7_7_11_result_info_t testcase07711_result;
			th7011_16845_test_7_8_1_result_info_t testcase0781_result;
			th7011_16845_test_7_8_2_result_info_t testcase0782_result;
			th7011_16845_test_8_1_1_result_info_t testcase0811_result;
			th7011_16845_test_8_1_2_result_info_t testcase0812_result;
			th7011_16845_test_8_1_3_result_info_t testcase0813_result;
			th7011_16845_test_8_1_4_result_info_t testcase0814_result;
			th7011_16845_test_8_1_5_result_info_t testcase0815_result;
			th7011_16845_test_8_1_6_result_info_t testcase0816_result;
			th7011_16845_test_8_1_7_result_info_t testcase0817_result;
			th7011_16845_test_8_1_8_result_info_t testcase0818_result;
			th7011_16845_test_8_2_1_result_info_t testcase0821_result;
			th7011_16845_test_8_2_2_result_info_t testcase0822_result;
			th7011_16845_test_8_2_3_result_info_t testcase0823_result;
			th7011_16845_test_8_2_4_result_info_t testcase0824_result;
			th7011_16845_test_8_2_5_result_info_t testcase0825_result;
			th7011_16845_test_8_2_6_result_info_t testcase0826_result;
			th7011_16845_test_8_2_7_result_info_t testcase0827_result;
			th7011_16845_test_8_2_8_result_info_t testcase0828_result;
			th7011_16845_test_8_3_1_result_info_t testcase0831_result;
			th7011_16845_test_8_3_2_result_info_t testcase0832_result;
			th7011_16845_test_8_3_3_result_info_t testcase0833_result;
			th7011_16845_test_8_3_4_result_info_t testcase0834_result;
			th7011_16845_test_8_4_1_result_info_t testcase0841_result;
			th7011_16845_test_8_4_2_result_info_t testcase0842_result;
			th7011_16845_test_8_4_3_result_info_t testcase0843_result;
			th7011_16845_test_8_4_4_result_info_t testcase0844_result;
			th7011_16845_test_8_4_5_result_info_t testcase0845_result;
			th7011_16845_test_8_5_1_result_info_t testcase0851_result;
			th7011_16845_test_8_5_2_result_info_t testcase0852_result;
			th7011_16845_test_8_5_3_result_info_t testcase0853_result;
			th7011_16845_test_8_5_4_result_info_t testcase0854_result;
			th7011_16845_test_8_5_5_result_info_t testcase0855_result;
			th7011_16845_test_8_5_6_result_info_t testcase0856_result;
			th7011_16845_test_8_5_7_result_info_t testcase0857_result;
			th7011_16845_test_8_5_8_result_info_t testcase0858_result;
			th7011_16845_test_8_5_9_result_info_t testcase0859_result;
			th7011_16845_test_8_7_1_result_info_t testcase0871_result;
			th7011_16845_test_8_7_2_result_info_t testcase0872_result;
			th7011_16845_test_8_7_4_result_info_t testcase0874_result;
			th7011_16845_test_8_8_1_result_info_t testcase0881_result;
		}result;
	}th7011_16845_test_case_result_info_t;

	TSDEV_API tsdev_api_th7011_16845_test_start(tsdev_handle_t handle, const th7011_16845_test_case_frame_data_t* test_data_input);

	/**
	* @brief Whether the test case 7.1.1 is in progress.
	* @param[in] handle pointer to tsdev handle.
	* @param[in] Percentage of tests performed, ranging from 1 to 100 .
	* @return refer to th7011_16845_test_status_t.
	*  - tsdev_th7011_16845_test_handle_invalid
	*  - tsdev_th7011_16845_test_ok
	*  - tsdev_th7011_16845_test_busy
	*  - tsdev_th7011_16845_test_call_timeout
	*/
	TSDEV_API tsdev_api_th7011_16845_test_isbusy(tsdev_handle_t handle, uint8_t* percent);

	/**
	* @brief abort the test case 7.1.1 is in progress.
	* @param[in] handle pointer to tsdev handle.
	* @return refer to th7011_16845_test_status_t.
	*  - tsdev_th7011_16845_test_handle_invalid
	*  - tsdev_th7011_16845_test_ok
	*  - tsdev_th7011_16845_test_call_timeout
	*/
	TSDEV_API tsdev_api_th7011_16845_test_current_abort(tsdev_handle_t handle);

	TSDEV_API tsdev_api_th7011_16845_test_get_result(tsdev_handle_t handle, th7011_16845_test_case_result_info_t* total_result);

	TSDEV_API tsdev_th7011_16845_test_get_wave_data(tsdev_handle_t handle, th7011_16845_test_case_wave_data_t* wave_data);

	TSDEV_API tsdev_th7011_16845_test_get_device_state(tsdev_handle_t handle, th7011_16845_test_state_t* state, th7011_16845_test_case_num_t* testcase_num);
#ifdef __cplusplus
}
#endif

#endif
