/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_DISTURB_CAN_H
#define __TSDEV_API_DISTURB_CAN_H
#include "tsdev_types.h"


#ifdef __cplusplus
extern "C"
{
#endif

    extern uint8_t IDX_API_TH7011_INIT;
    extern uint8_t IDX_API_TH7011_DISTURB;
    extern uint8_t IDX_API_TH7011_SP;
    extern uint8_t IDX_API_TH7011_SEND;
    extern uint8_t IDX_API_TH7011_STOP;
    extern uint8_t IDX_API_TH7011_PORT;
    extern uint8_t IDX_API_TH7011_SEQ;
    extern uint8_t IDX_API_TH7011_QUERY;

    typedef enum {
        tsdev_disturb_arbit_baudrate_125k,
        tsdev_disturb_arbit_baudrate_250k,
        tsdev_disturb_arbit_baudrate_500k,
        tsdev_disturb_arbit_baudrate_1000k,
    }tsdev_disturb_arbit_baudrate_t;

    typedef enum {
        tsdev_disturb_data_baudrate_125k,
        tsdev_disturb_data_baudrate_250k,
        tsdev_disturb_data_baudrate_500k,
        tsdev_disturb_data_baudrate_1000k,
        tsdev_disturb_data_baudrate_2000k,
        tsdev_disturb_data_baudrate_4000k,
        tsdev_disturb_data_baudrate_5000k,
        tsdev_disturb_data_baudrate_8000k
    }tsdev_disturb_data_baudrate_t;

    typedef enum {
        tsdev_second_sample_point_disable = 0b0,
        tsdev_second_sample_point_enable = 0b1
    }tsdev_ssp_switch_t;

    typedef enum {
        tsdev_dominant = (0x25555555u),
        tedev_recessive = (0x15555555u)
    }tsdev_disturb_way_t;

    typedef struct {
        uint32_t SSP_switch;           //SSP_switch = tsdev_second_sample_point_enable ro SSP_switch = tsdev_second_sample_point_disable
        uint32_t ID;
        uint32_t DLC;
        uint32_t Pos;
        uint32_t Disturb_way;
        uint32_t delay_txd_l_to_rxd;    //delay Bus low level to RX
        uint32_t delay_txd_h_to_rxd;    //delay Bus high level to RX
        uint32_t rev;
    }tsdev_second_sample_point_t;


    typedef enum {
        tsdev_classic_data_frame,
        tsdev_extended_data_frame,
        tsdev_classic_remite_frame,
        tsdev_extended_remote_frame,
        tsdev_fd_data_frame,
        tsdev_fd_extended_frame,
        tsdev_user_defined
    }tsdev_frame_type_t;

    typedef struct {
        uint32_t BseID;
        uint32_t BseID_MASK;    //BseID width  = BseID_MASK width = 11:0
        uint32_t RTRorRES;
        uint32_t RTRorRES_MASK;//width = 1
        uint32_t IDE;
        uint32_t IDE_MASK;    //width = 1
        uint32_t ExrendedID;
        uint32_t ExrendedID_MASK;//width = 17:0
        uint32_t RTRorRES_EXT;
        uint32_t RTRorRES_EXT_MASK;//width = 1
    }tsdev_arbitr_field_t;

    typedef struct {
        uint32_t DataWord[16];
        uint32_t DataWordMask[16];
    }tsdev_data_field_t;

    typedef struct {
        uint32_t R1orFDF;
        uint32_t R1orFDF_MASK;//width = 1
        uint32_t R0;
        uint32_t R0_MASK;//width = 1
        uint32_t BRS;
        uint32_t BRS_MASK;//width = 1
        uint32_t ESI;
        uint32_t ESI_MASK;//width = 1
        uint32_t DLC;
        uint32_t DLC_MASK;//width = 3:0
    }tsdev_control_feild_t;

    typedef struct {
        uint32_t SBC;
        uint32_t SBC_MASK;//width = 1
        uint32_t CRC;
        uint32_t CRC_MASK;//width = 14:0
        uint32_t CRC_DEL;
        uint32_t CRC_DEL_MASK;//width = 1
    }tsdev_crc_feild_t;

    typedef struct {
        uint32_t ACK;
        uint32_t ACK_MASK;//width = 1
        uint32_t ACK_DEL;
        uint32_t ACK_DEL_MASK;//width = 1
    }tsdev_ack_feild_t;

    typedef struct {
        uint32_t Frame_Type;
        tsdev_arbitr_field_t Arbitr_Field;
        tsdev_control_feild_t Control_Feild;
        tsdev_data_field_t Data_Field;
        tsdev_crc_feild_t Crc_Feild;
        tsdev_ack_feild_t Ack_Feild;
        uint32_t rev;
    }tsdev_first_filter_t;

    typedef enum {
        tsdev_sec_filter_off = 0b0000,
        tsdev_sec_filter0 = 0b0001,
        tsdev_sec_filter1 = 0b0010,
        tsdev_sec_filter2 = 0b0100,
        tsdev_sec_filter3 = 0b1000
    }tsdev_secon_filter_switch_t;

    typedef enum {
        tsdev_arbitrary_data,
        tsdev_control_data,
        tsdev_byte_data0,
        tsdev_byte_data1,
        tsdev_byte_data2,
        tsdev_byte_data3,
        tsdev_byte_data4,
        tsdev_byte_data5,
        tsdev_byte_data6,
        tsdev_byte_data7,
        tsdev_byte_data8,
        tsdev_byte_data9,
        tsdev_byte_data10,
        tsdev_byte_data11,
        tsdev_byte_data12,
        tsdev_byte_data13,
        tsdev_byte_data14,
        tsdev_byte_data15,
        tsdev_crc_data
    }tsdev_field_data_t;

    typedef struct {
        uint32_t BseID[2];
        uint32_t RTRorRES[2];
        uint32_t IDE[2];
        uint32_t ExrendedID[2];
        uint32_t RTRorRES_EXT[2];
    }tsdev_secon_arbitr_field_t;

    typedef struct {
        uint32_t R1orFDF[2];
        uint32_t R0[2];
        uint32_t BRS[2];
        uint32_t ESI[2];
        uint32_t DLC[2];
    }tsdev_secon_control_feild_t;

    typedef struct {
        uint8_t DataWord[2];
        uint8_t rev[6];
    }tsdev_secon_data_field_t;

    typedef struct {
        uint32_t SBC[2];
        uint32_t CRC[2];
        uint32_t CRC_DEL[2];
    }tsdev_secon_tsdev_crc_feild_t;

    typedef struct {
        tsdev_secon_arbitr_field_t Arbitr_Field;
        tsdev_secon_control_feild_t Control_Feild;
        tsdev_secon_data_field_t Data_Field;
        tsdev_secon_tsdev_crc_feild_t Crc_Feild;
    }tsdev_secon_frame_field_t;

    typedef struct {
        uint32_t Frame_Type;//tsdev_secon_filter_switch_t
        uint32_t Field_data;//tsdev_field_data_t
        tsdev_secon_frame_field_t Frame_field;
    }tsdev_second_filter_t;

    typedef struct {
        uint32_t Secon_filter_switch;
        tsdev_second_filter_t Second_filter0;
        tsdev_second_filter_t Second_filter1;
        tsdev_second_filter_t Second_filter2;
        tsdev_second_filter_t Second_filter3;
        uint32_t rev;
    }tsdev_second_layer_filter_t;

    typedef enum {
        tsdev_open_tx_disable = 0b0,
        tsdev_open_tx_enable = 0b1
    }Open_Tx_t;

    typedef enum {
        tsdev_sel_edge_disable = 0b0,
        tsdev_sel_edge_enble = 0b1
    }Sel_edge_t;

    typedef enum {
        tsdev_sel_disturb_error_disable = 0b0,
        tsdev_sel_disturb_error_enable = 0b1
    }sel_disturb_error_t;

    typedef enum {
        tsdev_missbit_trigger_disable = 0b0,
        tsdev_missbit_trigger_enable = 0b1
    }MissBit_trigger_t;

    typedef enum {
        tsdev_filter_n_disable = 0b0,
        tsdev_filter_n_enable = 0b1
    }Filter_n_t;

    typedef enum {
        tsdev_both = 0b00,
        TX = 0b01,
        RX = 0b10
    }Disturb_dir_t;

    typedef enum {
        Data = 0b00,
        Stuff = 0b01,
        Sof = 0b10,
        Error_bit0 = 0b11,
    }Disturb_bit_t;

    typedef struct {
        uint32_t Open_Tx;//Open_Tx_t
        uint32_t Sel_edge;//Sel_edge_t
        uint32_t sel_disturb_error;//sel_disturb_error_t
        uint32_t MissBit_trigger;//MissBit_trigger_t
        uint32_t Filter_n;//Filter_n_t
        uint32_t Disturb_dir;//Disturb_dir_t
        uint32_t Disturb_bit;// Disturb_bit_t 
        uint32_t rev;
    }tsdev_disturb_control_t;



    typedef struct {
        uint32_t Cycles;
        uint32_t Cycles_hold;
        uint32_t Repetitions;
        uint32_t Repetitions_hold;
        uint32_t Precession;
        uint32_t Length;
        uint32_t Disturb_sequence[20];   //tsdev_disturb_way_t
        //uint32_t rev;
    }tsdev_disturb_mod_t;


    typedef enum {
        tsdev_sof_filed_flag,
        tsdev_arbitrary_field_flag,
        tsdev_control_field_flag,
        tsdev_data_field_flag,
        tsdev_crc_field_flag,
        tsdev_ack_field_flag,
        tsdev_eof_field_flag,
        tsdev_interframe_flag,
        tsdev_error_field_flag
    }tsdev_frame_field_t;

    typedef enum {
        tsdev_SOF_flag,
        tsdev_IDBase_flag,
        tsdev_RemoteBase_flag,
        tsdev_IDEx_flag,
        tsdev_IDExtended_flag,
        tsdev_RemoteExtended_flag,
        tsdev_FDF_flag,
        tsdev_Reserved_flag,
        tsdev_BRS_flag,
        tsdev_ESI_flag,
        tsdev_DLC_flag,
        tsdev_DataByte0_flag,
        tsdev_DataByte1_flag,
        tsdev_DataByte2_flag,
        tsdev_DataByte3_flag,
        tsdev_DataByte4_flag,
        tsdev_DataByte5_flag,
        tsdev_DataByte6_flag,
        tsdev_DataByte7_flag,
        tsdev_DataByte8_flag,
        tsdev_DataByte9_flag,
        tsdev_DataByte10_flag,
        tsdev_DataByte11_flag,
        tsdev_DataByte12_flag,
        tsdev_DataByte13_flag,
        tsdev_DataByte14_flag,
        tsdev_DataByte15_flag,
        tsdev_DataByte16_flag,
        tsdev_DataByte17_flag,
        tsdev_DataByte18_flag,
        tsdev_DataByte19_flag,
        tsdev_DataByte20_flag,
        tsdev_DataByte21_flag,
        tsdev_DataByte22_flag,
        tsdev_DataByte23_flag,
        tsdev_DataByte24_flag,
        tsdev_DataByte25_flag,
        tsdev_DataByte26_flag,
        tsdev_DataByte27_flag,
        tsdev_DataByte28_flag,
        tsdev_DataByte29_flag,
        tsdev_DataByte30_flag,
        tsdev_DataByte31_flag,
        tsdev_DataByte32_flag,
        tsdev_DataByte33_flag,
        tsdev_DataByte34_flag,
        tsdev_DataByte35_flag,
        tsdev_DataByte36_flag,
        tsdev_DataByte37_flag,
        tsdev_DataByte38_flag,
        tsdev_DataByte39_flag,
        tsdev_DataByte40_flag,
        tsdev_DataByte41_flag,
        tsdev_DataByte42_flag,
        tsdev_DataByte43_flag,
        tsdev_DataByte44_flag,
        tsdev_DataByte45_flag,
        tsdev_DataByte46_flag,
        tsdev_DataByte47_flag,
        tsdev_DataByte48_flag,
        tsdev_DataByte49_flag,
        tsdev_DataByte50_flag,
        tsdev_DataByte51_flag,
        tsdev_DataByte52_flag,
        tsdev_DataByte53_flag,
        tsdev_DataByte54_flag,
        tsdev_DataByte55_flag,
        tsdev_DataByte56_flag,
        tsdev_DataByte57_flag,
        tsdev_DataByte58_flag,
        tsdev_DataByte59_flag,
        tsdev_DataByte60_flag,
        tsdev_DataByte61_flag,
        tsdev_DataByte62_flag,
        tsdev_DataByte63_flag,
        tsdev_CRC_flag,
        tsdev_CRCDel_flag,
        tsdev_AckSlot_flag,
        tsdev_AckDel_flag,
        tsdev_Eof_flag,
        tsdev_Interframe_flag,
        tsdev_error_flag,
        tsdev_null_flag,
    }tsdev_frame_field_trans_s;

    typedef struct {
        uint32_t Frame_Field;// tsdev_frame_field_t
        uint32_t Pos;
        uint32_t Stuff_Pos;
        uint32_t rev;
    }tsdev_disturb_Frame_config_t;

    typedef struct {
        tsdev_disturb_mod_t Disturb_mod;
        tsdev_disturb_Frame_config_t Disturb_Frame_config;
    }tsdev_disturb_cycle_t;

    typedef enum {
        tsdev_fd_0_send_frame = 0,
        tsdev_fd_1_send_frame = 1,
        tsdev_classic_send_frame = 2
    }tsdev_tx_frame_format_t;

    struct tsdev_fd_tx_frame_config_t {
        uint32_t TX_Frame_Format;//tsdev_tx_frame_format_t
        uint32_t TX_ID;
        uint32_t TX_Date1;
        uint32_t rev;
    };

    typedef enum {
        tsdev_port_low = 0,
        tsdev_port_1,
        tsdev_port_2,
        tsdev_port_3,
    }port_num_t;

    typedef enum {
        tsdev_do_trigger_en = 1,
        tsdev_do_trigger_en_n,
        tsdev_do_can_error_flag,
    }do_port_signal_t;

    typedef enum {
        tsdev_di_message_trigger_in = 0,
    }di_port_signal_t;

    typedef struct {
        uint32_t port_num; //port_num_t
        uint32_t do_port_signal;//do_port_signal_t
    }do_port_config_t;

    typedef struct {
        uint32_t port_num;//port_num_t
        uint32_t di_port_signal;//di_port_signal_t
    }di_port_config_t;
    /************************************************/
    typedef struct {
        uint32_t Arbit_Baudrate;
        uint32_t Data_Baudrate;
        uint32_t Arbit_Samplepoint;
        uint32_t Data_Samplepoint;
    }tsdev_th7011_can_Control_t;     //16 byte

    typedef struct {
        uint32_t ID;
        uint32_t Test_times;
        uint32_t Timeout;
        uint32_t guest_arbit_sample_pos;
        uint32_t guest_data_sample_pos;
        uint32_t precession;
        uint32_t delay_bus_d_to_rx;
        uint32_t delay_bus_r_to_rx;
        tsdev_second_sample_point_t Second_sample_point;
    }tsdev_sample_point_t;

    typedef struct {
        float arbit_sample_point;
        float data_sample_point;
        float SSP_arbit_sample_point;
        float SSP_data_sample_point;
    }tsdev_sample_point_result_t;

    typedef struct {
        tsdev_first_filter_t First_Filter;
        tsdev_second_layer_filter_t Second_Layer_Filter;
        tsdev_disturb_control_t Disturb_Control;
        tsdev_disturb_cycle_t Disturb_Cycle;
    }tsdev_disturb_Frame_t;

    struct tsdev_tx_frame_config_t {
        struct tsdev_fd_tx_frame_config_t fd_tx_frame_config;
        uint32_t Count;
        uint32_t rev;
    };

    typedef struct {
        uint32_t bit_num;
        uint32_t Frame_format[20];
        uint32_t div;
    }tsdev_sequence_config_t;

    typedef struct {
        do_port_config_t do_port_config1;
        do_port_config_t do_port_config2;
        do_port_config_t do_port_config3;
        di_port_config_t di_port_config1;
    }tsdev_port_config_t;

    typedef struct {
        unsigned int times;
        unsigned int clear_flag;
    }times_query_t;

#ifdef __cplusplus
}
#endif

#endif