/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_DEV_TH7011_H
#define __TSDEV_API_DEV_TH7011_H
#include "tsdev_types.h"
#include "tsdev_api_disturb_can.h"
#include "tsdev_api_disturb_lin.h"


#ifdef __cplusplus
extern "C"
{
#endif

    /**
     * @brief config dev work mod
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] dev_mod Set Sync config zynq7000 device work mod
     * @return if 0, ok, else nok.
     *
     */
    TSDEV_API tsdev_api_disturb_dev_set_mod(tsdev_handle_t handle, th7012_dev_mod* dev_mod);

    /**
     * @brief config dev work mod
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] dev_mod get Sync zynq7000 device work mod
     * @return if 0, ok, else nok.
     *
     */
    TSDEV_API tsdev_api_disturb_dev_get_mod(tsdev_handle_t handle, th7012_dev_mod* dev_mod);

     /**
     * @delivering initialization data.
     * @param[in] handle pointer to tsdev handle.
     * @param[in] conf pointer to application layer specific data.
     * @param[in] timeout timeout in ms.
     * @return refer to tsdev_err_t.
     */
    TSDEV_API tsdev_api_disturb_can_init(tsdev_handle_t handle, const tsdev_th7011_can_Control_t* conf);

    /**
    * @sampling point test and secondary sampling point(unopen).
    * @param[in] handle pointer to tsdev handle.
    * @param[in] conf pointer to application layer specific data.
    * @param[out] sample_point_result returned test results.
    * @return refer to tsdev_err_t.
    */
	TSDEV_API tsdev_api_can_sample_point_test(tsdev_handle_t handle, const tsdev_sample_point_t* conf, tsdev_sample_point_result_t* sample_point_result);
	
    /**
    * @delivery disturb configuration.
    * @param[in] handle pointer to tsdev handle.
    * @param[in] conf pointer to application layer specific data.
    * @return refer to tsdev_err_t.
    */
    TSDEV_API tsdev_api_can_disturb_config(tsdev_handle_t handle, const tsdev_disturb_Frame_t* conf);

    /**
    * @delivery disturb configuration.
    * @param[in] handle pointer to tsdev handle.
    * @param[in] conf pointer to application layer specific data.
    * @return refer to tsdev_err_t.
    */
    TSDEV_API tsdev_api_can_disturb_config_trans(tsdev_handle_t handle, const tsdev_disturb_Frame_t* conf);

    /**
    * @delivering initialization data.
    * @param[in] handle pointer to tsdev handle.
    * @param[in] conf pointer to application layer specific data.
    * @param[in] timeout timeout in ms.
    * @return refer to tsdev_err_t.
    */
    TSDEV_API tsdev_api_send_can_frame(tsdev_handle_t handle, struct tsdev_tx_frame_config_t* conf);

    /**
    * @delivering frame sequence configuration data.
    * @param[in] handle pointer to tsdev handle.
    * @param[in] conf pointer to application layer specific data.
    * @return refer to tsdev_err_t.
    */
    TSDEV_API tsdev_api_send_can_sequence(tsdev_handle_t handle, tsdev_sequence_config_t* conf);

    /**
    * @delivering configuration of port data.
    * @param[in] handle pointer to tsdev handle.
    * @param[in] conf pointer to application layer specific data.
    * @return refer to tsdev_err_t.
    */
    TSDEV_API tsdev_api_can_port_config(tsdev_handle_t handle, tsdev_port_config_t* conf);

    /**
    * @delivering stop jamming command data.
    * @param[in] handle pointer to tsdev handle.
    * @param[in] conf pointer to application layer specific data.
    * @return refer to tsdev_err_t.
    */
    TSDEV_API tsdev_api_can_stop(tsdev_handle_t handle);

    /**
    * @Query Result.
    * @param[in] handle pointer to tsdev handle.
    * @param[out] times returns the result of the number of queries.
    * @return refer to tsdev_err_t.
    */
    TSDEV_API tsdev_api_can_query(tsdev_handle_t handle, times_query_t * times_query);

    /*****************************************DISTURB_LIN*****************************************************/

    /**
         * @brief th7012 init
         * @param[in] handle pointer to tsdev api handle.
         * @param[in] timeout_ms Set Sync Request TimeOut [uint]:ms
         * @return if 0, ok, else nok.
         *
         */
    TSDEV_API tsdev_api_lin_init(tsdev_handle_t handle,
        uint32_t timeout);

    /**
     * @brief uninit th7012
     * @param[in] handle pointer to tsdev api handle.
     * @return if 0, ok, else nok.
     * @note
    */
    TSDEV_API tsdev_api_lin_uninit(tsdev_handle_t handle);

    /**
     * @brief Only read th7012 0x43c00000~0x43cfffff space value,which is fpga logic control
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] Addr register addr
     * @param[out] rdata data pointer
     * @return if 0, ok, else nok.
     * @note
    */
    TSDEV_API tsdev_api_lin_read_word(tsdev_handle_t handle, uint32_t Addr, uint32_t* rdata);

    /**
     * @brief Only write th7012 0x43c00000~0x43cfffff space,which is fpga logic control
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] Addr register addr
     * @param[in] wdata write to register value,which is 32bit
     * @return if 0, ok, else nok.
     * @note
    */
    TSDEV_API tsdev_api_lin_write_word(tsdev_handle_t handle, uint32_t Addr, uint32_t wdata);

    /**
     * @brief Only write th7012 0x43c00000~0x43cfffff space,which is fpga logic control
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] Addr register addr
     * @param[in] wdata write to register value,which is 16bit
     * @return if 0, ok, else nok.
     * @note
    */
    TSDEV_API tsdev_api_lin_write_halfword(tsdev_handle_t handle, uint32_t Addr, uint16_t wdata);

    /**
     * @brief Only write th7012 0x43c00000~0x43cfffff space,which is fpga logic control
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] Addr register addr
     * @param wdata write to register value,which is 8bit
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_write_byte(tsdev_handle_t handle, uint32_t Addr, uint8_t wdata);

    /**
     * @brief Read zynq linux application verison
     * @param[in] handle pointer to tsdev api handle.
     * @param[out] version data pointer
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_version(tsdev_handle_t handle, uint32_t* version);

    /**
     * @brief Control th7012 LIN MAC reset
     * @param[in] handle pointer to tsdev api handle.
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_pl_reset(tsdev_handle_t handle);

    /**
     * @brief init th7012 Lin Mac basic config
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] lin_config Lin Mac basic config struct,which is include Lin bps every segment delay
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_basic_config(tsdev_handle_t handle, th7012_lin_segment_config* lin_config);

    /**
     * @brief th7012 Lin Mode config
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] mode this parameter can set Master&Slave Mode,Lin Header Type,Disturbe Mode...
     * @param[in] mode_mask Mode parameter Mask,which can enable mode setting
     * @param[in] send_pid setting send pid
     * @param[in] recv_pid setting recv trigger pid
     * @param[in] recv_pid_mask setting recv_pid enable bit
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_mode_config(tsdev_handle_t handle, uint32_t mode, uint32_t mode_mask, uint32_t send_pid, uint32_t recv_pid, uint32_t recv_pid_mask);

    /**
     * @brief th7012 Lin packet data transmit
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] lin_data This structure pointer points to a specific LIN message.
     * @param[in] wait If the value of "wait" is true, the sending mode is synchronous mode;
     *                  if the value of "wait" is false, the sending mode is asynchronous mode.
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_tx(tsdev_handle_t handle, th7012_lin_transmit_data* lin_data, uint8_t wait);

    /**
     * @brief th7012 transmit finish query
     * @param[in] handle pointer to tsdev api handle.
     * @param[out] send_finish send_finish pointer,if the value of pointer is 0,last packet send finish
     *                          if the value of pointer is 1,last packet is sending
     *                          if the value of pointer is other value ,last packet is timeout or error
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_tx_query(tsdev_handle_t handle, uint32_t* send_finish);

    /**
     * @brief control Lin bus short to Vbat or GND
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] ctr_code if the value of ctr_code is 0,normal mode
     *                      if the value of ctr_code is 1,the Lin wire short to Vbat
     *                      if the value of ctr_code is 2,the Lin wire short to GND
     * @param[in] short_time setting shortcircuit time unit[1s]
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_short_ctr(tsdev_handle_t handle, uint32_t ctr_code, uint32_t short_time);

    /**
     * @brief setting coverage packet specific infomation
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] sync Lin packet Sync segement value
     * @param[in] pid Lin packet pid segement value
     * @param[in] len Lin packet Data field length
     * @param[in] lin_data the value of Lin Data
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_coverage_config(tsdev_handle_t handle, uint8_t sync, uint8_t pid, uint8_t len, uint8_t* lin_data);

    /**
     * @brief setting packet invert
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] lin_field setting specific LIN Packet Filed
     * @param[in] bitchoose setting specific LIN Packet bit
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_invert_config(tsdev_handle_t handle, tsdev_disturb_invert_lin_field lin_field, uint8_t bitchoose);

    /**
     * @brief setting Lin Packet Disturb
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] lin_field Set the starting field in the LIN Packet for disturb.
     * @param[in] bit Set the starting bit in the LIN Packet for disturb.
     * @param[in] high_or_low If high_or_low is 0, it means setting the LIN bus to a low level during disturb.
     *                          If high_or_low is 1, it means setting the LIN bus to a high level during disturb.
     * @param disturb_time disturb duration unit[25ns]
     * @param disturb_num Number of disturb
     * @return if 0, ok, else nok.
     * @note th7012 will disturb next bit
    */
    TSDEV_API tsdev_api_lin_disturb_config(tsdev_handle_t handle, tsdev_disturb_disturb_lin_field lin_field, uint8_t bit, uint8_t high_or_low, uint32_t disturb_time, uint32_t disturb_num);

    /**
     * @brief sample_point_test
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] lin_config Lin Mac basic config struct,which is include Lin bps every segment delay
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_sample_point_test(tsdev_handle_t handle, th7012_lin_segment_config_sp* lin_sp, th7012_sample_point* sp, uint8_t test_times); //3

    /**
     * @brief measure field timing
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] lin_config Lin Mac basic config struct,which is include Lin bps every segment delay
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_measure(tsdev_handle_t handle, th7012_lin_field_timing* field_timing);

    /**
     * @brief measure field timing
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] dif_time The time difference between two synchronization intervals
     * @param[in] timeout The test time out unit[1s]
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_break_del_time(tsdev_handle_t handle, uint64_t* dif_time, int timeout);

    /**
     * @brief control disturb
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] ctr if the value of ctr is 0,Stop disturb
     *                  if the value of ctr is 1,Start disturb
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_disturb_ctrl(tsdev_handle_t handle, uint8_t ctr);


    /**
     * @brief register Lin Packet recv callback
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] usr_arg user arg
     * @param[in] EventFunc callback function
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_recv_event_register(tsdev_handle_t handle, void* usr_arg, const tsdev_th7012_lin_recv EventFunc);

    /**
     * @brief unregister Lin Packet recv callback
     * @param[in] handle pointer to tsdev api handle.
     * @param[in] usr_arg user arg
     * @param[in] EventFunc callback function
     * @return if 0, ok, else nok.
    */
    TSDEV_API tsdev_api_lin_recv_event_unregister(tsdev_handle_t handle, void* usr_arg, const tsdev_th7012_lin_recv EventFunc);
                                          

#ifdef __cplusplus
}
#endif

#endif