/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_TA1015_H
#define __TSDEV_API_TA1015_H
#include "tsdev_types.h"
// Upstream renamed/isolated type declarations into *_types.h; include it so
// the callback typedefs (e.g. tsdev_arinc429_tx_cmd_event_t) are visible here.
#include "tsdev_api_ta1015_types.h"

#ifdef __cplusplus
extern "C"
{
#endif
#include <stdint.h>	
    // ----------------------------------------------------------arinc429------------------------------------------------ -
    // arinc429 api
    TSDEV_API tsdev_api_arinc429_send_tx_cmd_req(tsdev_handle_t handle, const struct tsdev_arinc429_tx_cmd_req_rsp_t* tx_cmd);
    TSDEV_API tsdev_api_arinc429_send_rx_cmd_req(tsdev_handle_t handle, const struct tsdev_arinc429_rx_cmd_req_rsp_t* rx_cmd);
    TSDEV_API tsdev_api_arinc429_tx_frm(tsdev_handle_t handle, const struct tsdev_arinc429_frm_tx_t* tx_frm);

    // arinc429 callback func
    TSDEV_API tsdev_api_arinc429_tx_cmd_reg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_arinc429_tx_cmd_event_t event);
    TSDEV_API tsdev_api_arinc429_tx_cmd_unreg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_arinc429_tx_cmd_event_t event);
    TSDEV_API tsdev_api_arinc429_tx_cmd_unreg_events(tsdev_handle_t handle);

    TSDEV_API tsdev_api_arinc429_rx_cmd_reg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_arinc429_rx_cmd_event_t event);
    TSDEV_API tsdev_api_arinc429_rx_cmd_unreg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_arinc429_rx_cmd_event_t event);
    TSDEV_API tsdev_api_arinc429_rx_cmd_unreg_events(tsdev_handle_t handle);

    TSDEV_API tsdev_api_arinc429_frm_done_reg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_arinc429_frm_done_event_t event);
    TSDEV_API tsdev_api_arinc429_frm_done_unreg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_arinc429_frm_done_event_t event);
    TSDEV_API tsdev_api_arinc429_frm_done_unreg_events(tsdev_handle_t handle);

    // ----------------------------------------------------------1553B-------------------------------------------------
    // 1553B api
    TSDEV_API tsdev_api_1553B_cmd_req(tsdev_handle_t handle, const struct tsdev_mil1553b_cmd_req_rsp_t* req_cmd);
    TSDEV_API tsdev_api_1553B_frm_tx(tsdev_handle_t handle, const struct tsdev_mil1553b_frm_tx_t* tx_frm);

    // 1553B callback func
    TSDEV_API tsdev_api_1553B_cmd_reg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_1553B_cmd_event_t event);
    TSDEV_API tsdev_api_1553B_cmd_unreg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_1553B_cmd_event_t event);
    TSDEV_API tsdev_api_1553B_cmd_unreg_events(tsdev_handle_t handle);

    TSDEV_API tsdev_api_1553B_frm_done_reg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_1553B_frm_done_event_t event);
    TSDEV_API tsdev_api_1553B_frm_done_unreg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_1553B_frm_done_event_t event);
    TSDEV_API tsdev_api_1553B_frm_done_unreg_events(tsdev_handle_t handle);

    // ----------------------------------------------------------uart-------------------------------------------------
    // uart api
    TSDEV_API tsdev_api_uart_cmd_req(tsdev_handle_t handle, const struct tsdev_uart_cmd_req_rsp_t* req_cmd);
    TSDEV_API tsdev_api_uart_frm_tx(tsdev_handle_t handle, const struct tsdev_uart_frm_tx_t* tx_frm);

    // uart callback func
    TSDEV_API tsdev_api_uart_cmd_reg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_uart_cmd_event_t event);
    TSDEV_API tsdev_api_uart_cmd_unreg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_uart_cmd_event_t event);
    TSDEV_API tsdev_api_uart_cmd_unreg_events(tsdev_handle_t handle);

    TSDEV_API tsdev_api_uart_frm_done_reg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_uart_frm_done_event_t event);
    TSDEV_API tsdev_api_uart_frm_done_unreg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_uart_frm_done_event_t event);
    TSDEV_API tsdev_api_uart_frm_done_unreg_events(tsdev_handle_t handle);

#ifdef __cplusplus
}
#endif

#endif
