/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_BASE_TYPES_H
#define __TSDEV_API_BASE_TYPES_H

#include <stdint.h>

enum _tsdev_err_t {
	tsdev_err_ok,
	tsdev_err_nok = -1,
	tsdev_err_timeout = -2,
	tsdev_err_handle_internal_err = -3,
	tsdev_err_invalid_param = -4,
	tsdev_err_invalid_com_type = -5,
	tsdev_err_invalid_handle = -6,
	tsdev_err_device_not_found = -7,
	tsdev_err_index_out_of_range = -8,
	tsdev_err_invalid_uid = -9,
	tsdev_err_netif_invalid_name = -10,
	tsdev_err_firmware_outdated = -11,
	tsdev_err_connect_timeout = -12,
	tsdev_err_fail = -13,
	tsdev_err_sys_not_support = -14,
	tsdev_err_fun_not_support = -15,
	tsdev_err_is_busy = -16,
	tsdev_err_not_open = -17,
	tsdev_err_device_verify_fail = -18,
};
typedef int32_t tsdev_err_t; // use enum _tsdev_err_t


typedef enum {
	tsdev_ch0 = 0,
	tsdev_ch1,
	tsdev_ch2,
	tsdev_ch3,
	tsdev_ch4,
	tsdev_ch5,
	tsdev_ch6,
	tsdev_ch7,
	tsdev_ch8,
	tsdev_ch9,
	tsdev_ch10,
	tsdev_ch11,
	tsdev_ch12,
	tsdev_ch13,
	tsdev_ch14,
	tsdev_ch15,
	tsdev_ch16,
	tsdev_ch17,
	tsdev_ch18,
	tsdev_ch19,
	tsdev_ch20,
	tsdev_ch21,
	tsdev_ch22,
	tsdev_ch23,
	tsdev_ch24,
	tsdev_ch25,
	tsdev_ch26,
	tsdev_ch27,
	tsdev_ch28,
	tsdev_ch29,
	tsdev_ch30,
	tsdev_ch31,
} tsdev_channel_idx_t;


typedef enum {
	tsdev_log_trace = 0,
	tsdev_log_debug,
	tsdev_log_info,
	tsdev_log_warn,
	tsdev_log_err,
	tsdev_log_critical,
	tsdev_log_lvls
} tsdev_log_lvl_t;

enum tsdev_com_t {
    tsdev_com_none = 0,
    tsdev_com_eth = 1,
    tsdev_com_tcp = 2,
    tsdev_com_canfd = 3,//not support
    tsdev_com_usb = 4,
    tsdev_com_serial = 5,//not support
    tsdev_com_pcie = 6,//not support
    tsdev_com_local = 7,
    tsdev_com_ethercat = 8,//not support

	tsdev_com_local_rt = 9,
	tsdev_com_tcp_rt = 10,
    tsdev_com_ethercat_rt = 11,
    tsdev_com_pcie_rt = 12,//not support
	tsdev_com_usb_rt = 13,
};

#define tsdev_UID_LEN (8)

#ifdef __CPPUTEST__
#define TSDEV_API   tsdev_err_t 
#elif defined __GNUC__ || defined LIBTSDEVBASERT_EXPORTS
#define TSDEV_API   tsdev_err_t 
#else
#ifdef LIBTSDEVBASE_EXPORTS
#define TSDEV_API __declspec(dllexport) tsdev_err_t 
#else
#define TSDEV_API __declspec(dllimport) tsdev_err_t 
#endif
#endif

typedef void* tsdev_handle_t;
typedef void* tsdev_tsmsg_t;

typedef tsdev_err_t(*tsdev_tsmsg_receive_callback_t)(tsdev_handle_t handle, void* usr_arg,
	tsdev_tsmsg_t msg,
	const void* header,
	uint8_t* data);
typedef tsdev_err_t(*tsdev_tsmsg_type_receive_callback_t)(tsdev_handle_t handle, void* usr_arg
	, tsdev_tsmsg_t msg,
	const void* header,
	uint8_t* data);
typedef tsdev_err_t(*tsdev_tsmsg_fdid_receive_callback_t)(tsdev_handle_t handle, void* usr_arg
	, tsdev_tsmsg_t msg,
	uint16_t fdid, uint16_t fsize,
	uint8_t* data);
typedef tsdev_err_t(*tsdev_tsmsg_common_service_receive_callback_t)(tsdev_handle_t handle, void* usr_arg
	, tsdev_tsmsg_t msg
	, uint16_t FCommand, uint8_t  FStatus, uint8_t  FProgramState, uint32_t FDataCnt
	, uint8_t* data);


typedef tsdev_err_t(*tsdev_api_server_custom_callback_t)(
	tsdev_handle_t handle, void* usr_arg, uint16_t server_idx, uint16_t rpc_cmd, uint8_t cnt, const uint8_t* par, uint16_t par_len);



struct tsdev_dev_w_config_t
{
	uint8_t clk_type; //0: default clk; 1: ptp clk
	uint8_t rev[7];
};

struct tsdev_dev_r_config_t
{
	uint8_t clk_type; //0: default clk; 1: ptp clk
	uint8_t rev0;
	uint16_t default_clk_mhz;
	uint16_t ptp_clk_mhz;
	uint8_t rev[2];
};

// NOTE: init to zeros before using it.
struct tsdev_device_settings_t
{
	uint8_t version;
	uint8_t rev[7];
	union tsdev_device_settings_pars_t
	{
		uint8_t rev[1000];
		struct tsdev_device_settings_v0_t
		{
			/**
			 * USB High Speed endpoint bInterval (valid only when com type is USB)
			 * 1 - 16, 0 - ignore
			 * real interval time = 2^(usb_hs_interval-1) * 125us
			 */
			uint8_t usb_hs_interval;
			/**
			 * USB Super Speed endpoint bInterval (valid only when com type is USB)
			 * 1 - 16, 0 - ignore
			 * real interval time = usb_ss_interval * 125us
			 */
			uint8_t usb_ss_interval;
			/**
			 * clock source for timestamp, valid only when multiple clocks are supported
			 * 0: default clk
			 * 1: ptp clk
			 * 2: tsync box clk
			 */
			uint8_t timestamp_clk_src;
		} v0;
	} pars;
};

struct tsdev_info_t {
	struct tsdev_basic_info_t {
		/** enum tsdev_devtype_t */
		uint16_t dev_type;
		/**
		 * [0-3]: com type
		 * [5 - 7]: rev
		 */
		uint8_t align;
		uint8_t hw_pos_id; 
		uint8_t rev[4]; //var add 2024-8-16
	} basic_info;
	uint8_t uid[8];
};


#endif