/*
Copyright (c) 2024:Shanghai TOSUN Technology Ltd.

The software mentioned in this copyright statement includes the automatic code generator function module of TSMaster software and the embedded code it generates. Among them, the copyright of the automatic code generation function module of TSMaster software is owned by Shanghai TOSUN Technology Ltd..It is protected by the Copyright Law of the People's Republic of China, the Regulations on the Protection of Computer Software, the Intellectual Property Protection Law, the Patent Law of the People's Republic of China and relevant international copyright treaties, laws, regulations, and other intellectual property laws and treaties.

The embedded code generated by the automatic code generation function of the TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN Technology Ltd. or the original copyright owner of the embedded code, and is only for personal learning and use. Shanghai TOSUN Technology Ltd. does not provide any kind of warranty, whether express or implied. All risks are borne by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint responsibility.

The semiconductor manufacturer's LOGO and product model displayed in the TSMaster are only for the convenience of user selection and useage,its copyright and ownership remain with the respective copyright owners,Shanghai TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for this, and does not assume joint and several liability for any possible infringement.

Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the software mentioned in this copyright statement without notifying users, and reserves the right to modify this license agreement.
*/
#ifndef TSDEV_USR_MODULE_H
#define TSDEV_USR_MODULE_H

#include <stddef.h>
#include "tsdev_usr_module_types.h"

#ifdef _MSC_VER
#define TSDEV_USR_API __declspec(dllexport)
#else
#define TSDEV_USR_API
#endif

#ifdef __cplusplus
extern "C"
{
#endif
#ifndef LIBTSDEVBASERT_EXPORTS
	//-----------------------------call by RTTSMaster, ignore by usr----------------------------------
	extern void* host_data_ptr;
	extern size_t host_data_size;
	TSDEV_USR_API int8_t tsdev_api_version(uint8_t* main_v, uint8_t* mid_v, uint8_t* sub_v, const char** gen_time);
	TSDEV_USR_API int8_t tsdev_usr_module_init(void** module_ctx);
	TSDEV_USR_API void tsdev_usr_module_uninit(void* module_ctx);
	TSDEV_USR_API int8_t tsdev_usr_module_get_core_cnt(void* module_ctx, uint8_t* cnt_p);
	TSDEV_USR_API int8_t tsdev_usr_module_create_core(void* module_ctx, uint8_t core_idx, tsdev_usr_core_handle_t* core_handle);
	TSDEV_USR_API void tsdev_usr_module_destroy_core(void* module_ctx, tsdev_usr_core_handle_t core_handle);
	TSDEV_USR_API int8_t tsdev_usr_module_update_method(void* module_ctx, tsdev_usr_core_handle_t core_handle, void* host_data_ptr, size_t host_data_size, uint16_t method_cnt, const struct tsdev_usr_module_fun* methods_p);
	TSDEV_USR_API int8_t tsdev_usr_module_get_core_callback(void* module_ctx, tsdev_usr_core_handle_t core_handle, uint8_t task_idx, const char** name_pp, uint16_t* sch_prescaler
		, uint16_t exp_callback_cnt, struct tsdev_usr_module_fun* exp_callbacks_p);
	TSDEV_USR_API int8_t tsdev_usr_module_get_sig_cnt(void* module_ctx, tsdev_usr_core_handle_t core_handle, uint32_t* cnt_p);
	TSDEV_USR_API int8_t tsdev_usr_module_get_sig_defs_ptr(void* module_ctx, tsdev_usr_core_handle_t core_handle, struct tsdev_cal_sig_def_t** sig_defs);
	//--------------------------------call by usr--------------------------------------------------------
	extern tsdev_err_t(*tsdev_api_log_out)(tsdev_handle_t handle, tsdev_log_lvl_t lvl, const char* msg);
	extern void* (*tsdev_api_malloc)(size_t size);
	extern void  (*tsdev_api_free)(void* ptr);
	extern tsdev_err_t(*tsdev_api_get_device_cnt)(tsdev_handle_t handle, uint16_t* cnt);
	extern tsdev_err_t(*tsdev_api_get_device_handle)(tsdev_handle_t handle, uint16_t idx, tsdev_handle_t* dev_handle_p, struct tsdev_info_t* info_p);
	extern tsdev_err_t(*tsdev_api_can_configure_regs_async)(tsdev_handle_t dev_handle, const struct tsdev_TPC_FDHardwareConf* conf);
	extern tsdev_err_t(*tsdev_api_can_transmit_async)(tsdev_handle_t dev_handle, const struct tsdev_canfd_tx_t* can);
	extern tsdev_err_t(*tsdev_api_can_frame_receive)(tsdev_handle_t handle, void* usr_arg, uint32_t max_rx_cnt, tsdev_can_frame_event_t event);
	extern tsdev_err_t(*tsdev_api_eth_tx_cmd_async)(tsdev_handle_t handle, const struct tsdev_PC_ETH_CMD_REQ* ACmdReq);
	extern tsdev_err_t(*tsdev_api_eth_transmit_async)(tsdev_handle_t handle, const struct tsdev_ETH_Header* AEthernetHeader);
	extern tsdev_err_t(*tsdev_api_eth_fifo_receive_msgs)(tsdev_handle_t handle, void* usr_arg, uint32_t max_rx_cnt, tsdev_api_eth_frame_event_t frame_handle);
	extern tsdev_err_t(*tsdev_api_flexray_set_controller_frametrigger)(tsdev_handle_t handle, const struct tsdev_TPC_FlexrayConfig* config);
	extern tsdev_err_t(*tsdev_api_flexray_cmdreq)(tsdev_handle_t handle, const struct tsdev_TPC_FlexrayCmdReq* req);
	extern tsdev_err_t(*tsdev_api_flexray_start_net)(tsdev_handle_t handle, int32_t node_idx);
	extern tsdev_err_t(*tsdev_api_flexray_stop_net)(tsdev_handle_t handle, int32_t node_idx);
	extern tsdev_err_t(*tsdev_api_flexray_wakeup_pattern)(tsdev_handle_t handle, int32_t node_idx);
	extern tsdev_err_t(*tsdev_api_flexray_transmit_async)(tsdev_handle_t handle, const struct tsdev_flexray_frame* AData);
	extern tsdev_err_t(*tsdev_api_io_cmd_async)(tsdev_handle_t handle, const union tsdev_dev_io_cmd_resp* cmd);
	extern tsdev_err_t(*tsdev_api_lin_config)(tsdev_handle_t handle, struct tsdev_lin_config_t* cmd);
	extern tsdev_err_t(*tsdev_api_lin_transmit_async)(tsdev_handle_t handle, const struct tsdev_LIN_frame* lin);
	extern tsdev_err_t(*tsdev_api_lin_fifo_receive_msgs)(tsdev_handle_t handle, void* usr_arg, uint32_t max_rx_cnt, const tsdev_lin_frame_event_t event);
	extern tsdev_err_t(*tsdev_api_sim_sig_get_cnt)(tsdev_handle_t handle, uint8_t core_idx, uint32_t* cnt);
	extern tsdev_err_t(*tsdev_api_sim_sig_get_defs)(tsdev_handle_t handle, uint8_t core_idx, uint32_t sig_start_idx, uint32_t read_cnt, struct tsdev_cal_sig_def_t* sig_defs);
	extern tsdev_err_t(*tsdev_api_sim_core_current)(tsdev_handle_t handle, uint8_t* core_idx);
	extern tsdev_err_t(*tsdev_api_sim_dp_group_fifo_receive_msgs)(tsdev_handle_t handle, void* usr_arg, uint32_t max_rx_cnt, tsdev_api_dp_group_event_t event_handle);
	//----------------------------callback is define in struct sim_callbacks at tsdev_usr_module_types.h-----------------------
#endif
#ifdef __cplusplus
}
#endif

#endif // _UDS_APP_IF_H
