/**
 * Copyright (c) 2025:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_CAN_UDS_H__
#define __TSDEV_API_CAN_UDS_H__
#include "tsdev_types.h"
#include "tsdev_api_can_uds_types.h"

#ifdef __cplusplus
extern "C"
{
#endif

    /**
     * @brief Apply new thread for CAN UDS according to apply info.
     * @param[in] handle device's handle
     * @param[in] info_p CAN UDS apply info
     * @param[out] thread_handle_p pointer to CAN UDS thread handle
     * @param[in] timeout_ms timeout in milliseconds
     * @return tsdev_err_t
     */
    TSDEV_API tsdev_api_can_uds_apply(tsdev_handle_t handle, const struct tsdev_can_uds_apply_info_t *info_p,
                                      uint64_t *thread_handle_p, uint32_t timeout_ms);

    /**
     * @brief Configure CAN UDS according to config info.
     * @param[in] handle device's handle
     * @param[in] thread_handle CAN UDS thread handle
     * @param[in] conf_p CAN UDS config info
     * @param[in] timeout_ms timeout in milliseconds
     * @return tsdev_err_t
     */
    TSDEV_API tsdev_api_can_uds_config(tsdev_handle_t handle, uint64_t thread_handle,
                                       const struct tsdev_can_uds_config_t *conf_p, uint32_t timeout_ms);

    /**
     * @brief Release CAN UDS thread.
     * @param[in] handle device's handle
     * @param[in] thread_handle CAN UDS thread handle
     * @param[in] timeout_ms timeout in milliseconds
     * @return tsdev_err_t
     */
    TSDEV_API tsdev_api_can_uds_release(tsdev_handle_t handle, uint64_t thread_handle, uint32_t timeout_ms);
    /**
     * @brief Send CAN UDS request
     * @param handle device's handle
     * @param thread_handle CAN UDS handle
     * @param is_function is function frame id
     * @param data_p pointer to data
     * @param data_len data length
     * @return tsdev_err_t
     */
    TSDEV_API tsdev_api_can_uds_transmit(tsdev_handle_t handle, uint64_t thread_handle, uint8_t is_function,
                                         const uint8_t *data_p, uint16_t data_len);
    /**
     * CAN UDS receive
     * @param handle device's handle
     * @param max_cnt max count to receive UDS messages in one call
     * @param cb callback
     * @return tsdev_err_t
     */
    TSDEV_API tsdev_api_can_uds_receive(tsdev_handle_t handle, uint32_t max_cnt, can_uds_message_callback_t cb);

#ifdef __cplusplus
}
#endif

#endif