/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_IO_TTS8018_H
#define __TSDEV_API_IO_TTS8018_H

#include "tsdev_types.h"
#include "tsdev_api_io_tts_common.h"
#ifdef __cplusplus
extern "C"
{
#endif




//TTS8018
union tsdev_dev_tts8018_io_cmd_resp {
    uint8_t rev[8];
    //all fealtures
    struct tsdev_dev_all_cmd0_resp0 {
        uint8_t  cmd;                  //tsdev_dev_io_cmd_enum
        uint8_t  dev_type;              // Board ID
        uint16_t ao_mode[16];          // 16-channel analog output voltage
        uint16_t  ao_enable;           // Output enable: 0=disable internal output, 1=enable internal output
        uint16_t ao_com;               // Output connected to external pin
        uint16_t ao_gnd;               // Output connected to GND
        uint16_t ao_bat;               // Output connected to BAT
        uint16_t ao_ch_mode;               // Channel mode: 0=disconnected, 1=latched
        uint16_t ai_com;               // Input connected to external pin
        uint16_t ai_gnd;               // Input connected to GND
        uint16_t ai_bat;               // Input connected to BAT
        uint16_t ai_ch_mode;               // Channel mode
    }tts8018_init_setup;

    //common feature 
    tts_cmd3_resp3   aiao_vol_lvl_out;    //aiao_vol_lvl_out 
    tts_cmd3_resp3   aiao_vol_lvl_in;     //aiao_vol_lvl_in
    tts_cmd9_resp9   aiao_voltage_write;  // Voltage output
    tts_cmd9_resp9 aiao_voltage_read;   // Voltage measurement
    tts_cmd10_resp10 ai_channle_mode; //tsdev_dev_tts_ai_ch_mode_set
    tts_cmd10_resp10 ao_channle_mode; //tsdev_dev_tts_ao_ch_mode_set
};

// max 16 channels
union tsdev_dev_io_tts8018_daq_resp {
    uint8_t rev[1024];
    struct tsdev_dev_tts_aiao_resp3 {
        uint64_t timestamp;
        uint8_t cmd;	                //tsdev_dev_io_tts_cmd_enum
        uint8_t cnt;                    // rolling cnt
        uint16_t vol_mv[16];           //
    }ai_status;

    struct tsdev_dev_tts_aiao_resp4 {
        uint64_t timestamp;
        uint8_t cmd;	                //tsdev_dev_io_tts_cmd_enum
        uint8_t cnt;                    // rolling cnt
        uint16_t vol_mv[16];           //
    }ao_status;
};

typedef tsdev_err_t(*tsdev_io_tts8018_cmd_event_t)(tsdev_handle_t handle, void* usr_arg, tsdev_tsmsg_t msg,
    uint16_t rev, uint16_t fsize, const union tsdev_dev_tts8018_io_cmd_resp* resp);

typedef tsdev_err_t(*tsdev_io_tts8018_daq_event_t)(tsdev_handle_t handle, void* usr_arg, tsdev_tsmsg_t msg,
    uint16_t rev, uint16_t fsize, const union tsdev_dev_io_tts8018_daq_resp* daq);

	TSDEV_API tsdev_api_io_tts8018_cmd_async(tsdev_handle_t handle,
									 const union tsdev_dev_tts8018_io_cmd_resp* cmd);

	TSDEV_API tsdev_api_io_tts8018_cmd_reg_event(tsdev_handle_t handle,
										 void *usr_arg,
										 const tsdev_io_tts8018_cmd_event_t event);

	TSDEV_API tsdev_api_io_tts8018_cmd_unreg_event(tsdev_handle_t handle,
										   void *usr_arg,
										   const tsdev_io_tts8018_cmd_event_t event);

	TSDEV_API tsdev_api_io_tts8018_cmd_unreg_events(tsdev_handle_t handle);

    TSDEV_API tsdev_api_io_tts8018_daq_reg_event(tsdev_handle_t handle,
        void* usr_arg,
        const tsdev_io_tts8018_daq_event_t event);
    TSDEV_API tsdev_api_io_tts8018_daq_unreg_event(tsdev_handle_t handle,
        void* usr_arg,
        const tsdev_io_tts8018_daq_event_t event);
    TSDEV_API tsdev_api_io_tts8018_daq_unreg_events(tsdev_handle_t handle);

#ifdef __cplusplus
}
#endif

#endif
