/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_DEV_CONFIG_TYPES_H
#define __TSDEV_API_DEV_CONFIG_TYPES_H
#include "tsdev_types.h"
#include "tsdev_api_base_types.h"
#include "tsdev_api_eth_types.h"
#include "tsdev_api_can_types.h"
#include "tsdev_api_lin_types.h"
#include "tsdev_api_psi5_types.h"
#include "tsdev_api_sent_types.h"
#include "tsdev_api_flexray_types.h"
#include "tsdev_api_mng_types.h"
#include "tsdev_api_io_types.h"
#include "tsdev_api_logger_types.h"
#include "tsdev_api_mqtt_types.h"
#include "tsdev_api_socket2canfd_types.h"
#include "tsdev_api_ta1015_types.h"
#include "tsdev_api_ecat_config_types.h"


enum tsdev_dev_config_cmd_index_t
{
    tsdev_dev_config_cmd_reset = 0,
    tsdev_dev_config_cmd_write,
    tsdev_dev_config_cmd_read,
};

enum tsdev_dev_config_cmd_err_t
{
    tsdev_dev_config_cmd_err_ok = 0,
    tsdev_dev_config_cmd_err_nok,
};

struct tsdev_dev_config_cmd_t
{
    uint8_t index;     // enum tsdev_dev_config_cmd_index_t
    uint8_t err_code;  // enum tsdev_dev_config_cmd_err_t
    uint16_t data_cnt; // read or write data count
    uint8_t rev[12];
};

enum tsdev_dev_config_data_types_t
{
    tsdev_dev_config_invalid,
    tsdev_dev_config_can_conf,
    tsdev_dev_config_lin_conf,
    tsdev_dev_config_fr_conf,
    tsdev_dev_config_fr_cmd,
    tsdev_dev_cofnig_logger_cmd,
    tsdev_dev_config_eth_cmd,    
    tsdev_dev_config_can_sockets,
    tsdev_dev_config_uart_conf,
    tsdev_dev_config_ecat_can_filter_config,
    tsdev_dev_config_data_type_cnt,
};

struct tsdev_dev_config_data_t
{
    uint16_t type; // enum tsdev_dev_config_data_types_t
    uint16_t rev[3];
    union tsdev_dev_config_data_ptrs_t
    {
        struct tsdev_TPC_FDHardwareConf can;
        struct tsdev_lin_config_t lin_conf;
        struct tsdev_TPC_FlexrayConfig fr_conf;
        struct tsdev_TPC_FlexrayCmdReq fr_cmd;
        struct tsdev_PC_ETH_CMD_REQ eth_cmd;
        struct tsdev_mqtt_client_config_t mqtt_cmd;
        struct tsdev_Canfd_SocketConf_t can_sockets;
        struct tsdev_logger_cmd_req_t log_cmd;
        struct tsdev_uart_cmd_req_rsp_t rs485_config;
        tsdev_ecat_can_filter_config_t ecat_can_filter_config;
    } pars;
};

typedef tsdev_err_t (*tsdev_dev_config_cmd_event_t)(tsdev_handle_t handle, void* usr_arg, tsdev_tsmsg_t msg,
 uint16_t fdid, uint16_t fsize, const struct tsdev_dev_config_cmd_t* cmd_p);

typedef tsdev_err_t (*tsdev_dev_config_data_event_t)(tsdev_handle_t handle, void* usr_arg, tsdev_tsmsg_t msg,
 uint16_t fdid, uint16_t fsize, const struct tsdev_dev_config_data_t* data_p);

#endif