/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_RPC_H
#define __TSDEV_API_RPC_H

#include "tsdev_types.h"




#ifdef __cplusplus
extern "C"
{
#endif
	//only bit 0-14 for rpc_cmd is valid
	//cmd 0: call remote fun by char
	//cmd 1: call remote scan
	typedef tsdev_err_t(* tsdev_api_client_cmd0_callback_t)(
		tsdev_handle_t handle, void* usr_arg, const char* results);
	typedef tsdev_err_t(* tsdev_api_client_cmd1_callback_t)(
		tsdev_handle_t handle, void* usr_arg, uint16_t count);
	typedef tsdev_err_t(* tsdev_api_client_custom_callback_t)(
		tsdev_handle_t handle, void* usr_arg, uint16_t rpc_cmd, const uint8_t* par, uint16_t par_len);

	typedef tsdev_err_t(* tsdev_api_server_custom_callback_t)(
		tsdev_handle_t handle, void* usr_arg, uint16_t server_idx, uint16_t rpc_cmd, uint8_t cnt, const uint8_t* par, uint16_t par_len);

#if 0
    //for sec0
    TSDEV_API tsdev_api_rpc_requset_set_usr_key(tsdev_handle_t handle,
                                            const char *usr_name,
                                            const char *usr_key);
    //for sec1
    TSDEV_API tsdev_api_rpc_requset_set_private_pem(tsdev_handle_t handle,
                                                const char *pem);
#endif

	TSDEV_API tsdev_api_rpc_client_requset_cmd0_async(tsdev_handle_t handle, const char* cmd_args);
	TSDEV_API tsdev_api_rpc_client_cmd0_reg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_api_client_cmd0_callback_t event);
	TSDEV_API tsdev_api_rpc_client_cmd0_unreg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_api_client_cmd0_callback_t event);
	TSDEV_API tsdev_api_rpc_client_cmd0_unreg_events(tsdev_handle_t handle);

	TSDEV_API tsdev_api_rpc_client_requset_cmd1_async(tsdev_handle_t handle);
	TSDEV_API tsdev_api_rpc_client_cmd1_reg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_api_client_cmd1_callback_t event);
	TSDEV_API tsdev_api_rpc_client_cmd1_unreg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_api_client_cmd1_callback_t event);
	TSDEV_API tsdev_api_rpc_client_cmd1_unreg_events(tsdev_handle_t handle);

	TSDEV_API tsdev_api_rpc_client_requset_custom_async(tsdev_handle_t handle, uint16_t rpc_cmd, uint16_t par_len, const uint8_t* par);
	TSDEV_API tsdev_api_rpc_client_custom_reg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_api_client_custom_callback_t event);
	TSDEV_API tsdev_api_rpc_client_custom_unreg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_api_client_custom_callback_t event);
	TSDEV_API tsdev_api_rpc_client_custom_unreg_events(tsdev_handle_t handle);

	TSDEV_API tsdev_api_rpc_server_custom_reg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_api_server_custom_callback_t event);
	TSDEV_API tsdev_api_rpc_server_custom_unreg_event(tsdev_handle_t handle, void* usr_arg, const tsdev_api_server_custom_callback_t event);
	TSDEV_API tsdev_api_rpc_server_custom_unreg_events(tsdev_handle_t handle);

	TSDEV_API tsdev_api_rpc_server_resp_custom(tsdev_handle_t handle, uint16_t server_idx, uint16_t rpc_cmd, uint8_t cnt, const uint8_t* par, uint16_t par_len);

#ifdef __cplusplus
}
#endif

#endif