/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_USRMODULE_H
#define __TSDEV_API_USRMODULE_H

#include "tsdev_types.h"
#include "tsdev_api_usrmodule_types.h"

#ifdef __cplusplus
extern "C"
{
#endif

    TSDEV_API tsdev_api_usrmodule_download_image(tsdev_handle_t handle,
                                           const uint8_t *image,
                                           uint64_t length,
                                           void* usr_arg,
                                           tsdev_dev_usrmodule_cmd_event_t cmd_evt,
                                           tsdev_usrmodule_data_trans_callback_t data_evt,
                                           uint32_t timeout_ms);

    TSDEV_API tsdev_api_usrmodule_send_cmd(tsdev_handle_t handle,
                                    uint8_t cmd_type, 
                                    uint32_t image_runtime);
                                    
    TSDEV_API tsdev_api_dev_usrmodule_cmd_reg_event(tsdev_handle_t handle,
        void* usr_arg,
        tsdev_dev_usrmodule_cmd_event_t event);

#ifdef __cplusplus
}
#endif

#endif
