/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_IO_TTS8517_H
#define __TSDEV_API_IO_TTS8517_H

#include "tsdev_types.h"

#ifdef __cplusplus
extern "C"
{
#endif

    enum tsdev_dev_io_tts8517_cmd_enum {
        tsdev_dev_tts8517_daq_set = 0,
        tsdev_dev_tts8517_full_read = 1,
        tsdev_dev_tts8517_full_write = 2,
        tsdev_dev_tts8517_fiu_read = 3,
        tsdev_dev_tts8517_fiu_write = 4,
    };

    enum tsdev_dev_io_tts8517_daq_enum {
        tsdev_dev_tts8517_full_report = 0,
    };

    union tsdev_dev_io_tts8517_cmd_resp {
        uint8_t rev[8];
        struct tsdev_dev_io_tts8517_daq_set_cmd_resp {
            // bit 0 - 6: tsdev_dev_io_tts8517_cmd_enum
            // bit 7: op_valid_ok (cmd: cmd valid;  resp: op ok)
            uint8_t cmd;
            uint8_t daq_enum; // tsdev_dev_io_tts8517_daq_enum
            uint8_t rev[2];
            uint32_t period_time_ms;
        } tts8517_daq_set_cmd_resp;
        struct tsdev_dev_io_tts8517_full_cmd_resp {
            // bit 0 - 6: tsdev_dev_io_tts8517_cmd_enum
            // bit 7: op_valid_ok (cmd: cmd valid;  resp: op ok)
            uint8_t cmd;
            // fiu[0]bit[0]: ch1 fiu_open, fiu[0]bit[1]: ch1 fiu_vbat, fiu[0]bit[2]: ch1 fiu_gnd, fiu[0]bit[3]: ch1 fiu_com,
            // fiu[0]bit[4]: ch2 fiu_open, fiu[0]bit[5]: ch2 fiu_vbat, fiu[0]bit[6]: ch2 fiu_gnd, fiu[0]bit[7]: ch2 fiu_com,
            // ...
            // fiu[4]bit[4]: ch10 fiu_open, fiu[4]bit[5]: ch10 fiu_vbat, fiu[4]bit[6]: ch10 fiu_gnd, fiu[4]bit[7]: ch10 fiu_com,
            uint8_t fiu[5];
        } tts8517_full_cmd_resp;
        struct tsdev_dev_io_tts8517_fiu_cmd_resp {
            // bit 0 - 6: tsdev_dev_io_tts8517_cmd_enum
            // bit 7: op_valid_ok (cmd: cmd valid;  resp: op ok)
            uint8_t cmd;
            uint8_t idx; // 0: ch1, 1: ch2, ... 9: ch10
            uint8_t type; // 0: open, 1: vbat, 2: gnd, 3: com, 
            uint8_t status; // 0: not set, 1: set
        } tts8517_fiu_cmd_resp;
    };

    union tsdev_dev_io_tts8517_daq_resp {
        uint8_t rev[16];
        struct tsdev_dev_io_tts8517_full_report
        {
            uint64_t timestamp;
            // bit 0 - 6: tsdev_dev_io_tts8517_daq_enum
            // bit 7: op_valid_ok (cmd: cmd valid;  resp: op ok)
            uint8_t cmd;
            // fiu[0]bit[0]: ch1 fiu_open, fiu[0]bit[1]: ch1 fiu_vbat, fiu[0]bit[2]: ch1 fiu_gnd, fiu[0]bit[3]: ch1 fiu_com,
            // fiu[0]bit[4]: ch2 fiu_open, fiu[0]bit[5]: ch2 fiu_vbat, fiu[0]bit[6]: ch2 fiu_gnd, fiu[0]bit[7]: ch2 fiu_com,
            // ...
            // fiu[4]bit[4]: ch10 fiu_open, fiu[4]bit[5]: ch10 fiu_vbat, fiu[4]bit[6]: ch10 fiu_gnd, fiu[4]bit[7]: ch10 fiu_com,
            uint8_t fiu[5];
        } tts8517_full_report;
    };

    typedef tsdev_err_t(*tsdev_io_tts8517_cmd_event_t)(tsdev_handle_t handle, void* usr_arg, tsdev_tsmsg_t msg,
        uint16_t rev, uint16_t fsize, const union tsdev_dev_io_tts8517_cmd_resp* resp);

    typedef tsdev_err_t(*tsdev_io_tts8517_daq_event_t)(tsdev_handle_t handle, void* usr_arg, tsdev_tsmsg_t msg,
        uint16_t rev, uint16_t fsize, const union tsdev_dev_io_tts8517_daq_resp* daq);


	TSDEV_API tsdev_api_io_tts8517_cmd_async(tsdev_handle_t handle,
									 const union tsdev_dev_io_tts8517_cmd_resp* cmd);

	TSDEV_API tsdev_api_io_tts8517_cmd_reg_event(tsdev_handle_t handle,
										 void *usr_arg,
										 const tsdev_io_tts8517_cmd_event_t event);

	TSDEV_API tsdev_api_io_tts8517_cmd_unreg_event(tsdev_handle_t handle,
										   void *usr_arg,
										   const tsdev_io_tts8517_cmd_event_t event);

	TSDEV_API tsdev_api_io_tts8517_cmd_unreg_events(tsdev_handle_t handle);

	TSDEV_API tsdev_api_io_tts8517_daq_reg_event(tsdev_handle_t handle,
										 void *usr_arg,
										 const tsdev_io_tts8517_daq_event_t event);

	TSDEV_API tsdev_api_io_tts8517_daq_unreg_event(tsdev_handle_t handle,
										   void *usr_arg,
										   const tsdev_io_tts8517_daq_event_t event);

	TSDEV_API tsdev_api_io_tts8517_daq_unreg_events(tsdev_handle_t handle);

#ifdef __cplusplus
}
#endif

#endif