/**
 * Copyright (c) 2025:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_WIN_RT_H
#define __TSDEV_API_WIN_RT_H

#include "tsdev_types.h"




#ifdef __cplusplus
extern "C"
{
#endif

#ifndef LIBTSDEVBASERT_EXPORTS
#ifdef _MSC_VER
	//api for host only
	//TSDEV_API tsdev_api_rt_init(void);
	TSDEV_API tsdev_api_rt_netif_get_cnt(uint16_t* count);
	TSDEV_API tsdev_api_rt_netif_get_name(uint16_t idx, const char** name);
	TSDEV_API tsdev_api_rt_netif_open(const char* name);
	TSDEV_API tsdev_api_rt_netif_set_ipv4(const char* name, uint8_t ip[4], uint8_t mask[4], uint8_t gw[4]);
	TSDEV_API tsdev_api_rt_netif_set_mac(const char* name, uint8_t mac[6]);
	TSDEV_API tsdev_api_rt_netif_close(const char* name);

	TSDEV_API tsdev_api_rt_usb_controler_get_cnt(uint16_t* count);
	TSDEV_API tsdev_api_rt_usb_controler_get_name(uint16_t idx, const char** name);

	TSDEV_API tsdev_api_rt_uninit(void);
#endif
#endif

#ifdef __cplusplus
}
#endif

#endif
