/*
Copyright (c) 2024:Shanghai TOSUN Technology Ltd.

The software mentioned in this copyright statement includes the automatic code generator function module of TSMaster software and the embedded code it generates. Among them, the copyright of the automatic code generation function module of TSMaster software is owned by Shanghai TOSUN Technology Ltd..It is protected by the Copyright Law of the People's Republic of China, the Regulations on the Protection of Computer Software, the Intellectual Property Protection Law, the Patent Law of the People's Republic of China and relevant international copyright treaties, laws, regulations, and other intellectual property laws and treaties.

The embedded code generated by the automatic code generation function of the TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN Technology Ltd. or the original copyright owner of the embedded code, and is only for personal learning and use. Shanghai TOSUN Technology Ltd. does not provide any kind of warranty, whether express or implied. All risks are borne by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint responsibility.

The semiconductor manufacturer's LOGO and product model displayed in the TSMaster are only for the convenience of user selection and useage,its copyright and ownership remain with the respective copyright owners,Shanghai TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for this, and does not assume joint and several liability for any possible infringement.

Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the software mentioned in this copyright statement without notifying users, and reserves the right to modify this license agreement.
*/
#ifndef TSDEV_USR_TYPES_MODULE_H
#define TSDEV_USR_TYPES_MODULE_H

#include <stddef.h>
#include "tsdev_api_sim_types.h"
#include "tsdev_api_can_types.h"
#include "tsdev_api_eth_types.h"
#include "tsdev_api_flexray_types.h"
#include "tsdev_api_lin_types.h"
#include "tsdev_api_io_types.h"

struct tsdev_usr_module_fun
{
	const char* fun_name;
	void* fun_ptr;
	size_t offset;
};

struct tsdev_usr_module_core_desc;
struct tsdev_usr_core_handle;
typedef struct tsdev_usr_core_handle* tsdev_usr_core_handle_t;

/* Central list of host API symbols exported to user modules. */
#define TSDEV_USR_MODULE_FUNC_LIST(OP) \
	OP("tsdev_api_log_out", tsdev_api_log_out) \
	OP("tsdev_api_malloc", tsdev_api_malloc) \
	OP("tsdev_api_free", tsdev_api_free) \
	OP("tsdev_api_get_device_cnt", tsdev_api_get_device_cnt) \
	OP("tsdev_api_get_device_handle", tsdev_api_get_device_handle) \
	\
	OP("tsdev_api_can_configure_regs_async", tsdev_api_can_configure_regs_async) \
	OP("tsdev_api_can_transmit_async", tsdev_api_can_transmit_async) \
	OP("tsdev_api_can_frame_receive", tsdev_api_can_frame_receive) \
	\
	OP("tsdev_api_eth_tx_cmd_async", tsdev_api_eth_tx_cmd_async) \
	OP("tsdev_api_eth_transmit_async", tsdev_api_eth_transmit_async) \
	OP("tsdev_api_eth_fifo_receive_msgs", tsdev_api_eth_fifo_receive_msgs) \
	\
	OP("tsdev_api_flexray_set_controller_frametrigger", tsdev_api_flexray_set_controller_frametrigger) \
	OP("tsdev_api_flexray_cmdreq", tsdev_api_flexray_cmdreq) \
	OP("tsdev_api_flexray_start_net", tsdev_api_flexray_start_net) \
	OP("tsdev_api_flexray_stop_net", tsdev_api_flexray_stop_net) \
	OP("tsdev_api_flexray_wakeup_pattern", tsdev_api_flexray_wakeup_pattern) \
	OP("tsdev_api_flexray_transmit_async", tsdev_api_flexray_transmit_async) \
	OP("tsdev_api_flexray_receive", tsdev_api_flexray_receive) \
	\
	OP("tsdev_api_io_cmd_async", tsdev_api_io_cmd_async) \
	\
	OP("tsdev_api_lin_config", tsdev_api_lin_config) \
	OP("tsdev_api_lin_transmit_async", tsdev_api_lin_transmit_async) \
	OP("tsdev_api_lin_fifo_receive_msgs", tsdev_api_lin_fifo_receive_msgs) \
	\
	OP("tsdev_api_sim_sig_get_cnt", tsdev_api_sim_sig_get_cnt) \
	OP("tsdev_api_sim_sig_get_defs", tsdev_api_sim_sig_get_defs) \
	OP("tsdev_api_sim_core_current", tsdev_api_sim_core_current) \
	OP("tsdev_api_sim_dp_group_fifo_receive_msgs", tsdev_api_sim_dp_group_fifo_receive_msgs)

/* Lifecycle callbacks exposed to user modules; field names must stay aligned with exported symbols. */
/* Leave entries as NULL when the module does not implement the corresponding hook. */
struct sim_callbacks {
	tsdev_start_t tsdev_start;
	tsdev_cycle_entry_pre_t tsdev_cycle_entry_pre;
	tsdev_cycle_entry_t tsdev_cycle_entry;
	tsdev_cycle_entry_after_t tsdev_cycle_entry_after;
	tsdev_stop_t tsdev_stop;

	tsdev_can_cmd_event_t tsdev_can_cmd_event;
	tsdev_can_frame_event_t tsdev_can_frame_event;

	tsdev_api_eth_cmd_event_t tsdev_api_eth_cmd_event;
	tsdev_api_eth_frame_event_t tsdev_api_eth_frame_event;

	tsdev_flexray_cmd_resp_event_t tsdev_flexray_cmd_resp_event;
	tsdev_flexray_frame_event_t tsdev_flexray_frame_event;

	tsdev_io_cmd_event_t tsdev_io_cmd_event;
	tsdev_io_daq_event_t tsdev_io_daq_event;

	tsdev_lin_cmd_event_t tsdev_lin_cmd_event;
	tsdev_lin_frame_event_t tsdev_lin_frame_event;
};

#endif // _UDS_APP_IF_H
