/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_TAC_TYPES_H
#define __TSDEV_API_TAC_TYPES_H
#include "tsdev_api_base_types.h"

enum tsdev_tac_cmd_idx_t
{
    tsdev_tac_cmd_read_hw_info = 0,
    tsdev_tac_cmd_dowload_image,
    tsdev_tac_cmd_run_once_image,
    tsdev_tac_cmd_run_image,
    tsdev_tac_cmd_stop_image,
    tsdev_tac_cmd_del_all_image,
    tsdev_tac_cmd_del_image_by_type,
};

typedef enum tsdev_tac_exe_type_e
{
    TAC_ONCE_EXE = 0,
    TAC_CAN_RECV_EXE,
    TAC_CAN_SEND_EXE,
    TAC_CAN_PRE_SEND_EXE,
    TAC_TYPE_CNT,
}tsdev_tac_exe_type_t;

struct tsdev_tac_cmd_t
{
    uint16_t cmd_idx;    
    uint16_t err_code; // tsdev_err_t
    uint8_t image_type;
    uint8_t rev2[11];
};

typedef struct tsdev_tac_config_s
{
    struct {
        char tac_name[23];
        uint8_t tac_type;   // tsdev_tac_exe_type_t        
    } tac_info_t;
    const uint8_t* image_buf;
    uint64_t image_length;    
} tsdev_tac_config_t;


typedef tsdev_err_t(*tsdev_tac_cmd_event_t)(tsdev_handle_t handle, void* usr_arg, tsdev_tsmsg_t msg,
    uint16_t rev, uint16_t fsize, const struct tsdev_tac_cmd_t* cmd);

// total_len: total len of transmit (TX/RX)
// data: data trans complete of this callback
typedef void (*tsdev_tac_data_event_t)(tsdev_handle_t handle,
                                       void* usr_arg,
                                       uint64_t total_len,
                                       const uint8_t *data,
                                       uint16_t len,
                                       tsdev_err_t err);

#endif
