/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_LOGGER_TYPES_H__
#define __TSDEV_API_LOGGER_TYPES_H__
#include "tsdev_api_base_types.h"

/*******************************************************************************
 * For logger API version 0.0
 ******************************************************************************/
struct tsdev_logger_record_info_t
{
    uint32_t utc_date;
    uint32_t utc_time;
    uint32_t sector_start;
    uint32_t sector_nums;
    uint32_t local_time_ms;
};

struct tsdev_logger_export_info_t
{
    uint8_t record_idx;
    uint32_t sector_start;
    uint32_t sector_nums;
};

struct tsdev_rtc_data_t
{
    uint32_t utc_date; // B0 - day, B1 - mon, B3 - year_l, B4 - year_h
    uint32_t utc_time; // B0 - sec, B1 - min, B2 - hour, B3 - 0
};

struct tsdev_gps_data_t
{
    uint64_t FTimeUS; // default = 0
    uint32_t UTCTime; // B0 - sec, B1 - min, B2 - hour, B3 - 0
    uint32_t UTCDate; // B0 - day, B1 - mon, B3 - year_l, B4 - year_h
    uint32_t Latitude;
    uint32_t Longitude;
    uint32_t Speed;    // km/h
    uint32_t Direct;   // ?
    uint32_t Altitude; // ?
    uint8_t N_S;       // 0 - N, 1 - S
    uint8_t E_W;       // 0 - E, 1 - W
    uint8_t Satellite; // enum tsdev_satellite_t
    uint8_t FIdxChn;   // default = 0
};

struct tsdev_gps_config_t
{
    uint8_t enable;
    uint8_t freq; // HZ
};

enum tsdev_logger_mode_t
{
    tsdev_logger_mode_ilde = 0,
    tsdev_logger_mode_record_on,
    tsdev_logger_mode_replay,
    // cmd
    tsdev_logger_mode_config,
};

struct tsdev_logger_mode_pars_t
{
    uint8_t mode; // enum tsdev_logger_mode_t
    uint8_t rev[7];
    struct tsdev_logger_mode_cmd_config_t
    {
        uint64_t record_max_size; // (bytes) 0 - no limit
    } config;
};

typedef tsdev_err_t (*tsdev_logger_event_t)(tsdev_handle_t handle, void *usr_arg,
                                            tsdev_tsmsg_t msg, uint16_t FCommand, uint8_t FStatus, uint8_t FProgramState,
                                            uint32_t FDataCnt, uint8_t *data);

typedef tsdev_err_t (*tsdev_logger_gps_event_t)(tsdev_handle_t handle, void *usr_arg, tsdev_tsmsg_t msg,
                                                uint16_t rev, uint16_t fsize, const struct tsdev_gps_data_t *data);

/*******************************************************************************
 * For logger API version 1.0
 ******************************************************************************/
enum tsdev_logger_cmd_enum
{
	tsdev_logger_cmd_get_disk_info = 0,
	tsdev_logger_cmd_set_disk_info,
	tsdev_logger_cmd_get_file_info,
	tsdev_logger_cmd_file_export_start,
	tsdev_logger_cmd_file_export_stop,
	tsdev_logger_cmd_record_on,
	tsdev_logger_cmd_record_off,
	tsdev_logger_cmd_set_rtc,
	tsdev_logger_cmd_get_rtc,
	tsdev_logger_cmd_set_gps,
	tsdev_logger_cmd_config,
	tsdev_logger_cmd_file_cutting,
	tsdev_logger_cmd_file_delete,
};

enum tsdev_logger_disk_type_enum
{
	tsdev_logger_disk_emmc = 0,
	tsdev_logger_disk_sd,
	tsdev_logger_disk_ssd,
};

enum tsdev_logger_data_type_enum
{
	tsdev_logger_data_all = 0,
	tsdev_logger_data_can,
	tsdev_logger_data_lin,
	tsdev_logger_data_flexray,
	tsdev_logger_data_eth,
	tsdev_logger_data_gps,
	tsdev_logger_data_cnt,
};

enum tsdev_logger_err_enum
{
	tsdev_logger_err_ok = 0,
	tsdev_logger_err_nok,
};

enum tsdev_logger_file_type_enum
{
	tsdev_logger_raw,
	tsdev_logger_blf,
	tsdev_logger_asc,
};

enum tsdev_logger_cycle_record_enum
{
	tsdev_logger_cycle_no,
	tsdev_logger_cycle_yes,
};

enum tsdev_logger_file_delete_type_enum
{
	tsdev_logger_delete_invalid,
	tsdev_logger_delete_from_head,
	tsdev_logger_delete_from_tail,
	tsdev_logger_delete_all,
};

struct tsdev_logger_disk_t
{
	uint64_t total_sz;
	uint64_t used_sz;
	uint8_t partition_cnt;
	uint8_t file_type; //enum tsdev_logger_file_type_enum
	uint8_t is_cycle; //enum tsdev_logger_cycle_record_enum cyclic overwriting
	uint8_t rev[5];
	struct tsdev_logger_partition_t
	{
		uint64_t total_sz;
		uint64_t used_sz;
		uint8_t data_type; // enum tsdev_logger_data_type_enum
		uint8_t rev[5];
		uint16_t file_cnt;
		uint64_t f_cut_size;
	} partition[8];
};

struct tsdev_logger_file_t
{
	uint32_t create_utc_date;
	uint32_t create_utc_time;
	uint32_t modify_utc_date;
	uint32_t modify_utc_time;
	uint32_t msg_cnt;
	uint8_t d_idx;  	// disk index
	uint8_t p_idx;      // partition index
	uint16_t f_idx;     // file index
	uint32_t size_kb;   // 1kb = 1024bytes
	uint16_t trigger_cnt;
	uint8_t  file_type; //enum tsdev_logger_file_type_enum
	uint8_t open_flag; //0:write,1:read
	struct tsdev_logger_trigger_t
	{
		uint32_t rx_cnt;
		uint32_t value;
		uint32_t utc_date;
		uint32_t utc_time;
	}trigger_info[32];
};

enum tsdev_logger_cmdq_exec_condition_enum
{
	tsdev_logger_cmdq_on_powerup = 0,
	tsdev_logger_cmdq_on_timer,
};

struct tsdev_cmdq_header_t
{
	uint8_t exec_cond; // enum tsdev_logger_cmdq_exec_condition_enum
	uint8_t rev[3];
	uint16_t fdid;
	uint16_t fsize;
	union tsdev_logger_cmdq_pars_t
	{
		uint8_t rev[8];
		struct tsdev_logger_cmdq_on_timer_t
		{
			uint32_t period_ms;
		} on_timer;
	} pars;
};
struct tsdev_logger_gps_config_t
{
	uint32_t period_ms;
	uint8_t  enable;
	uint8_t  rev[3];

};

struct tsdev_logger_rtc_config_t
{
	uint8_t sec;
	uint8_t min;
	uint8_t hour;
	uint8_t day;
	uint8_t week_day;
	uint8_t month;
	uint16_t year;
};

struct tsdev_logger_gps_data_t
{
	uint64_t FTimeUS; // default = 0
	uint32_t UTCTime; // B0 - sec, B1 - min, B2 - hour, B3 - 0
	uint32_t UTCDate; // B0 - day, B1 - mon, B3 - year_l, B4 - year_h
	uint32_t Latitude;
	uint32_t Longitude;
	uint32_t Speed; // km/h
	uint32_t Direct; // ?
	uint32_t Altitude; // ?
	uint8_t N_S; // 0 - N, 1 - S
	uint8_t E_W; // 0 - E, 1 - W
	uint8_t Satellite; // enum tsdev_satellite_t
	uint8_t FIdxChn; // default = 0
};

// trigger data
struct tsdev_logger_trigger_data_t
{
	uint64_t timestamp_us;
	uint8_t rev[8];
};

struct tsdev_logger_config_t
{
	uint8_t disk_sel_idx; // enum tsdev_logger_disk_type_enum
	uint8_t rev[7];
};

struct tsdev_logger_cmd_req_t
{
	uint8_t cmd;//enum tsdev_logger_cmd_enum
	uint8_t rev[7];
	union tsdev_logger_cmd_req_pars_t
	{
		struct tsdev_logger_disk_t disk; // tsdev_logger_cmd_set_disk_info
		struct tsdev_logger_file_info_req_t
		{
			uint8_t disk_idx;
			uint8_t partition_idx;
			uint8_t rev[6];
		} file_info;
		struct tsdev_logger_file_export_start_req_t
		{
			uint8_t disk_idx;
			uint8_t partition_idx;
			uint8_t rev[2];
			uint32_t file_idx;
			uint32_t start_cnt;
			uint32_t end_cnt;
		} export_info; // start/stop
		struct tsdev_logger_config_t config_info; //tsdev_logger_cmd_config
		struct tsdev_logger_delete_t
		{
			uint8_t partition_idx;
			uint8_t delete_type;//enum tsdev_logger_file_delete_type_enum
			uint8_t rev[2];
			uint32_t delete_cnt;
		}delete_info;
	} pars;
};

struct tsdev_logger_cmd_rsp_t
{
	uint8_t cmd;
	uint8_t err;
	uint8_t rev[6];
	union tsdev_logger_cmd_rsp_pars_t
	{
		struct tsdev_logger_disk_t disk;
		struct tsdev_logger_file_t file;
		struct tsdev_logger_file_export_start_rsp_t
		{
			uint8_t disk_idx;
			uint8_t partition_idx;
			uint16_t file_idx;
		} export_start;
		struct tsdev_logger_rtc_config_t rtc_info;
	} pars;
};
typedef tsdev_err_t (*tsdev_logger_v1_event_t)(tsdev_handle_t handle, void *usr_arg, tsdev_tsmsg_t msg,
                                               uint16_t rev, uint16_t fsize, const struct tsdev_logger_cmd_rsp_t *data);

#endif