/**
 * Copyright (c) 2026:Shanghai TOSUN Technology Ltd.
 *
 * The software mentioned in this copyright statement includes the automatic
 * code generator function module of TSMaster software and the embedded code it
 * generates. Among them, the copyright of the automatic code generation
 * function module of TSMaster software is owned by Shanghai TOSUN Technology
 * Ltd..It is protected by the Copyright Law of the People's Republic of China,
 * the Regulations on the Protection of Computer Software, the Intellectual
 * Property Protection Law, the Patent Law of the People's Republic of China and
 * relevant international copyright treaties, laws, regulations, and other
 * intellectual property laws and treaties.
 *
 * The embedded code generated by the automatic code generation function of the
 * TSMaster is a non-commercial code whose copyright belongs to Shanghai TOSUN
 * Technology Ltd. or the original copyright owner of the embedded code, and is
 * only for personal learning and use. Shanghai TOSUN Technology Ltd. does not
 * provide any kind of warranty, whether express or implied. All risks are borne
 * by the user, and Shanghai TOSUN Technology Ltd. does not assume any joint
 * responsibility.
 *
 * The semiconductor manufacturer's LOGO and product model displayed in the
 * TSMaster are only for the convenience of user selection and useage,its
 * copyright and ownership remain with the respective copyright owners,Shanghai
 * TOSUN Technology Ltd. does not provide any guarantee and rights guarantee for
 * this, and does not assume joint and several liability for any possible
 * infringement.
 *
 * Shanghai TOSUN Technology Ltd. reserves the right to modify and upgrade the
 * software mentioned in this copyright statement without notifying users, and
 * reserves the right to modify this license agreement.
 */
#ifndef __TSDEV_API_LOGGER_H
#define __TSDEV_API_LOGGER_H
#include "tsdev_types.h"

#ifdef __cplusplus
extern "C"
{
#endif

    TSDEV_API tsdev_api_logger_reg_event(tsdev_handle_t handle, void *usr_arg, uint16_t FCommand, tsdev_logger_event_t event);

    TSDEV_API tsdev_api_logger_unreg_event(tsdev_handle_t handle, void *usr_arg, uint16_t FCommand, tsdev_logger_event_t event);

    TSDEV_API tsdev_api_logger_gps_reg_event(tsdev_handle_t handle, void* usr_arg, tsdev_logger_gps_event_t event);

    TSDEV_API tsdev_api_logger_gps_unreg_event(tsdev_handle_t handle, void* usr_arg, tsdev_logger_gps_event_t event);

    TSDEV_API tsdev_api_logger_unreg_events(tsdev_handle_t handle);

    /**
     * @brief set logger mode
     * @param[in] handle pointer to device handle
     * @param[in] cmd_p struct tsdev_logger_mode_pars_t
     * @return if 0, ok, else nok.
     * @note FCommand = 15
     */
    TSDEV_API tsdev_api_logger_set_mode(tsdev_handle_t handle, const struct tsdev_logger_mode_pars_t* pars_p);
    /**
     * @brief get record list, max nums is 128
     * @param[in] handle pointer to device handle
     * @return if 0, ok, else nok.
     * @note FCommand = 11, cmd response data (struct tsdev_logger_record_info_t)
     */
    TSDEV_API tsdev_api_logger_get_record(tsdev_handle_t handle, uint8_t index);
    /**
     * @brief delete record list
     * @param[in] handle pointer to device handle
     * @return if 0, ok, else nok.
     * @note FCommand = 11
     */
    TSDEV_API tsdev_api_logger_delete_record(tsdev_handle_t handle);
    /**
     * @brief start export
     * @param[in] handle pointer to device handle
     * @return if 0, ok, else nok.
     * @note FCommand = 13, cmd response data (struct tsdev_logger_record_info_t), to check progress
     */
    TSDEV_API tsdev_api_logger_start_export(tsdev_handle_t handle, uint8_t record_idx);
    /**
     * @brief stop export
     * @param[in] handle pointer to device handle
     * @return if 0, ok, else nok.
     * @note FCommand = 13, cmd response data (struct tsdev_logger_record_info_t)
     */
    TSDEV_API tsdev_api_logger_stop_export(tsdev_handle_t handle);
    /**
     * @brief set rtc date and time
     * @param[in] handle pointer to device handle
     * @param[in] config struct tsdev_rtc_config_t
     * @return if 0, ok, else nok.
     * @note FCommand = 16
     */
    TSDEV_API tsdev_api_logger_set_rtc(tsdev_handle_t handle, const struct tsdev_rtc_data_t* data);
    /**
     * @brief get rtc date and time
     * @param[in] handle pointer to device handle
     * @param[in] config struct tsdev_rtc_config_t
     * @return if 0, ok, else nok.
     * @note FCommand = 17
     */
    TSDEV_API tsdev_api_logger_get_rtc(tsdev_handle_t handle);
    /**
     * @brief set gps config param
     * @param[in] handle pointer to device handle
     * @param[in] config struct tsdev_gps_config_t
     * @return if 0, ok, else nok.
     * @note FCommand = 14
     */
    TSDEV_API tsdev_api_logger_set_gps(tsdev_handle_t handle, const struct tsdev_gps_config_t *config);

#ifdef __cplusplus
}
#endif

#endif